### ISSUE TITLE
Coc reports "rename provider not found" when trying to rename a symbol

### ISSUE THREAD

**Issue by gfarrell** [haskell/haskell-language-server#1660] opened 2021-04-03 12:47 UTC
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /usr/bin/haskell-language-server-wrapper) (GIT hash: 4cd1cf934638881e52b3eba9f70157a4b799c0e9)
Tool versions found on the $PATH
cabal:          Not found
stack:          2.5.1
ghc:            Not found
```

Which OS do you use: *ArchLinux*
Which lsp-client do you use: *Neovim (coc.nvim)*
Describe your project (alternative: link to the project): [project link](https://github.com/gfarrell/tron-lines)

Contents of `hie.yaml`:
```yaml
cradle:
  stack:
```

### Steps to reproduce
Using a minimal example
```haskell
module Simulation () where

data MyData = MyData Int Int Int

doSomething :: MyData -> Int
doSomething (MyData x y z) = x + y + z
```

Put the cursor over `MyData' on the line defining the `MyData` type and [trigger the action I have defined for `coc-rename`](https://github.com/gfarrell/dotfiles/blob/master/neovim/init.vim#L207) in order to try renaming `MyData` to `MyOtherData`.

### Expected behaviour
A little dialogue should show allowing me to rename `MyData` and have that change reflected across the codebase.

### Actual behaviour
A warning appears saying:
```
[coc.nvim]: Error on notification "rename": rename provider not found for current buffer, your language server don't [sic] support it.
```

I'm happy to help debug further, but I don't know if this is a Coc problem or an HLS problem, although rename does work in other languages (e.g. Typescript).

**Comment by eddiemundo** [comment] 2021-04-03 14:30
Renaming is not actually implemented yet. See #282.

**Comment by Ailrun** [comment] 2021-04-03 15:15
Duplicate of #282.

**Closed** 2021-04-03 15:15 UTC
Labels: component: retrie plugin, pr welcome, type: enhancement

**Comment by gfarrell** [comment] 2021-04-04 13:46
Ok thanks, wasn’t sure so I searched but clearly missed #282
