### ISSUE TITLE
Nix installation?

### ISSUE THREAD

**Issue by spacekitteh** [haskell/haskell-language-server#122] opened 2020-05-23 05:57 UTC
Anyone have a nix expression to install this?

**Comment by korayal** [comment] 2020-05-23 12:05
When I have spare time, I try to keep up with the master branch for GHC
8.6.5 here:

https://github.com/korayal/hls-nix

It also has a cachix cache for darwin & linux

**Comment by 414owen** [comment] 2020-05-23 20:56
@korayal I tried out a bunch of different derivations I found floating around.
Yours is the only one that worked out of the box.
If you're happy to maintain this, it would be great to add a link to hls-nix from the haskell-language-server readme. Might prevent a few other people from waiting for GHC builds.

**Comment by alanz** [comment] 2020-05-24 09:57
Would anyone like to update the README to reflect this?

**Comment by korayal** [comment] 2020-05-24 10:43
@414owen I don't think my version is useful for everyone using nix, because the build is only confirmed on the fixed nixpkgs version I'm using on GHC 8.6.5. The nix expression could be useful for people trying this out on their own versions. I don't plan on maintaining this on any other combinations than what I use at the time. Even 'that' takes ~0-2 hours of my time depending on the change in dependencies.

It would be nice to build a `hls` clone for [all-hies](https://github.com/Infinisil/all-hies) though. But unfortunately, I do not have the time to do that. but if someone does, I can support and contribute to that effort when I have the spare time.

**Comment by 414owen** [comment] 2020-05-24 13:25
@korayal fair enough. I might look into supporting more GHC versions and setting up CI.
Thanks for bootstrapping a build :)

**Comment by zypeh** [comment] 2020-05-25 10:25
Is it ok if I work on this? I am learning Nix packaging and try to build hls on Nix too.

**Comment by korayal** [comment] 2020-05-25 16:56
@414owen thanks! Btw, I did kick off a clone of `ghcide-nix` on a branch [here](https://github.com/korayal/hls-nix/tree/multi-version) for `hls-nix` and started a build for `hls-ghc865`. it could take hours, so I don't know if it will succeed on first try. but I think if we can make it build and push to a cache, it would be pretty easy to maintain. Maybe @domenkozar can help us out here.

@zypeh this can also be useful if you wanted to take on this challenge.

@zypeh this also can help you out. if you like to

**Comment by domenkozar** [comment] 2020-05-25 18:02
Would you be up to having Nix expressions in this repo? That would really make things easy.

**Comment by zypeh** [comment] 2020-05-25 18:07
@domenkozar you mean having the nix files working directly on this repo?

**Comment by domenkozar** [comment] 2020-05-25 19:03
Yup.

**Comment by korayal** [comment] 2020-05-25 19:16
My take above using `ghcide-nix`'s `haskell.nix` method failed for this project, which I think is related to `stack-to-nix`, I got the error below:

```
substituteStream(): WARNING: pattern '# nix-sha256:' doesn't match anything in file 'stack-8.6.5.yaml'
fatal: not a tree object: fb3859dca2e54d1bbb2c873e68ed225fa179fbef
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
```
Which, I think is related to [this dependency](https://github.com/haskell/haskell-language-server/blob/master/stack-8.6.5.yaml#L41-L42)

**Comment by domenkozar** [comment] 2020-05-26 07:57
It's quite tricky. As part of https://nix.dev/ I plan to write also a tutorial for haskell.nix

**Comment by korayal** [comment] 2020-05-26 11:09
On my [latest take](https://github.com/korayal/hls-nix/tree/42af4b216dc725ff81f78376e47b1d69a7b26f47) I was able to build for **GHC 8.8.3** and **8.6.5**, but not others. [GHC 8.10.1 is not supported by haskell.nix yet](https://github.com/input-output-hk/haskell.nix/pull/541). I haven't digged deeper for **8.8.2** and **8.6.4**.

On the other hand, since haskell-language-server exposes two executables (`haskell-language-server` and `haskell-language-server-wrapper`), when I install [packages.haskell-language-server.components.exes](https://github.com/korayal/hls-nix/blob/012aca6057796afadc2e13aacc33ea8023095edd/nix/default.nix#L32), I get priority conflict on `LICENCE` files. But if I install `packages.haskell-language-server.components.exes.haskell-language-server` then change it's priority and then install `packages.haskell-language-server.components.exes.haskell-language-server-wrapper`, it does work. Though I don't think this is the way to fix that.

I've pushed to my cachix cache on [that branch](https://github.com/korayal/hls-nix/tree/multi-version) for both `hls-ghc865` and `hls-ghc883` for Linux.
---
unrelated to these above, but I was wondering about something. Right now this project is using ghcide as a submodule. Would it be possible to install this project without explicitly defining that ghcide dependency within nix files? 

Normally when we install a nix package from GitHub we use the [tarball](https://www.github.com/haskell/haskell-language-server/archive/master.tar.gz) and submodules are not included there.

**Comment by spacekitteh** [comment] 2020-05-27 00:50
> On my [latest take](https://github.com/korayal/hls-nix/tree/012aca6057796afadc2e13aacc33ea8023095edd) I was able to build for **GHC 8.8.3** and **8.6.5**, but not others. [GHC 8.10.1 is not supported by haskell.nix yet](https://github.com/input-output-hk/haskell.nix/pull/541). I haven't digged deeper for **8.8.2** and **8.6.4**.
> 
> On the other hand, since haskell-language-server exposes two executables (`haskell-language-server` and `haskell-language-server-wrapper`), when I install [packages.haskell-language-server.components.exes](https://github.com/korayal/hls-nix/blob/012aca6057796afadc2e13aacc33ea8023095edd/nix/default.nix#L32), I get priority conflict on `LICENCE` files. But if I install `packages.haskell-language-server.components.exes.haskell-language-server` then change it's priority and then install `packages.haskell-language-server.components.exes.haskell-language-server-wrapper`, it does work. Though I don't think this is the way to fix that.
> 
> I've pushed to my cachix cache on [that branch](https://github.com/korayal/hls-nix/tree/multi-version) for both `hls-ghc865` and `hls-ghc883` for Linux.

Hmm. When I try installing `hls-ghc883` using `home-manager`, I get a type error: `The option value `home.packages.[definition 23-entry 36]' in `/home/spacekitteh/.config/nixpkgs/home.nix' is not of type `package'.`

**Comment by spacekitteh** [comment] 2020-05-27 00:59
Ah, your installation instructions were wrong. I'll submit a PR.

**Comment by korayal** [comment] 2020-05-27 07:05
I just noticed there's already [an issue](https://github.com/Infinisil/all-hies/issues/57) on **all-hies** for this. I think the best path forward is to wait for/help @Infinisil on that since he's already working on a [haskell.nix port for all-hies](https://github.com/Infinisil/all-hies/blob/haskell.nix/).

**Comment by Infinisil** [comment] 2020-05-27 22:15
Here's the current issue for using haskell.nix for all-hies: https://github.com/Infinisil/all-hies/issues/19, with this branch having the changes: https://github.com/Infinisil/all-hies/tree/haskell.nix

It's a bit unfortunate that I can only get 8.6.5 and 8.8.3 working with it though :/

**Comment by poscat0x04** [comment] 2020-06-14 04:06
I've just generated some nix derivations using the haskell.nix infra, they seem to be usable but I'm not entirely sure.

[repo](https://github.com/poscat0x04/hls-nix)

**Comment by michaelpj** [comment] 2020-06-15 15:32
I have a slightly different `haskell.nix` expression that I got working recently: https://github.com/input-output-hk/plutus/blob/6021baf728ed812a45a1a87c5deac2ee7d756d9d/nix/haskell-extra.nix#L33

**Comment by poscat0x04** [comment] 2020-06-15 18:58
Did an overhaul to my repository, now it supports all GHC versions on both 0.1 release and master

**Comment by Sir4ur0n** [comment] 2020-06-22 10:22
Thank you @poscat0x04 , I have started again from your derivation and had it work on my project! I had to duplicate your project to change various things to make it work with my project though, so I opened a few issues on your repo to smoothen the derivation consumption, but it otherwise seems to work! I'd be happy to switch back to your derivation if you agree on these changes (and I can try to open PRs to do the changes I proposed).

Again, thank you!

**Comment by spacekitteh** [comment] 2020-07-01 01:26
Anybody have an up-to-date version for the vanilla Haskell infrastructure?

**Comment by Sir4ur0n** [comment] 2020-07-01 19:24
For what it's worth: a first version has been merged into the `nixpkgs` repository 2 days ago, thanks to @GuillaumeDesforges, see https://github.com/NixOS/nixpkgs/pull/91279 for more information.

I don't think it's **yet** available on `nixpkgs-unstable` channel, but it should land soon.

**Comment by spacekitteh** [comment] 2020-07-01 23:34
Oh sweet!

**Comment by spacekitteh** [comment] 2020-07-07 20:46
Hmm, what attribute is it under?

**Comment by Sir4ur0n** [comment] 2020-07-07 22:15
@GuillaumeDesforges are you able to tell us more? I just tested with `nixpkgs-unstable` and I can't find the `haskell-language-server` executable, nor `hls`, neither at top level or inside `haskellPackages`, but I'm not 100% familiar with how Haskell packages are updated/published on `nixpkgs`.

**Comment by leungbk** [comment] 2020-07-07 22:29
It's not yet on the unstable channel, but it is on the master branch of
nixpkgs right now.

**Comment by GuillaumeDesforges** [comment] 2020-07-08 07:08
You can find nixpkgs status here:
https://status.nixos.org/

It says that the last update was yesterday for nixpkgs-unstable, so it should be there after updating the channel (are you on the unstable channel?)

It should be available in ```(import <nixpkgs> {}).haskell.packages.ghc883.haskell-language-server```

**Comment by Sir4ur0n** [comment] 2020-07-08 17:13
Thank you Guillaume, I think I am more lost because of Nix then 🤔 
```shell
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
$ nix-channel --update
unpacking channels...
$ echo $NIX_PATH
/home/sir4ur0n/.nix-defexpr/channels:/home/sir4ur0n/.nix-defexpr/channels
$ ll /home/sir4ur0n/.nix-defexpr/channels/
nixpkgs -> /nix/store/fazhhnw3ywcxxh16zlbb15h381gvxc2f-nixpkgs-20.09pre233103.4855aa62fa1/nixpkgs/
$ nix repl
nix-repl> (import <nixpkgs> {}).lib.version
"20.09pre233103.4855aa62fa1"
nix-repl> (import <nixpkgs> {}).haskell.packages.ghc883.haskell-language-server
error: attribute 'haskell-language-server' missing, at (string):1:1
```

I assume based on the number `233103` that my version is older than yours `233323` (which may explain why I don't yet see the HLS package), however for the life of me I can't figure out what I'm doing wrong 😐 

If anyone would be kind enough to tell me what's wrong, I would appreciate 🙇 I did search on Nix documentation but could not find any other way than `nix-channel --update` to update my `nixpkgs`...

**Comment by spacekitteh** [comment] 2020-07-08 21:31
I found I had to run `nix-channel --update` twice for it to actually work for some reason :woman_shrugging:

**Comment by Sir4ur0n** [comment] 2020-07-08 22:04
> I found I had to run `nix-channel --update` twice for it to actually work for some reason 🤷‍♀️

What. The. F*ck.

I just tested and it also worked O_o

Would anybody be able to explain this dark magic/bug?

**Comment by spacekitteh** [comment] 2020-07-08 23:46
@copumpkin ?

**Comment by Sir4ur0n** [comment] 2020-07-09 09:28
Slightly unrelated question: how come the packages doesn't appear in https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=haskell-language-server ?

**Comment by GuillaumeDesforges** [comment] 2020-07-09 13:32
> Slightly unrelated question: how come the packages doesn't appear in https://nixos.org/nixos/packages.html?channel=nixpkgs-unstable&query=haskell-language-server ?

![image](https://user-images.githubusercontent.com/1882000/87046397-70b2b980-c1f9-11ea-9d35-382405622813.png)

**Comment by Sir4ur0n** [comment] 2020-07-09 14:01
Yes, I am, it's part of the URL...

When I click:
![image](https://user-images.githubusercontent.com/1204125/87048861-8bd2f880-c1fc-11ea-810d-8adde8993e45.png)

Interestingly, when trying in a private-mode browser, it appears:
![image](https://user-images.githubusercontent.com/1204125/87048996-b58c1f80-c1fc-11ea-9c93-6533ec46515c.png)

I guess this is related to caching, however this website is **highly confusing**, as it displays a loading bar (even on my regular web browser) before displaying "No results found", so the user (at least me) expects this is a server response, not some cache:
![image](https://user-images.githubusercontent.com/1204125/87049076-cf2d6700-c1fc-11ea-989e-130807d997bb.png)

Note: it still displays "No results found" when force refreshing (in Chrome: Ctrl + F5, Shift + F5)...

I guess this solves this mystery, though I find it a poor user experience :/

If anyone is affiliated or knows maintainers of this website, this may be worth letting them know :disappointed:

**Comment by Sir4ur0n** [comment] 2020-07-10 12:38
In case anyone is interested, I took a second look at this caching problem.

The problem seems to come from the fact that this page at some points loads https://channels.nixos.org/nixpkgs-unstable/packages.json.br which is a HTTP 301 (redirect to the latest nixpkgs).

On my regular browser, it hits a disk cache and thus always targets https://releases.nixos.org/nixpkgs/nixpkgs-20.09pre232864.55668eb671b/packages.json.br (even if using Ctrl + F5)

![image](https://user-images.githubusercontent.com/1204125/87154912-52f95900-c2ba-11ea-9727-df5916cfef64.png)

Note the version is stuck at `232864`.

When doing the same thing in an incognito browser, it redirects to https://releases.nixos.org/nixpkgs/nixpkgs-20.09pre233849.1d801806827/packages.json.br (note the version is `233849`).

The former does not contain `haskell-language-server`, the latter does.

I guess the page should not cache this 301 redirect :man_shrugging:

**Comment by mulderr** [comment] 2020-07-25 13:51
Short experience report. Moved project to `nixos-unstable-small` rev `9ab83c6eed9d1c6840940f5918713383346706a3` and GHC 8.8.4. Had to add `haskell.packages.ghc884.haskell-language-server` to my `shell.nix`. This gives:
```
haskell-language-server version: 0.2.2.0 (GHC: 8.8.4) (...)
```

And... it's alive! VS code plugin picked it up automatically.

@GuillaumeDesforges nice work! :+1:

**Comment by rybern** [comment] 2020-07-30 04:21
Thank you @GuillaumeDesforges!!

It's worth noting that the version pointed to by nixpkgs doesn't have PR #243, which fixed an issue with lsp-haskell in emacs (see [here](https://github.com/emacs-lsp/lsp-haskell/issues/73)). In case anyone else runs into that: I got around it by modifying the HLS nixpkgs derivation to point at master, which wouldn't compile because nixpkgs doesn't have lsp-test 0.11.0.3 yet, so I forked HLS to remove that dependency ([that fork here](https://github.com/rybern/haskell-language-server/tree/downgrade-lsp-test)), and turned off the check phase.

**Comment by soulomoon** [comment] 2020-08-01 21:33
Since currently cachix cache does not have enough pre build versions. I create a simple [script](https://github.com/soulomoon/all-hls) to ease the installation of all pre-builds binaries from github release.

**Comment by Sir4ur0n** [comment] 2020-08-17 16:40
Besides documenting the availability in Nixpkgs (with a minimal `shell.nix` example?), is there anything else to be done in this issue? If not, I can try to open a PR and then we finally close this issue?

**Comment by tscholak** [comment] 2020-08-17 17:36
Hi, I was able to get it to work with `haskell.nix`, see here: https://github.com/hasktorch/hasktorch-skeleton/blob/master/nix/default.nix#L35-L54 and here: https://github.com/hasktorch/hasktorch-skeleton/blob/master/shell.nix#L24

**Comment by peterstorm** [comment] 2020-08-21 08:17
Can someone help me install the 864 version with nix, using fetchUrl? I tried this, but I can't make it work.

`{ pkgs ? import ../nixpkgs.nix }:
pkgs.stdenv.mkDerivation rec {
  name = "haskell-language-server";

  src = pkgs.fetchurl {
    url = "https://github.com/haskell/haskell-language-server/releases/download/0.3.0/haskell-language-server-Linux-8.6.4.gz";
    sha256 = "1q3vq2gdb3zsmxab1fmq4s7f7p4r3kdzn709aqf83hhfx18sn1rj";

  };
  phases = ["installPhase"];





  installPhase = ''
    mkdir -p $out/bin
    ${pkgs.gzip}/bin/gzip -d $src  $out/bin
    chmod +x $out/bin/haskell-language-server-Linux-8.6.4

  '';
}`

**Comment by GuillaumeDesforges** [comment] 2020-08-21 08:29
@peterstorm I'd advice using the `haskell-language-server` from nixpkgs:

for instance if you want a `shell.nix` file for `nix-env`:
```nix
{ pkgs ? import <nixpkgs> }:
pkgs.mkShell {
  buildInputs = with pkgs; [ cabal-install stack haskell.packages.ghc864.haskell-language-server ];
}
```

your `<nixpkgs>` should be unstable (see https://nixos.wiki/wiki/Nix_channels)

**Comment by peterstorm** [comment] 2020-08-21 08:31
Oh, I didn't know that version was added, I'll check that out, thank you @GuillaumeDesforges!

**Comment by peterstorm** [comment] 2020-08-21 08:39
@GuillaumeDesforges 
Hmm, it says that the `gh864` attribute is missing, and I'm importing sources from unstable :(

**Comment by GuillaumeDesforges** [comment] 2020-08-21 08:41
Oops, ghc864 not gh864

**Comment by GuillaumeDesforges** [comment] 2020-08-21 08:42
Well, seems like ghc864 has been dropped in favor of ghc865. Can you upgrade?

**Comment by peterstorm** [comment] 2020-08-21 08:43
@GuillaumeDesforges Not really, I'm on that specific version because of a GHCJS project :( I'll try to figure out how to get the binary

**Comment by galagora** [comment] 2020-09-15 12:30
This issue is fixed and can be closed. The latest version is in Nixpkgs; it can be installed just like any other Haskell package.

**Comment by galagora** [comment] 2020-09-15 12:37
@peterstorm If you still have this issue, try

```nix
# { stdenv
# , autoPatchelfHook
# }:
with import (import ./nix/sources.nix).nixpkgs {};
stdenv.mkDerivation {
  name = "haskell-language-server";
  src = /home/$USER/downloads/haskell-language-server-Linux-8.6.4.gz;

  nativeBuildInputs = [
    autoPatchelfHook
  ];

  buildInputs = [
    git
    gmp
    ncurses
    zlib

    haskellPackages.cabal-install
    haskellPackages.hlint
  ];

  phases = ["installPhase"];

  installPhase = ''
    mkdir -p $out/bin
    gzip -d < $src > $out/bin/haskell-language-server-Linux-8.10.1
    chmod +x $out/bin/haskell-language-server-Linux-8.10.1
  '';
}
```

**Comment by shajra** [comment] 2020-09-16 03:34
I've got Nix expressions building with GitHub Actions and cached to shajra.cachix.org for 8.6.5, 8.8.4, and 8.10.2: https://github.com/shajra/nix-hls/actions/runs/252124388.

the README is not fleshed out, but my goal is to make clear instructions to get people started and point them in the right direction.

This is a Haskell.nix build, because I think trying to do it the Nixpkgs way is just a bit more tedious than it's worth.  But if more versions get compiled for Nixpkgs, then I guess the value of this project attenuates and binaries will be cached in Hydra (which is generally better).

**Comment by peterstorm** [comment] 2020-09-18 11:32
> 
> 
> @peterstorm If you still have this issue, try
> 
> ```nix
> # { stdenv
> # , autoPatchelfHook
> # }:
> with import (import ./nix/sources.nix).nixpkgs {};
> stdenv.mkDerivation {
>   name = "haskell-language-server";
>   src = fetchurl {
>     url = "https://github.com/haskell/haskell-language-server/releases/download/0.4.0/haskell-language-server-Linux-8.6.4.gz";
>     sha256 = "0fhzm9190mgya08mcjz9zrd34p1s3k1a1l9dzxpxm7ij9b43n333";
>   };
>   nativeBuildInputs = [
>     autoPatchelfHook
>   ];
> 
>   buildInputs = [
>     git
>     gmp
>     ncurses
>     zlib
> 
>     haskellPackages.cabal-install
>     haskellPackages.hlint
>   ];
> 
>   phases = ["installPhase"];
> 
>   installPhase = ''
>     mkdir -p $out/bin
>     gzip -d < $src > $out/bin/haskell-language-server-Linux-8.6.4
>     chmod +x $out/bin/haskell-language-server-Linux-8.6.4
>   '';
> }
> ```

I ended up doing this stupid thing, which works, but is convoluted - your's is way more succint, so I'll try that! :D

**Comment by masaeedu** [comment] 2020-09-20 17:53
I feel bad for just making another thing instead of using one of the nice projects mentioned above, but I just wanted an easy way to consume the Github releases of this project (instead of using something built from source somewhere else).

I wrote a script yesterday that extracts all the version platform combinations of the HLS wrapper and the GHC-specific HLS binaries into a structured blob of JSON. Then I added a Nix expression that takes a desired platform (i.e. macOS or Linux), version and GHC and just gunzips the correct wrapper and GHC-specific binary from the Github releases into a derivation.

In your shell.nix, you can have:

```
with import <nixpkgs> {};

let
  all-hls = fetchFromGitHub { owner = "masaeedu"; repo = "all-hls"; rev = "155e57d7ca9f79ce293360f98895e9bd68d12355"; sha256 = "04s3mrxjdr7gmd901l1z23qglqmn8i39v7sdf2fv4zbv6hz24ydb"; };
  hls = import all-hls { version = "0.4.0"; ghc = "8.6.5"; };
in
mkShell {
  buildInputs = [ hls ];
}
```

And then run:

```
➜  aijdoadasoidsa nix-shell

[nix-shell:/tmp/aijdoadasoidsa]$ haskell-language-server
haskell-language-server version: 0.4.0.0 (GHC: 8.6.5) (PATH: /nix/store/dhnghmpz1c9gz8rjpyj2vikxr93f569g-haskell-language-server-0.4.0-for-8.6.5-on-Linux/bin/haskell-language-server) (GIT hash: 0a18edde24923251a148cbbc0ae993a6aac83b9c)
(haskell-language-server)Ghcide setup tester in /tmp/aijdoadasoidsa.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Tool versions found on the $PATH
cabal:          Not found
stack:          2.3.3
ghc:            Not found


Step 1/4: Finding files to test in /tmp/aijdoadasoidsa
haskell-language-server: user error (Couldn't find any .hs/.lhs files inside directory: .)
```

**Comment by shajra** [comment] 2020-09-21 01:04
Okay, it's good that people figured out how to wrap the published HLS builds.  Hopefully that can also get cached into Cachix too.  In the meantime, I think my `nix-hls` project still might have some reason to exist (maybe not much), because by building from scratch, I can build the unreleased versions too if there's some motivation to do that (like a work-around to a bug).

I didn't get around to writing docs for it this weekend, but when I do I have a personal note to reference the other projects mentioned in this thread so people know what their options are.

**Comment by korayal** [comment] 2020-10-09 08:51
Is there a way to have a `haskell-language-server-wrapper` executable [that can work out what version of GHC the project uses](https://github.com/haskell/haskell-language-server#editor-integration), and runs it's respective `haskell-language-server` executable on Nix?

**Comment by GuillaumeDesforges** [comment] 2020-10-10 14:27
> Is there a way to have a `haskell-language-server-wrapper` executable [that can work out what version of GHC the project uses](https://github.com/haskell/haskell-language-server#editor-integration), and runs it's respective `haskell-language-server` executable on Nix?

I was just on my way to signal that https://github.com/NixOS/nixpkgs/pull/99519 has been merged, so wrapped hls will soon land on nixpkgs unstable.

**Comment by jneira** [comment] 2020-10-10 19:37
When the nix installation will be stable enough it would be great to add a section about in README (and close the issue). 
pr's welcome! 😄

**Comment by Anton-Latukha** [comment] 2020-10-10 21:34
So far as I see and hear from yesterday's `peti` Livestream talks that 0.5.0 works great in Nixpkgs and in NixOS.
In VSCode on NixOS it works, due to "Nix Environment Selector" extension.
For Emacs the case is that `lsp-haskell` needed a fix: https://github.com/emacs-lsp/lsp-haskell/issues/85, fix is: https://github.com/emacs-lsp/lsp-haskell/pull/87, then `haskell-server-wrapper-function` would work.

===

Curently I am thinking is it is right that all IDEs currently required to provide their custom Nix env support and wrap the `haskell-language-server-wrapper`, because there is no support of Nix env in HLS wrapper.

IDK.

**Comment by Anton-Latukha** [comment] 2020-10-10 23:38
I started spitballing some PR :arrow_up:.
HLS and `ghcid` have problems loading HLS on NixOS, so currently, code is in pure draft mode, until something (me on Ubuntu, or they load HLS in NixOS) works.

You are free to start your own PR, or add your hacking into the current PR.

**Comment by maralorn** [comment] 2020-10-11 13:37
There is an attribute `pkgs.haskell-language-server` in nixpkgs unstable (as soon as unstable has passed the tests, see: https://status.nixos.org/), that should "just work".

I also added a section to the nixpkgs manual on how to install and run hls. If I don‘t forget it I can post a link here once the channel bump happened.

**Comment by maralorn** [comment] 2020-10-11 13:39
@Anton-Latukha Sorry, but I don‘t understand the problem you are seeing. Can you give an example situation where the current setup fails and have you confirmed that it fails in that case?

**Comment by Anton-Latukha** [comment] 2020-10-11 17:29
Ok, sorry, people in the thread.

You can be mixed-up reading above messages.

This is my efforts of solving the parallel separate issue in the Emacs `lsp-haskell` package inside Haskell4Nix Discord mixed-up and leaked here.

And for HLS wrapper to have an option for the loading of the Nix env - that is probably not "Nix installation?" topic, so I would open a proper topic for it and move my stuff there.

Sorry for inconvinience.

**Comment by sgraf812** [comment] 2020-10-31 18:59
Apparently, the commit landed and the tests were green at least once in the last few weeks. There's https://haskell4nix.readthedocs.io/nixpkgs-users-guide.html#how-to-install-haskell-language-server that describes how to install HLS. As far as I can tell, it works! Thank you :)

**Comment by maralorn** [comment] 2020-11-01 00:42
Oh, yeah. I forgot about this thread.^^ Thanks, for the link @sgraf812 .

I have gotten positive feedback about it, but I would be glad to hear about any troubles. This concerns the actual package as well as the documentation.

**Comment by domenkozar** [comment] 2020-11-24 12:44
FYI: I've seen ghcide/HLS segfault on Nix when using TH https://github.com/haskell/ghcide/issues/910

**Comment by tscholak** [comment] 2020-11-24 12:52
Maybe a bit OT, but for those of you using IOHK's haskell.nix, I can recommend adding hls as a "tool" to the shell derivation like so: https://github.com/hasktorch/hasktorch/blob/0ba5db83111c7fa4e5a6c32d83cbadbca36120c9/nix/default.nix#L39. Works very well 😀

**Comment by maralorn** [comment] 2020-11-24 21:29
I am using hls on nix with TH and I haven‘t witnessed any segfaults yet (although I had two other TH issues which were fixed in the meantime).

I thought I had heard other reports about TH segfaults. Would be interesting to know if those also only happened on nix.

**Comment by domenkozar** [comment] 2020-11-25 09:09
I have a feeling that it's glibc difference between my system and what ghcide/HLS was compiled with, given that `dlopen` is part of stack trace.

In this particular case, if I compile HLS via stack+nix (which takes my local system NIX_PATH) it works.

**Comment by maralorn** [comment] 2020-11-25 09:30
@domenkozar So you think you get the crashes because you use hls from unstable on a stable-nixos system or something similar?

**Comment by domenkozar** [comment] 2020-11-25 09:46
That's my assumption, but I didn't confirm it. I don't think there's a way to tell haskell packages in nixpkgs to build everything with debug symbols, that would at least help pin down full trace.

**Comment by domenkozar** [comment] 2021-01-06 16:03
Should we close this with README update how to install HLS with Nix by pointing to https://haskell4nix.readthedocs.io/nixpkgs-users-guide.html?highlight=language%20server#how-to-install-haskell-language-server ?

**Comment by shajra** [comment] 2021-01-06 16:16
A while ago, I committed to maintaining some Haskell.nix-based builds of HLS.  I also put in a good amount of documentation on using HLS with Nix.  I like where it ended up.  However, if this documentation is useful, I wonder if it's too much on-the-side and hidden away.

I'd appreciate people's review and suggestions: https://github.com/shajra/nix-haskell-hls

**Comment by spacekitteh** [comment] 2021-01-06 21:28
@domenkozar I'm more than happy to close it, but I obviously can't update the README, so someone should do that and close it in the commit.

**Comment by jneira** [comment] 2021-01-07 12:14
> @domenkozar I'm more than happy to close it, but I obviously can't update the README, so someone should do that and close it in the commit.

a pr will be very very welcomed

**Comment by jkachmar** [comment] 2021-03-06 20:38
I threw together a small project in the vein of Justin Woo's `easy-dhall-nix` and `easy-purescript-nix`, which reuses the binaries produced by [this repository's release page]() to produce installations that are compatible with Nix.

https://github.com/jkachmar/easy-hls-nix

---

I've tested this (manually) on both macOS and NixOS installations, and if there's interest I can polish it up a bit more with some sort of CI setup that can check the results and perhaps automate things whenever this project pushes a new release.

**Comment by masaeedu** [comment] 2021-03-06 20:55
@jkachmar I posted this earlier in the thread, so you might already have looked at it, but you might find https://github.com/masaeedu/all-hls interesting.

**Comment by maralorn** [comment] 2021-03-06 23:04
@jkachmar Have you tried that with a little more complex projects? i.e. with TH?
I looked at your project and the amount of magic your doing is so small that I would be surprised if that worked for all cases.

**Comment by maralorn** [comment] 2021-03-10 18:44
@jkachmar Well, I don‘t remember exactly. There were numerous TH issues.

What I am thinking about are I think linking issues. From my experience not using the same ghc to compile hls and your project will lead to issues in nixpkgs. That e.g. happens when dependencies build with cabal are linked against different glibc versions than hls. Sometimes stuff like that surfaces when using TH but maybe I just misremember that.

But if @masaeedu has also using this approach then maybe this is just fine?

I am really surprised by this. I was under the impression that the static binaries wouldn‘t be compatible … Doesn‘t this mean that the vscode plugin which just dynamically downloads hls binaries for you should work just fine under nixos?

**Comment by maralorn** [comment] 2021-03-10 19:29
@jkachmar I went back and tested three things on my project:
a) Using the vscode plugin on my codebase without any hls installed.
b) Using your package to install hls.
c) Use the hls from nixpkgs.

In the cases a) and b) I get
```
Message:  Unexpected usage errorld-linux-x86-64.so.2: cannot open shared object file
```
(accidentally all the files I get this error in use TH.)
It’s not exactly the error I had expected, but it’s a linking problem, so I am not surprised.

With c) it works.

So as cool and simple as your approach it, I fear it’s not a general solution.

**Comment by jkachmar** [comment] 2021-03-15 01:19
@maralorn I've opened a Draft PR with a workaround for NixOS that I _believe_ should fix this issue.

I added a small test to check that basic Template Haskell invocations work (e.g. `aeson`), but I'm not sure if there's some edge case that I haven't accounted for.

**Comment by jneira** [comment] 2021-06-21 05:44
Hey, i think we could transform the wisdom put in this issue in some document, f.e. a guide to:
* install/setup a dev env over hls using nix
* how to use hls in nix environments

It seems there are several methods to do it.
someone has the opportunity to write somthing alike (or part of it)?

**Comment by maralorn** [comment] 2021-06-21 20:32
@jneira For us nixpkgs Haskell maintainers, documentation is the next thing on our todo list. Setting up a dev environment will be central in that and using hls will again be central in that.

**Comment by domenkozar** [comment] 2021-09-17 14:04
Note that I can't upgrade to 1.4.0.0 because it requires a nixpkgs-unstable to get GHC 8.10.7 while my system runs stable 21.05.

As my project uses TH, as soon as HLS typechecks my project then segfaults while calling `dlopen`. It seems that glibc mismatch between how HLS is compiled and system makes it segfault, but that's just a wild guess.

**Comment by jkachmar** [comment] 2021-09-17 16:03
@domenkozar If you’re using the statically linked version then yeah this is a known consequence of statically linking against `glibc`.

As I understand it, there’s no guarantee of stability for the interpreter between any version of `glibc`, so the statically linked HLS binaries rely on the fact that most users will likely be invoking it on a distribution that has a compatible version of `glibc`.

---

Possibly veering off topic a bit, but I really don’t think HLS should be packaged this way.

If we want a statically linked executable then we should use `musl`, otherwise we should at most only be partially statically linking the executable (i.e. not statically linking `glibc`).

**Comment by pepeiborra** [comment] 2021-09-17 17:27
> 
> Possibly veering off topic a bit, but I really don’t think HLS should be packaged this way.
> 
> 
> 
> If we want a statically linked executable then we should use `musl`, otherwise we should at most only be partially statically linking the executable (i.e. not statically linking `glibc`).

I would fully support a PR that did this

**Comment by domenkozar** [comment] 2021-09-20 08:39
> @domenkozar If you’re using the statically linked version then yeah this is a known consequence of statically linking against `glibc`.
> 
> As I understand it, there’s no guarantee of stability for the interpreter between any version of `glibc`, so the statically linked HLS binaries rely on the fact that most users will likely be invoking it on a distribution that has a compatible version of `glibc`.
> 
> Possibly veering off topic a bit, but I really don’t think HLS should be packaged this way.
> 
> If we want a statically linked executable then we should use `musl`, otherwise we should at most only be partially statically linking the executable (i.e. not statically linking `glibc`).

It's compiled using `stack build --stack-yaml=stack-8.10.7.yaml`, using one from nixpkgs also doesn't work.

Don't think the problem is in static linking of HLS but rather TH and glibc mismatch

**Comment by jneira** [comment] 2021-10-04 08:12
This issue is deeply buried in the issue tracker and i think there are lot of valuable info here that worths to be included in the installation guide https://haskell-language-server.readthedocs.io/en/latest/installation.html
Someone volunteer? @michaelpj :wink: ?

**Comment by maralorn** [comment] 2021-10-04 16:34
I had written everything, that I thought was necessary about this in https://haskell4nix.readthedocs.io/nixpkgs-users-guide.html#how-to-install-haskell-language-server, which will hopefully soon move into the nixpkgs manual.

I suggest that both documentations reference each other. I don‘t care very much, where the meat of the content resides.

**Comment by jneira** [comment] 2021-10-04 18:01
wow, wonderful, thanks for the info, will link it in our docs

**Closed** 2021-10-10 00:55 UTC
Labels: type: documentation, type: enhancement, build, os: nixos, pr welcome

**Comment by michaelpj** [comment] 2023-09-12 13:54
To add a late addition: HLS is pretty easily buildable with `haskell.nix`, by pointing it at the HLS repository and using `cabalProject`.

**Comment by maralorn** [comment] 2023-09-12 14:10
Cool! For anyone stumbling by I want to point out: Get your hls from where you get your ghc. If you install ghc from haskell.nix then do as Michael says. If you install ghc from nixpkgs follow the nixpkgs manual at: https://nixos.org/manual/nixpkgs/unstable/#haskell-language-server
