### ISSUE TITLE
HLS failed to start after upgrade to 1.8.0.0

### ISSUE THREAD

**Issue by goosedb** [haskell/haskell-language-server#3166] opened 2022-09-15 07:44 UTC
### Your environment

Ubuntu
8.10.7
vscode-haskell
1.8.0.0

### Steps to reproduce
upgrade to 1.8.0.0

### Debug information
```
2022-09-15 07:40:02.7090000 [client] INFO Executing 'haskell-language-server-wrapper --project-ghc-version' in cwd '/home/goosedb/Documents/Haskell/placid'
2022-09-15 07:40:02.7540000 [client] ERROR Error executing 'haskell-language-server-wrapper --project-ghc-version' with error code 1
2022-09-15 07:40:02.7540000 [client] ERROR stderr: haskell-language-server-wrapper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by haskell-language-server-wrapper)

2022-09-15 07:40:02.7550000 [client] ERROR Error: haskell-language-server --project-ghc-version exited with exit code 1:

haskell-language-server-wrapper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by haskell-language-server-wrapper)
```

**Comment by pepeiborra** [comment] 2022-09-15 08:12
Duplicate of #3160

**Closed** 2022-09-15 08:13 UTC
Labels: type: bug, status: needs triage
