### ISSUE TITLE
Automatically adding an import for current module

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#3719] opened 2023-07-16 08:44 UTC
Using HLS at fb5e5c998c7d4f13546ae015191a7983aedf3345

### Steps to reproduce

Open a file with a class definition in it.

Edit a function to be a synonym for a class method

### Expected behaviour

Nothing but my edit

### Actual behaviour

An import line gets added for the current module, causing a loop.

![image](https://github.com/haskell/haskell-language-server/assets/409607/3c43d67b-cb23-46d6-98cf-18fa535013fc)

**Comment by michaelpj** [comment] 2023-08-09 11:12
I believe this is a duplicate of https://github.com/haskell/haskell-language-server/issues/2270 (item 3)

**Closed by michaelpj** 2023-08-09 11:12 UTC
Labels: type: bug, status: needs triage
