### ISSUE TITLE
Quick Fix (VSCode) No Longer Showing Fix Options

### ISSUE THREAD

**Issue by theGhostJW** [haskell/haskell-language-server#4012] opened 2024-01-23 19:53 UTC
### Your environment

**Which OS do you use?**
Ubuntu (Windows WSL)

**Which version of GHC do you use and how did you install it?**
cabal:          3.10.2.1
ghc:            9.8.1

**Which LSP client (editor/plugin) do you use?**
vscode-haskell

**Which version of HLS do you use and how did you install it?**
2.6.0.0 via ghcUp

**Have you configured HLS in any way (especially: a `hie.yaml` file)?**
No

### Summary

Previously, when there is a hint or error, quick fix options have been provided in VSCode (e.g. to use a correct variable name or update imports), and these could be applied automatically by selecting one of those options. 

Now the only options provided are either to turn off the error via a pragma or copilot related fixes. I have tried disabling copilot and confirmed this does not fix the issue. Also, the suggested code action is provided in the hint.

I have double checked my HLS options selected in VS code and all the related code action / plugin options are checked.

### Steps to reproduce

1. slightly change a variable name to be incorrect
2. hover over the error
3. => note the suggested fix:

    ![image](https://github.com/haskell/haskell-language-server/assets/3053204/0eca1634-f5aa-4035-8aee-530594f28580)
    
4.  invoke Quick Fix
5. => no related fix option is given

  ![image](https://github.com/haskell/haskell-language-server/assets/3053204/f7d09b7e-433a-4b7c-bdce-6c341e079036)

### Expected behaviour

Fix option should be provided

**Comment by michaelpj** [comment] 2024-01-24 10:02
HLS relies on GHC's diagnostics to power code actions, if you change the diagnostics that GHC emits we may not function the same. In particular, it looks like you have `-fdeferred-out-of-scope-variables` set, which is going to change the errors that GHC emits. Maybe we don't handle those correctly. Do the code actions come back if you stop setting that flag?

**Comment by wz1000** [comment] 2024-01-24 10:31
we set `-fdeferred-out-of-scope-variables` in HLS.

I think this is just hls-refactor-plugin not being available for GHC 9.8 in 2.6.0.0

**Comment by michaelpj** [comment] 2024-01-24 10:38
Okay, I'm going to close this as expected behaviour then.

**Closed by michaelpj** 2024-01-24 10:38 UTC
Labels: type: bug, status: needs triage

**Comment by theGhostJW** [comment] 2024-01-24 10:45
OK thanks. Hope to see it become available a future release.

**Comment by Bodigrim** [comment] 2024-01-28 15:49
@michaelpj @wz1000 is there an issue tracking `hls-refactor-plugin` with GHC 9.8? It seems to build fine, no?

**Comment by wz1000** [comment] 2024-01-28 15:55
It will be included in the next release.
