### ISSUE TITLE
showTypeForSelection working?

### ISSUE THREAD

**Issue by jamesdbrock** [haskell/haskell-language-server#1973] opened 2021-06-24 08:42 UTC
This “show type of selected expression on hover” feature haskell/vscode-haskell#40 is great. Is this currently working? 

I can’t find any mention of this feature in the [README.md](https://github.com/haskell/vscode-haskell/blob/master/README.md).

I tried this in my `settings.json` and nothing happens.

```
  "languageServerHaskell.showTypeForSelection.onHover": "true",
  "languageServerHaskell.showTypeForSelection.command.location": "dropdown",
```

I don't see any mention of this in the logs, for example `~/.config/Code/logs/20210624T170820/exthost1/output_logging_20210624T170826/5-Haskell\ \(IHaskell2\).log`

VSCode v1.57.1
haskell.haskell extension v1.4.0

**Comment by jneira** [comment] 2021-06-24 09:43
If you dont mind i am gonna close it as duplicate of the mentioned issue: #709, you could track the progress an eventual implementation there.

**Closed by jneira** 2021-06-24 09:43 UTC
Labels: type: enhancement
