### ISSUE TITLE
Doesn't show compile error with PolyKinds and DataKinds enabled

### ISSUE THREAD

**Issue by eddiemundo** [haskell/haskell-language-server#1263] opened 2021-01-26 17:46 UTC
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /nix/store/ry6c4xcqk7789q1n2hcgqzlq1pk4slj2-haskell-language-server-0.8.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		Not found
ghc:		8.10.3
```
Which lsp-client do you use:
Neovim
Describe your project (alternative: link to the project):

Contents of `hie.yaml`:
```yaml
```

### Steps to reproduce
```haskell
{-# LANGUAGE PolyKinds, DataKinds #-}

module Sandbox where

asdf :: (Int :: (Int :: Int))
asdf = undefined
```

### Expected behaviour
Should display compile error
```sh
Sandbox.hs:36:18: error:
    • Expected kind ‘Int’, but ‘Int’ has kind ‘*’
    • In the kind ‘(Int :: Int)’
      In the type signature: asdf :: (Int :: (Int :: Int))
   |
36 | asdf :: (Int :: (Int :: Int))
   |                  ^^^
```

### Actual behaviour
Doesn't show any error. Running `cabal new-build` does show an error though.

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /nix/store/ry6c4xcqk7789q1n2hcgqzlq1pk4slj2-haskell-language-server-0.8.0.0/bin/haskell-language-server)
(haskell-language-server)Ghcide setup tester in /home/jon/projects/haskell/type-tracer.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		Not found
ghc:		8.10.3


Step 1/4: Finding files to test in /home/jon/projects/haskell/type-tracer
Found 3 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "Setup.hs"
NotShowMessage (NotificationMessage {_jsonrpc = "2.0", _method = WindowShowMessage, _params = ShowMessageParams {_xtype = MtInfo, _message = "No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for Setup.hs.\n Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).\nYou should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error."}})
Output from setting up the cradle Cradle {cradleRootDir = "/home/jon/projects/haskell/type-tracer", cradleOptsProg = CradleAction: Cabal}
File:     /home/jon/projects/haskell/type-tracer/Setup.hs
Hidden:   no
Range:    1:1-2:1
Source:   cradle
Severity: DsError
Message: 
  Multi Cradle: No prefixes matched
  pwd: /home/jon/projects/haskell/type-tracer
  filepath: /home/jon/projects/haskell/type-tracer/Setup.hs
  prefixes:
  ("././Main.hs",Cabal {component = Just "type-tracer:exe:type-tracer"})
  ("././Sandbox.hs",Cabal {component = Just "type-tracer:exe:type-tracer"})
[INFO] Consulting the cradle for "Sandbox.hs"
NotShowMessage (NotificationMessage {_jsonrpc = "2.0", _method = WindowShowMessage, _params = ShowMessageParams {_xtype = MtInfo, _message = "No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for Sandbox.hs.\n Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).\nYou should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error."}})
Output from setting up the cradle Cradle {cradleRootDir = "/home/jon/projects/haskell/type-tracer", cradleOptsProg = CradleAction: Cabal}
> Resolving dependencies...
> Build profile: -w ghc-8.10.3 -O1
> In order, the following will be built (use -v for more details):
>  - type-tracer-0.1.0.0 (exe:type-tracer) (configuration changed)
> Configuring executable 'type-tracer' for type-tracer-0.1.0.0..
> Warning: The 'license-file' field refers to the file 'LICENSE' which does not
> exist.
> Preprocessing executable 'type-tracer' for type-tracer-0.1.0.0..
[INFO] Using interface files cache dir: ghcide
[INFO] Making new HscEnv[main]
[INFO] Consulting the cradle for "Setup.hs"
NotShowMessage (NotificationMessage {_jsonrpc = "2.0", _method = WindowShowMessage, _params = ShowMessageParams {_xtype = MtInfo, _message = "No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for Setup.hs.\n Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).\nYou should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error."}})
Output from setting up the cradle Cradle {cradleRootDir = "/home/jon/projects/haskell/type-tracer", cradleOptsProg = CradleAction: Cabal}
Files that failed:
[INFO] finish: User TypeCheck (took 0.87s)
 * /home/jon/projects/haskell/type-tracer/Sandbox.hs
 * /home/jon/projects/haskell/type-tracer/Setup.hs

Completed (1 file worked, 2 files failed)
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
## versions

vim version: NVIM v0.4.4
node version: v14.15.1
coc.nvim version: 0.0.79
coc.nvim directory: /home/jon/.local/share/nvim/plugged/coc.nvim
term: xterm-kitty
platform: linux

## Output channel: prettier


## Output channel: snippets

[Info 12:40:43 PM] Using ultisnips directories: UltiSnips /home/jon/nix/neovim/snippets
[Info 12:40:43 PM] Using ultisnips python command: pyx

## Output channel: languageserver.haskell

Module "/home/jon/projects/haskell/type-tracer/a" is loaded by Cradle:
 Cradle {cradleRootDir = "/home/jon/projects/haskell/type-tracer", cra
dleOptsProg = 
CradleAction: Cabal}
Run 
entered for haskell-language-serv
er-wrapper(haskell-language-server-w
rapper) Version 0.8.0.0 x
86_64 ghc-8.10.3
Current directory
: /home/jon/projects/haskell/type-trac
er
Operating system: linux
Argume
nts: ["--lsp"]
Cradle directory: /hom
e/jon/projects/haskell/type-tracer
Cr
adle type: Cabal

Tool versions
 found on the $PATH
cabal:		3.2.0.0
stack:
		Not found
ghc:		8.10.3



Consulting the cradle to get 
project GHC version...
Project GHC 
version: 8.10.3
haskell-language-server exe candidates: ["haskell-langu
age-server-8.10.3","haskell-languag
e-server-8.10","haskell-language
-server"]
Launching has
kell-language-server exe at:/nix/store/ry6c4xcqk7789q1
n2hcgqzlq1pk4slj2-haskell-language-se
rver-0.8.0.0/bin/haskell-languag
e-server-8.10.3
haskell-l
an
guage-server version
: 0.8.0.0 (GHC: 8.10.3)
 (PATH: /nix/store/ry6c4xcqk
7789q1n2hcgqzlq1pk4slj2-haskel
l-language-server-0.8.0.0/
bin/haskell-language-server)
Starting (haskell
-language-server)LSP server...

  with arguments: LspArguments {a
rgLSP = True, argsCwd = Not
hing, argFiles = [], ar
gsShakeProfiling = Nothing, argsTe
sting = False, argsExamplePlugin 
= False, argsDebugOn = False, 
argsLogFile = Nothing, arg
sThreads = 0, argsProjectGhcVe
rsion = False}
  with plugin
s: 
[PluginId "brittany",Plugin
Id "class",PluginId "eval",
PluginId "floskell",PluginId 
"fourmolu",PluginId "ghcide"
,PluginId "hlint",PluginId 
"importLens",PluginId "moduleN
ame",PluginId "ormolu",Plug
inId "pragmas",PluginId "
retrie",PluginId "stylish-has
kell",PluginId "tactic"]
  i
n directory: /home/jon/projec
ts/haskell/type-tracer
If you 
are seeing this in a termin
al, you probably should have r
un ghcide WITHOUT the --lsp o
ption!
 
Started LSP s
erver in 0.00s
2021-01-26 12:40:47.100296286 [ThreadId 21] - Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-4510339122776953459) "file:///home/jon/projects/haskell/type-tracer"], clientSettings = hashed (Just (Object (fromList [("haskell",Object (fromList []))])))}
2021-01-26 12:40:47.108678901 [ThreadId 21] - Opened text document: file:///home/jon/projects/haskell/type-tracer/Sandbox.hs
2021-01-26 12:40:47.109602687 [ThreadId 71] - hlint:getIdeas:file:NormalizedFilePath "/home/jon/projects/haskell/type-tracer/Sandbox.hs"
2021-01-26 12:40:47.112925487 [ThreadId 77] - Consulting the cradle for "Sandbox.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/home/jon/projects/haskell/type-tracer", cradleOptsProg = CradleAction: Cabal}
> Resolving dependencies...
> Build profile: -w ghc-8.10.3 -O1
> In order, the following will be built (use -v for more details):
>  - type-tracer-0.1.0.0 (exe:type-tracer) (configuration changed)
> Configuring executable 'type-tracer' for type-tracer-0.1.0.0..
2021-01-26 12:40:49.114861893 [ThreadId 89] - Plugin.makeCodeLens (ideLogger)
> Warning: The 'license-file' field refers to the file 'LICENSE' which does not
> exist.
> Preprocessing executable 'type-tracer' for type-tracer-0.1.0.0..
2021-01-26 12:40:52.087302712 [ThreadId 77] - Using interface files cache dir: ghcide
2021-01-26 12:40:52.087397655 [ThreadId 77] - Making new HscEnv[main]
2021-01-26 12:40:52.096938641 [ThreadId 142] - hlint:getIdeas:file:NormalizedFilePath "/home/jon/projects/haskell/type-tracer/Sandbox.hs"
2021-01-26 12:40:52.097850206 [ThreadId 174] - finish: getSession (took 0.00s)
2021-01-26 12:40:52.127551797 [ThreadId 528] - finish: codeLens (took 0.03s)
2021-01-26 12:40:52.127961895 [ThreadId 544] - finish:  (took 0.00s)
2021-01-26 12:40:52.128223923 [ThreadId 546] - finish: ModuleName.ghcSession (took 0.00s)
2021-01-26 12:40:52.12874936 [ThreadId 557] - finish: ModuleName.GetParsedModule (took 0.00s)
2021-01-26 12:40:52.586015483 [ThreadId 1492] - DocumentHighlight request at position 35:1 in file: /home/jon/projects/haskell/type-tracer/Sandbox.hs
2021-01-26 12:40:54.331492864 [ThreadId 1505] - DocumentHighlight request at position 35:2 in file: /home/jon/projects/haskell/type-tracer/Sandbox.hs
2021-01-26 12:40:55.882526343 [ThreadId 1511] - GhcIde.hover entered (ideLogger)
2021-01-26 12:40:55.882751912 [ThreadId 1511] - Hover request at position 36:2 in file: /home/jon/projects/haskell/type-tracer/Sandbox.hs
2021-01-26 12:40:56.086717792 [ThreadId 1517] - DocumentHighlight request at position 36:2 in file: /home/jon/projects/haskell/type-tracer/Sandbox.hs



```
</details>

**Comment by theGhostJW** [comment] 2021-02-12 22:19
I think I am facing a similar issue running hsl 0.9.0 on VSCode and windows.

I have been making some extensive changes to a project and stack shows me a laundry list of compilation errors. 

[stack.txt](https://github.com/haskell/haskell-language-server/files/5974500/stack.txt)

The VSCode Haskell (1.2.0) extension is working fine though (jump to definition etc.) and reporting no errors.

[hlsLogs.txt](https://github.com/haskell/haskell-language-server/files/5974503/hlsLogs.txt)

It seems to take a couple of tries to get hls working  with the project in its current state (sometimes it hangs in the initial processing) but when hls loads successfully it never shows me the compilation errors as stack does.

here is the project:
https://github.com/theGhostJW/pyrethrum/releases/tag/hls_not_showing_errors

**Comment by jneira** [comment] 2021-02-13 16:03
In the second case dont seem to be related with the extensions mentioned in the issue.
It seems hls is showing stale info about the project, even after restarting it, coul you delete `%LOCALAPPDATA%\ghcide` and try again?

**Comment by theGhostJW** [comment] 2021-02-13 21:52
Hi @jneira,
I have just deleted `%LOCALAPPDATA%\ghcide` and restarted VSCode. 
A new `main-...` subfolder is created, hls starts successfully and as before seems fully functional but for reporting no errors.

Polykinds and DataKinds is enabled in default extensions for this project but PolyKinds has been disabled on the failing file: `Runner.hs`.

**Comment by theGhostJW** [comment] 2021-03-08 06:08
Assuming mine is a different error I'll create a new issue

**Comment by michaelpj** [comment] 2024-01-11 11:11
Tentatively closing since no recent reproducers.

**Closed by michaelpj** 2024-01-11 11:11 UTC
Labels: type: bug, component: ghcide
