### ISSUE TITLE
Code action to define undefined variables includes suggestions in type signature

### ISSUE THREAD

**Issue by jameshaydon** [haskell/haskell-language-server#3795] opened 2023-09-07 02:14 UTC
### Your environment

MacOS
GHC 9.4.5 from ghcup
cabal
emacs+lsp-mode
HLS v2.2.0.0 from ghcup

### Steps to reproduce

Write some code with an undefined variable, e.g.:
```haskell
foo :: Int -> Int
foo x = plus x (plus x x)
```

Invoke the code action `Define plus...`

Result:
```haskell
plus :: Int -> t0 -> Int Suggested fix: Perhaps use ‘mplus’ (imported from Control.Monad.Reader)
plus = _
```

### Expected behaviour

The suggestion should not be in the type signature, possibly it could be a comment before/after the type signature.

### Actual behaviour

Suggestion in the signature, causing a parse error.

**Comment by michaelpj** [comment] 2023-09-07 08:39
Looks like a bug in the regex for parsing stuff out of the GHC error message...

**Comment by jhrcek** [comment] 2024-01-24 05:14
Stumbled upon this while checking for some easy bugs to fix.
It seems the problem is that the bug is coming from [this regex](https://github.com/haskell/haskell-language-server/blob/d6553e001f5134401aef1c676817211947740583/plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/Diagnostic.hs#L47) and the fact that 
- the regex works on pre-processed error message in which spaces have been unified (that is replace every sequence of whitespace (including newlines) in the error with a single space).
- it seems that recent GHCs don't contain the "bulletpoint" characters that the regex uses to detect the end of type signature.

This shouldn't be that hard to fix, but I wonder if it's worth trying to make the regexes more robust, or try to use the new structured erros for this (which were only introduced in recent GHCs, something like 9.6+?)

@michaelpj any opinions?

**Comment by michaelpj** [comment] 2024-01-24 10:26
I think using the structured errors is a whole project, I'm planning to propose it as a GSoC project. So probably not a quick fix. Whereas fixing the regex is a patch, but at least should be quick. What would be extremely helpful in any case would be writing a test that shows the problem!

**Comment by jhrcek** [comment] 2024-01-26 11:06
Fixed in https://github.com/haskell/haskell-language-server/pull/4016 so this can be closed.

**Closed** 2024-01-26 13:57 UTC
Labels: type: bug

**Comment by jameshaydon** [comment] 2024-01-27 04:27
Thanks!
