### ISSUE TITLE
HLS is broken with some TH code: "Error dynamically loading libm.so.6"

### ISSUE THREAD

**Issue by sonowz** [haskell/haskell-language-server#1601] opened 2021-03-21 08:40 UTC
### Your environment

- VSCode
- NixOS 20.09, with either remote-SSH or remote-WSL
- haskell-language-server version: 1.0.0.0
- stack : 2.3.3

### The error
```sh
[INFO] Making new HscEnv[main]
Error dynamically loading libm.so.6:
libm.so.6: cannot open shared object file: No such file or directory
```
### The cause
https://github.com/haskell/haskell-language-server/blob/b9c6e6cf4de5a0778c5ddb5d5e62fc8d1e0d78ef/ghcide/session-loader/Development/IDE/Session.hs#L345-L349
Related PR: https://github.com/haskell/ghcide/pull/723

The cause is straightforward: by default NixOS does not have `libm.so.6` nor `glibc` in its system environment. Thus HLS literally can't load `libm.so.6`.

### The workaround

Setting `LD_LIBRARY_PATH` to the path which `libm.so.6` lives works and the error is gone. XD
```nix
with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "glibc-patch";
  buildInputs = [ glibc ];
  LD_LIBRARY_PATH = "${glibc}/lib/";
}
```

## Long description

For NixOS, it seems like the error is raised every time I use HLS.
Generally, HLS works as normal, and the error doesn't affect anything. Just error message above (`Error dynamically loading libm.so.6`).
However, if the source code uses some TemplateHaskell, almost **every HLS feature is broken** and produces error below. No code highlighting, no type hints.
![image](https://user-images.githubusercontent.com/18653427/111898188-e305ba00-8a67-11eb-81be-aefc0e2c830f.png)

I think HLS is broken only when system calls in `libm.so.6` really gets called.

**Comment by jneira** [comment] 2021-03-21 20:02
@sonowz wow, this is a almost perfect bug report, many thanks 😄 

Not sure what could be a definitive solution, pinging @pepeiborra just in case.

**Comment by pepeiborra** [comment] 2021-03-21 20:05
The best solution is probably to build HLS with Nix, and not reuse the pre-built binaries

**Comment by sonowz** [comment] 2021-03-23 11:25
I came up with something like this:
```haskell
res <- loadDLL hscEnv "libm.so.6" 
case res of 
  Nothing -> pure () 
  Just err -> downloadLibM >> loadDLL hscEnv "libm.so.6"
```
Is this possible? I have no expertise in these OS-level thingy..

**Comment by jneira** [comment] 2022-01-31 11:31
I am gonna close this issue as all compiler crashes seems to have the same root cause:
* We have a general issue about: https://github.com/haskell/haskell-language-server/issues/1431
* And other one with more info about the causes: https://github.com/haskell/haskell-language-server/issues/2000
* We have a generic workaround (build hls from source dynamically linked) documented in the troubleshooting guide: https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#static-binaries-and-template-haskell-support
* And a possible fix upstream for ghc described in https://github.com/haskell/haskell-language-server/issues/2000#issuecomment-974658606

If any of you think the issue should not be included generically feel free to reopen it (with a brief explanation if possible)
Thanks all!

**Closed by jneira** 2022-01-31 11:31 UTC
Labels: type: bug, can-workaround, os: nixos, component: ghcide
