### ISSUE TITLE
HLS does not update variables when working on multiple files

### ISSUE THREAD

**Issue by Karthik-Dulam** [haskell/haskell-language-server#3419] opened 2022-12-21 15:46 UTC
### Your environment
`stack new bug --resolver nightly-2022-11-12`
This is a ghc-9.4.2 snapshot.

**Which OS do you use?**
ArchLinux

**Which version of GHC do you use and how did you install it?**
GHC 9.2.4 from Stack 

**How is your project built (alternative: link to the project)?**
Stack build

**Which LSP client (editor/plugin) do you use?**
Neovim+LanguageClient-neovim and [HLS-tools](https://github.com/MrcJkb/haskell-tools.nvim#features).
I was able to reproduce this issue on VS Code too.

**Which version of HLS do you use and how did you install it?**
1.8.0 from GHCup

**Have you configured HLS in any way (especially: a `hie.yaml` file)?**
No.
### Steps to reproduce
Prepare a new project using stack new.
`stack new bug --resolver nightly-2022-11-12`
`nvim app/Main.hs src/Lib.hs -p`
Edit Lib.hs
`data Foo = Spam | Eggs`
Edit Main.hs
`bug = Eggs`

### Expected behaviour
No error from HLS.
No error while compiling using GHC.

### Actual behaviour
`Data Constructor not in scope: Eggs`
No error while compiling using GHC.

**Comment by fendor** [comment] 2022-12-21 19:42
Sounds like a duplicate of https://github.com/haskell/haskell-language-server/issues/1822

**Comment by Karthik-Dulam** [comment] 2022-12-22 06:21
Thank you, generating a hie.yaml using gen-hie fixed the problem.

**Closed** 2022-12-22 06:21 UTC
Labels: type: bug, status: needs triage
