### ISSUE TITLE
Space Leak

### ISSUE THREAD

**Issue by ldub** [haskell/haskell-language-server#386] opened 2020-09-09 00:44 UTC
### Subject of the issue
Massive space leak when hacking on persistent.

### Your environment
* Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`
  * How would I run this? I just have the VS Code plugin enabled
* Which lsp-client do you use
  * VS Code
* Describe your project (alternative: link to the project)
  * https://github.com/yesodweb/persistent/issues
* Contents of `hie.yaml`
  * none

### Steps to reproduce
Start hacking on persistent with the vs code hls package

### Expected behaviour
I'm not sure if it should work out of the box with no hie.yaml or anything, but I certainly didnt expect a space leak.

### Actual behaviour
![image](https://user-images.githubusercontent.com/3114081/92541448-e7206780-f1fa-11ea-9729-a96729f150f1.png)

### Include debug information
- macOS Catalina

**Comment by Ailrun** [comment] 2020-09-09 01:28
Does your case have anything to do with https://github.com/haskell/haskell-language-server/issues/352, namely, have a self referencing type?

**Comment by ldub** [comment] 2020-09-09 03:51
Seems likely, but I'm not 100% sure. I think its fine to close this until #352 is resolved and then I can re-test.

**Comment by pepeiborra** [comment] 2020-09-09 07:25
The problem here and in #352 is the lack of `hie.yaml`. We need to either fix the implicit cradle scenario or disallow it completely

**Comment by codygman** [comment] 2020-09-09 16:52
My vote is disable it completely now, release, then figure out how to move forward. Present users with an error that they need to create a cradle and link them to instructions.

A lot of people got burned off of using HIE because of performance issues and went back to just ghcid.

I think the publicity of hls is at stake here, though it's created a lot of performance goodwill.

**Comment by Ailrun** [comment] 2020-09-09 18:36
I also think it would be better to disallow it for now, as it looks like https://github.com/haskell/haskell-language-server/pull/186 won't be completed any time soon. There are a lot of issues which will be resolved with valid `hie.yaml`, but abstruse errors confuse users so that they post those issues. What's worse, users may decide to just leave HLS without posting an issue.

**Comment by jneira** [comment] 2020-09-09 21:24
Agree but we dont know neither how many are using the implicit cradle happily. Afaik simple projects, typical from newcomers, work with the actual implicit hie. Generate a hie.yaml is not rocket science but those projects will not work anymore and you can hit another errors trying to add it. Newcomers know barely what it is a component! We dont know how many will simple move away.

Maybe if the error message is good enough to motivate them make that additional step... but ideally we should generate it automatically with implicit hie.

**Comment by ndmitchell** [comment] 2020-09-10 10:12
FWIW, I used the implicit cradle with my website generator project this weekend. The experience was very smooth. Had it been a case of "well, if you want to edit those 2 lines _and_ have error checking you must ..." then I wouldn't have used HLS, but would have gone for Ghcid. And I'm a developer of HLS/Ghcide!

I think we should definitely not require a cradle. But if there isn't a cradle, writing out one with implicit hie seems quite reasonable.

**Comment by pepeiborra** [comment] 2020-09-10 18:54
One potential problem with disallowing the implicit cradle scenario is that the ghcide test suite is full of cradle-less unit tests - these are one-module projects with no Cabal or Stack descriptor. So whatever solution we adopt needs to work for that use case or refactor the entire test suite. Or perhaps be specific to haskell-language-server, leaving ghcide on its own

**Comment by codygman** [comment] 2020-09-11 21:01
> FWIW, I used the implicit cradle with my website generator project this weekend. The experience was very smooth. Had it been a case of "well, if you want to edit those 2 lines _and_ have error checking you must ..." then I wouldn't have used HLS, but would have gone for Ghcid. And I'm a developer of HLS/Ghcide!
> 
> I think we should definitely not require a cradle. But if there isn't a cradle, writing out one with implicit hie seems quite reasonable.

To be clear, I think the implicit cradle is valuable.

But if there are edge cases likely to occur with a feature that cause this much memory usage, I'd argue stability should be favored.

It sounds like @ndmitchell avoided this memory leak in the course of normal development though. I wonder why.

**Comment by ndmitchell** [comment] 2020-09-12 11:18
> It sounds like @ndmitchell avoided this memory leak in the course of normal development though. I wonder why.

Or it leaked, but so slowly I didn't notice. It's 2 Haskell files.

> But if there are edge cases likely to occur with a feature that cause this much memory usage, I'd argue stability should be favored.

We should fix the feature, rather than harming newcomers experiences. It doesn't seem too hard to generate a hie.yaml in one step, and then use it in a second.

**Comment by ldub** [comment] 2020-09-16 23:36
![image](https://user-images.githubusercontent.com/3114081/93402846-b5328500-f83a-11ea-8ab2-285f763265be.png)
also getting pretty high CPU usage, locking up my system

**Comment by Ailrun** [comment] 2021-01-28 06:57
I believe now we are using a better implicit hie.yaml. Are you still able to reproduce the same memory leak?

**Comment by jneira** [comment] 2022-01-31 10:12
@ldub newer hls versions has lot of improvements around memory usage so i am gonna clode this optimistically, feel free to reopen if you continue experiencing it with a new hls version

**Closed by jneira** 2022-01-31 10:12 UTC
Labels: type: bug, status: needs repro, type: performance, status: needs confirmation
