### ISSUE TITLE
Refactoring type constructor of data incorrectly renames the record fields too

### ISSUE THREAD

**Issue by Aster89** [haskell/haskell-language-server#4083] opened 2024-02-17 16:40 UTC
### Your environment

Which OS do you use? ArchLinux (up-to-date)
Which version of GHC do you use and how did you install it? 9.4.8, via GHCup
How is your project built (alternative: link to the project)? Irrelevant, I just open a new file

Which LSP client (editor/plugin) do you use? Vim(terminal) + YCM
Which version of HLS do you use and how did you install it? 2.5.0.0, via GHCup
Have you configured HLS in any way (especially: a `hie.yaml` file)? ... I think I haven't...

### Steps to reproduce

1. Create a one-line file with content  `data Foo = Bar { a :: !Int , b :: !Int }`
2. put the cursor try to refactor `Bar` to be `Baz`

### Expected behaviour

The code should be become
```haskell
data Foo = Bar { a :: !Int , b :: !Int }
```

### Actual behaviour

But it becomes
```haskell
data Foo = Baz { Baz :: !Int , Baz :: !Int }
```

### Debug information

Is this the relevant piece?
```none
2024-02-17 16:01:41,666 - DEBUG - TX: Sending message: b'Content-Length: 172\r\n\r\n{"id":2,"jsonrpc":"2.0","method":"textDocument/rename","params":{"newName":"Baz","position":{"character":13,"line":0},"textDocument":{"uri":"file:///home/enrico/uffa.hs"}}}'
2024-02-17 16:01:41,690 - DEBUG - RX: Received message: b'{"id":2,"jsonrpc":"2.0","result":{"documentChanges":[{"edits":[{"newText":"data Foo = Baz { Baz :: !Int , Baz :: !Int }","range":{"end":{"character":40,"line":0},"start":{"character":0,"line":0}}}],"textDocument":{"uri":"file:///home/enrico/uffa.hs","version":1}}]}}'
127.0.0.1 - - [17/Feb/2024 16:01:41] "POST /run_completer_command HTTP/1.1" 200 348
2024-02-17 16:01:41,693 - DEBUG - in-event <InotifyEvent: src_path=b'/home/enrico/.uffa.hs.swp', wd=1, mask=IN_MODIFY, cookie=0, name='.uffa.hs.swp'>
2024-02-17 16:01:41,713 - DEBUG - Event name: FileReadyToParse
2024-02-17 16:01:41,713 - INFO - Adding buffer identifiers for file: /home/enrico/uffa.hs
2024-02-17 16:01:41,714 - DEBUG - Refreshing file /home/enrico/uffa.hs: State is Open -> Open/action Change
2024-02-17 16:01:41,714 - DEBUG - TX: Sending notification: b'Content-Length: 204\r\n\r\n{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"text":"data Foo = Baz { Baz :: !Int , Baz :: !Int }\\n"}],"textDocument":{"uri":"file:///home/enrico/uffa.hs","version":2}}}'
127.0.0.1 - - [17/Feb/2024 16:01:41] "POST /event_notification HTTP/1.1" 200 2
2024-02-17 16:01:41,717 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"message":"parse error on input \xe2\x80\x98Baz\xe2\x80\x99","range":{"end":{"character":20,"line":0},"start":{"character":17,"line":0}},"severity":1,"source":"parser"}],"uri":"file:///home/enrico/uffa.hs","version":2}}'
```

**Comment by Aster89** [comment] 2024-02-17 16:55
I'm trying to understand how to give you the HLS logs directly, rather than those represented by YCM.

**Comment by jhrcek** [comment] 2024-02-17 17:41
Thanks for the bug report!
In this case logs are not necessary,
the reproducer you described is sufficient (I managed to reproduce it too).
I'll look into this and try to fix it.

**Comment by fendor** [comment] 2024-02-17 17:58
@jhrcek FWIW, I think this is relatively well-known and a bug in hiedb.

**Comment by theGhostJW** [comment] 2024-02-17 19:51
perhaps @fendor is referring to this:
https://github.com/wz1000/HieDb/issues/45

also looks like this has been logged before:
https://github.com/haskell/haskell-language-server/issues/2915

**Comment by fendor** [comment] 2024-03-06 13:32
Closing in favour of #2915

**Closed by fendor** 2024-03-06 13:32 UTC
Labels: type: bug, status: needs triage
