### ISSUE TITLE
Eval plugin appears to stop working after a function def that has more than one pattern match

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#3312] opened 2022-11-01 15:04 UTC
#### Which OS do you use?
NixOS

#### Which version of GHC do you use and how did you install it?
```
[nix-shell:/tmp]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.4
```
via nix

#### How is your project built (alternative: link to the project)?
No project

##### Which LSP client (editor/plugin) do you use?
Neovim+LanguageClient-neovim

#### Which version of HLS do you use and how did you install it?
```
[nix-shell:/tmp]$ haskell-language-server --version
2022-11-01T15:02:05.261746Z | Info | No log file specified; using stderr.
haskell-language-server version: 1.8.0.0 (GHC: 9.2.4) (PATH: /nix/store/d717g1x6mr0310lijj6671pws1k5cvn7-haskell-language-server-1.8.0.0/bin/.haskell-language-server-9.2.4-unwrapped)
```
via `nix-shell -p haskell.packages.ghc924.haskell-language-server`

#### Have you configured HLS in any way (especially: a `hie.yaml` file)?
No

### Steps to reproduce
For the following file
```haskell
-- >>> 5
-- 5
bla :: Bool -> Bool
bla True = True
bla False = False
```
The `Evaluate...` code lens pops up. However, for the following file
```haskell
bla :: Bool -> Bool
bla True = True
bla False = False
-- >>> 5
```
it doesn't. 

The thing that triggers this issue appears to be any multiline (more than one match) function definition.

This issue does not reproduce if we're using an hls built with 9.0.2

**Comment by googleson78** [comment] 2022-11-01 15:14
Here're the logs from the language server and from the client from the following experiment:

0. Start with the file that has `Evaluate`.
1. Wait for `Evaluate...` to pop up
2. Move the `-- >>> 5` below the function.
3. Wait some time.
4. Close the file

[LanguageClient.log](https://github.com/haskell/haskell-language-server/files/9911553/LanguageClient.log)
[LanguageServer.log](https://github.com/haskell/haskell-language-server/files/9911554/LanguageServer.log)

**Comment by turbotimon** [comment] 2023-02-21 16:52
Maybe it't the same problem? #3500+

**Comment by PiDelport** [comment] 2023-05-15 19:52
This looks like the same issue as:

- https://github.com/haskell/haskell-language-server/issues/3129

**Comment by jfong2702** [comment] 2023-10-04 17:38
I am having the same issue what was the resolution?

**Comment by googleson78** [comment] 2023-10-23 14:45
This continues to be unresolved - any clues? The eval functionality is extremely helpful for teaching - you can leave examples with expected output for students, and they can easily run pseudo-unit tests to verify that their program works for those cases

**Comment by trevarj** [comment] 2023-12-30 13:40
@googleson78 FYI, this seems resolved on the HLS 2.5.0.0.

**Comment by fendor** [comment] 2023-12-30 15:19
![image](https://github.com/haskell/haskell-language-server/assets/8463814/33b50532-f071-4ca6-9d87-d3a8b58d3ef0)

I can still reproduce on 2.5.0.0 with GHC 9.4.8.

**Comment by trevarj** [comment] 2023-12-30 16:02
I was testing using 2.5.0.0 and GHC 9.8.1

**Comment by jhrcek** [comment] 2024-03-03 13:55
This issue has been fixed by https://github.com/haskell/haskell-language-server/pull/4113

**Closed by jhrcek** 2024-03-03 13:55 UTC
Labels: type: bug, component: hls-eval-plugin
