### ISSUE TITLE
`stylish-haskell` not picking up `.stylish-haskell.yaml` in parent directory

### ISSUE THREAD

**Issue by typed-hole** [haskell/haskell-language-server#540] opened 2020-10-26 17:35 UTC
When I set the formatting provider to `stylish-haskell`, I expect it to make use of a relevant `.stylish-haskell.yaml` configuration file (according to the rules specified by `stylish-haskell` itself, c.f. https://github.com/jaspervdj/stylish-haskell#configuration), but I can't get it to pick one up, no matter where I put it.

The smallest minimal reproducible example I can come up with is:
1) create a new minimal haskell project (e.g. a plain `cabal init`)
2) place a `.stylish-haskell.yaml` config in it that differs in any way from the standard
3) set `haskell.formattingProvider` to `stylish-haskell`, for the workspace or user
4) trigger a format document in a source file

From my tests, it still uses the default stylish haskell settings. I've also attempted to place the `.stylish-haskell.yaml` file in `~`, but it made no difference.

I have verified that my stylish haskell configuration file is not the issue, by invoking `stylish-haskell` manually on a file in the command line, the the result is then the expected formatting.

**Comment by jneira** [comment] 2020-10-26 19:27
@Ailrun maybe do you have some time to take a look into this?

**Comment by Ailrun** [comment] 2020-10-26 23:00
@jneira I will take a look if anyone doesn't in next 2 weeks or so, as I'm currently too busy for some paper works...

**Comment by Ailrun** [comment] 2020-11-26 16:53
@typed-hole, could you give me more clues? It works well with latest HLS/Emacs on Linux.
It would be great if you could provide a reproduction repo with more detailed instruction.

**Comment by jneira** [comment] 2021-02-24 08:03
@typed-hole could you confirm if the issue continue being reproduced? i am afraid that we will close it id there will be not feedback (as we cant reproduce it)

**Comment by teto** [comment] 2021-11-09 16:46
seems to work for me.

**Comment by jneira** [comment] 2021-11-09 20:51
@teto thanks for confirming it, will close, @typed-hole feel free to reopen if it continue failing for you (with a reproducible case if possible)

**Closed by jneira** 2021-11-09 20:51 UTC
Labels: type: enhancement, status: needs repro, component: plugins, status: needs confirmation

**Comment by sekunho** [comment] 2022-02-23 07:04
I ran into this but only because I used the incorrect file extension. I had `.stylish-haskell.yml` so HLS didn't pick it up, but it worked when I used `.stylish-haskell.yaml`.

**Comment by sekunho** [comment] 2022-02-23 10:54
@Ailrun Thanks! I wanted to note this in case someone gets the same problem as me. :smile:
