### ISSUE TITLE
stack: hls fails to load modules from test component

### ISSUE THREAD

**Issue by 1Computer1** [haskell/haskell-language-server#151] opened 2020-06-06 22:21 UTC
To reproduce:
- `$ stack new bug`
- Create `.hie.yaml` with the three targets:
```
cradle:
    stack:
        - path: "./src"
          component: "bug:lib"
        - path: "./app"
          component: "bug:exe:bug-exe"
        - path: "./test"
          component: "bug:test:bug-test"
```
- Create a bunch of new modules in the library.
- Import them in the tests. It should work at the moment.
- Reload/restart HLS? I'm not sure about this step, something goes wrong here.
- The test module should now fail to find one of the library modules, and adding new ones won't work either. It doesn't seem to work after another reload too.

The logs seem to tell me that it is using the wrong `.cabal` file:
```
"Making new HscEnv[main]"
(([],Just HscEnvEq 4),fromList [("bug.cabal",Just 2020-06-06 22:16:45.8126357 UTC),("package.yaml",Just 2020-06-06 22:04:03.9856616 UTC),("stack.yaml",Just 2020-06-06 22:04:04.6931537 UTC)])
2020-06-06 18:18:41.2528917 [ThreadId 125] - finish: FileStoreTC (took 6.83s)
2020-06-06 18:18:41.3349849 [ThreadId 344] - finish: InitialLoad (took 0.07s)
```

The file is from `2020-06-06 22:16:45.8126357 UTC` but the current time is `18:18:41.2528917`.

I'm on Stack LTS 15.15, commit 2310e1039c90d9bccaffd688a0d1ec79a9360bf4 of HLS, Ubuntu 20.04 (WSL 1).

**Comment by jneira** [comment] 2020-06-12 07:33
Did you build stack with tests enabled (with `stack build --test --no-run-tests`) at any moment? 
I am afraid stack does not build tests by default and the ide (through hie-bios) cant find the required files to load test modules. The root cause is in stack: https://github.com/commercialhaskell/stack/issues/5213

@1Computer1  please, try to build tests with the cited command above and reload the ide to check it.

**Comment by 1Computer1** [comment] 2020-06-12 21:26
I can confirm that building the tests and then a reload fixes the problem.

**Comment by jneira** [comment] 2020-06-12 21:48
Thanks for report and try the workaround, we'll keep this one to track this problem. It is a frequent issue, reported in #121 for example.

**Comment by jneira** [comment] 2020-11-09 07:37
As https://github.com/commercialhaskell/stack/issues/5213 was fixed, using a newer stack version should not reproduce the issue, @1Computer1 could you confirm it, pleas?

**Comment by jneira** [comment] 2020-11-17 06:41
I am gonna optimistically close the issue, @1Computer1 feel free to reopen if you continue hitting the error

**Closed by jneira** 2020-11-17 06:41 UTC
Labels: build tool: stack, can-workaround, component: hie-bios, status: needs confirmation, type: bug
