### ISSUE TITLE
'unknown symbol' error  when running hls on the stack codebase

### ISSUE THREAD

**Issue by theobat** [haskell/haskell-language-server#330] opened 2020-08-16 16:56 UTC
Hi,

The repo where this happens is https://github.com/commercialhaskell/stack/
I slightly modified the package.yaml to use GHC 8.8.3 and LTS-16.9 (but an older one does not change this issue)

I get:
```
haskell-language-server-8.8.3: 
lookupSymbol failed in relocateSection (relocate external)
/Users/theophile/.stack/snapshots/x86_64-osx/63fd7302eafdb4f0848748d641de7b97f139e859d01e32c9b472b68facb0ed5d/8.8.3/lib/x86_64-osx-ghc-8.8.3/hackage-security-0.6.0.1-EOE2VKs23b41HWmlFHCnG/libHShackage-security-0.6.0.1-EOE2VKs23b41HWmlFHCnG.a: unknown symbol `___dso_handle'
```

I'm not sure what to do with this or where it comes from, ~~I didn't find any occurence of `___dso_handle` on google~~.
Here's an interesting [GHC issue](https://gitlab.haskell.org/ghc/ghc/-/issues/9010) though, I'm trying to see if something can be done at the hackage-security level (or a shared C lib they use)
Also, maybe it's unrelated, but Template Haskell is used in several places in the stack codebase.

**Comment by theobat** [comment] 2020-08-26 19:06
Another interesting thread on google about ___dso_handle:
https://mail.haskell.org/pipermail/haskell-cafe/2011-January/088041.html

It definitely seems to be related to template haskell

**Comment by theobat** [comment] 2021-01-07 23:07
Yet another interesting suggestion in (untested for now) : https://stackoverflow.com/questions/26449154/a-workaround-for-the-template-haskell-c-bug

Seems like this is also an issue on linux (the linking fails, with different errors though)

**Comment by jneira** [comment] 2022-01-31 08:46
I am gonna close this issue as all compiler crashes seems to have the same root cause:
* We have a general issue about: https://github.com/haskell/haskell-language-server/issues/1431
* And other one with more info about the causes: https://github.com/haskell/haskell-language-server/issues/2000
* We have a generic workaround (build hls from source dynamically linked) documented in the troubleshooting guide: https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#static-binaries-and-template-haskell-support
* And a possible fix upstream for ghc described in https://github.com/haskell/haskell-language-server/issues/2000#issuecomment-974658606

If any of you think the issue should not be included generically feel free to reopen it (with a brief explanation if possible)
Thanks all!

**Closed by jneira** 2022-01-31 08:46 UTC
Labels: type: bug, status: needs repro, os: macos, type: template haskell related
