### ISSUE TITLE
Nix Shell error: Package ‘retrie-0.1.1.1’ is marked as broken, refusing to evaluate

### ISSUE THREAD

**Issue by Sir4ur0n** [haskell/haskell-language-server#325] opened 2020-08-16 11:55 UTC
On a fresh `master`, when running `nix-shell`, it fails because of `retrie` being marked as broken:
```shell
$ nix-shell
error: Package ‘retrie-0.1.1.1’ in /nix/store/p49mi5i4r35n1m6kx07lkxp07p8hh8hs-source/pkgs/development/haskell-modules/hackage-packages.nix:214783 is marked as broken, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)
```

Edit: FYI changing the following in `shell.nix` makes it work, but I am unsure if this is a good idea...
```git
-   nixpkgs ? import sources.nixpkgs {},
+   nixpkgs ? import sources.nixpkgs {config.allowBroken = true;},
```

**Comment by pepeiborra** [comment] 2020-08-16 21:55
Please send a PR with the allowBroken fix

**Comment by Sir4ur0n** [comment] 2020-08-16 22:03
Done in https://github.com/haskell/haskell-language-server/pull/331

**Comment by jneira** [comment] 2020-08-16 22:50
I guess we should keep this open to find out the root cause and find another definitive solution.

**Comment by pepeiborra** [comment] 2020-08-17 07:04
The root cause is that the package is marked as broken in Nix because the tests fail. This is unlikely to change, the tests will continue to fail in a Nix build. 
I failed to notice it earlier because I have allowBroken=True in my system settings.

**Closed** 2020-08-17 07:04 UTC
Labels: build, can-workaround, os: nixos, type: bug

**Comment by Sir4ur0n** [comment] 2020-08-17 07:07
I think the definitive solution is for `retrie` to no longer be marked as broken in Nixpkgs :smile: 

It seems that @maralorn has [fixed it already](https://github.com/NixOS/nixpkgs/pull/95585) (while also kindly bumping Nixpkgs version of HLS to 0.3), this should be fine in a couple of days when the next wave of Haskell package is published.

When this becomes available in Nixpkgs, all we need to do is update the sources in `./nix/` and we should be good to go :smile:

**Comment by Sir4ur0n** [comment] 2020-08-17 17:21
Shouldn't this issue be reopened?

**Comment by pepeiborra** [comment] 2020-08-17 18:56
Even if the retrie tests are disabled in Nix, I think we should keep `allowBroken=true` in our `shell.nix` file
