### ISSUE TITLE
Incorrect flags when loading multiple executable components on GHC 9.4

### ISSUE THREAD

**Issue by Vic-M** [haskell/haskell-language-server#3513] opened 2023-03-05 00:53 UTC
Hello, I'm not sure if this is a configuration issue with my hie.yaml, but I'm unable to get HLS to work with two Main.hs files at the same time. There's no issues with compiling both of them with cabal though.

### Your environment
**Which OS do you use?**
Windows WSL2 running CentOS Stream 9

**Which version of GHC do you use and how did you install it?**
GHC 9.4.4 from ghcup

**How is your project built (alternative: link to the project)?**
https://gitlab.com/vmatassa/hls-two-main-example

**Which LSP client (editor/plugin) do you use?**
vscode

**Which version of HLS do you use and how did you install it?**
HLS 1.9.1.0 from ghcup

### Steps to reproduce

1. Open projectA/app/Main.hs
2. Open projectB/app/Main.hs right after

### Actual behaviour

HLS is unable to recognize libraries that are exclusively in projectB cabal's file.

```
Could not load module ‘Data.Aeson’
It is a member of the hidden package ‘aeson-2.1.2.1’.
Perhaps you need to add ‘aeson’ to the build-depends in your .cabal file.
It is a member of the hidden package ‘aeson-2.1.1.0’.
Perhaps you need to add ‘aeson’ to the build-depends in your .cabal file.
It is a member of the hidden package ‘aeson-2.1.1.0’.
Perhaps you need to add ‘aeson’ to the build-depends in your .cabal file.
```

![image](https://user-images.githubusercontent.com/32042587/222935491-354c5ac8-9e2b-4389-9f5c-30ef69dd80fd.png)

### Expected behaviour

HLS should be able to find installed libraries from all cabal files in the project.

**Comment by fendor** [comment] 2023-03-05 13:34
Hi, thank you for your bug report!

I can reproduce on windows.
Maybe we use relativ filepaths somewhere...

**Comment by L0neGamer** [comment] 2023-05-19 10:58
My company upgraded to GHC 9.4.5 last thursday and we're getting similar issues with our HLS instances. We have multiple packages in the same project, and the ones marked as missing include both our own packages and ones like `shakespeare-2.1.0`, `directory-1.3.7.1`, and others.

Do the maintainers need any investigation on symptom-observers' behalf?

**Comment by georgefst** [comment] 2023-06-13 17:24
This stems from 6c99563a9f82f2545448e54be93180b935513ccc, and commenting out the `Set up a multi component session with the other units on GHC 9.4` CPP branch appears to fix the behaviour. I don't know whether it's worth opening a PR doing so for now, as it might have other undesirable effects. And maybe there's a mistake that's obvious to @wz1000, who wrote the code. I don't personally know the new home units API well enough to easily debug much further.

PS. thanks @fendor for pointing me in the right direction.

**Comment by georgefst** [comment] 2023-06-13 17:28
(changing the title because I've been consistently seeing this with https://github.com/georgefst/evdev, in which the executables are defined in the _same_ cabal file, and because it's now clear this is 9.4-specific)

**Closed** 2023-07-26 11:26 UTC
Labels: type: bug, component: ghcide
