### ISSUE TITLE
Wingman Intelligent derivations of Semigroup and Monoid doesn't work as expected.

### ISSUE THREAD

**Issue by FongHou** [haskell/haskell-language-server#1680] opened 2021-04-06 20:15 UTC
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

It's built from master source with @isovector PR #1675 merged locally.

```sh
❯ haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /home/haskeller/.local/bin/haskell-language-server-wrapper) (GIT hash: c67b233bd21bc749e011ce9c5f7038466b69be7e)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.5.1
ghc:            Not found
```

Which OS do you use:

Which lsp-client do you use: coc-nvim on Ubuntu

Describe your project (alternative: link to the project):

Contents of `hie.yaml`: 
```yaml
❯ cat hie.yaml
cradle:
  stack:
```

### Steps to reproduce

![image](https://user-images.githubusercontent.com/13973254/113771679-b00f2780-96f1-11eb-9564-1e0b43d7e728.png)

### Expected behaviour

According to plugins/hls-tactics-plugin/test/golden/KnownDestructedSemigroup.hs.expected

```
data Test a = Test [a]

instance Semigroup (Test a) where
   (<>) (Test a) (Test c) = Test (a <> c)
```

Ideally,
```
data Test a = Test [a]

instance Semigroup (Test a) where
   Test a <> Test c = Test (a <> c)
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/13973254/113771759-ccab5f80-96f1-11eb-9e13-035fc7827450.png)

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
<paste your logs here>
!!!goal: Judgement {_jHypothesis = Hypothesis {unHypothesis = [HyInfo {hi_name = a, hi_provenance = PatternMatchPrv (PatVal {pv_scrutinee = Just _0, pv_ancestry = fromList [<>,_0], pv_datacon = Test, pv_position = 0}), hi_type = [a]},HyInfo {hi_name = _0, hi_provenance = DisallowedPrv AlreadyDestructed (TopLevelArgPrv <> 0 2), hi_type = Test a},HyInfo {hi_name = c, hi_provenance = PatternMatchPrv (PatVal {pv_scrutinee = Just _1, pv_ancestry = fromList [<>,_1], pv_datacon = Test, pv_position = 0}), hi_type = [a]},HyInfo {hi_name = _1, hi_provenance = DisallowedPrv AlreadyDestructed (TopLevelArgPrv <> 1 2), hi_type = Test a},HyInfo {hi_name = <>, hi_provenance = ClassMethodPrv Semigroup, hi_type = a -> a -> a},HyInfo {hi_name = sconcat, hi_provenance = ClassMethodPrv Semigroup, hi_type = NonEmpty a -> a},HyInfo {hi_name = stimes, hi_provenance = ClassMethodPrv Semigroup, hi_type = forall b. Integral b => b -> a -> a}]}, _jBlacklistDestruct = False, _jWhitelistSplit = True, _jIsTopHole = True, _jGoal = Test a}
!!!ctx: [(<>,Test a -> Test a -> Test a)]
!!!skolems: fromList [a]
!!!other solution: case a of
  [] -> Test []
  (a7 : l_a) -> Test []
!!!with score: (Down 0,False,Down 0,Down 2,1,Down 0,Down 87)
!!!other solution: case a of
  [] -> Test []
  (a7 : l_a) -> Test (a7 : [])
!!!with score: (Down 0,False,Down 0,Down 2,2,Down 0,Down 161)
!!!other solution: case a of
  [] -> Test []
  (a7 : l_a) -> Test c
!!!with score: (Down 0,False,Down 0,Down 2,2,Down 0,Down 87)
!!!other solution: case a of
  [] -> Test c
  (a7 : l_a) -> Test c
!!!with score: (Down 0,False,Down 0,Down 2,2,Down 0,Down 87)
!!!other solution: case a of
  [] -> Test c
  (a7 : l_a) -> Test []
!!!with score: (Down 0,False,Down 0,Down 2,2,Down 0,Down 87)
!!!other solution: case a of
  [] -> Test []
  (a7 : l_a) -> Test (a7 : c)
!!!with score: (Down 0,False,Down 0,Down 2,3,Down 0,Down 161)
!!!other solution: case a of
  [] -> Test c
  (a7 : l_a) -> Test (a7 : c)
!!!with score: (Down 0,False,Down 0,Down 2,3,Down 0,Down 161)
!!!other solution: case a of
  [] -> Test c
  (a7 : l_a) -> Test (a7 : [])
!!!with score: (Down 0,False,Down 0,Down 2,3,Down 0,Down 161)
!!!other solution: Test []
!!!with score: (Down 0,True,Down 0,Down 0,0,Down 0,Down 7)
!!!other solution: Test c
!!!with score: (Down 0,True,Down 0,Down 0,1,Down 0,Down 7)
!!!other solution: Test a
!!!with score: (Down 0,True,Down 0,Down 0,1,Down 0,Down 7)
!!!solution: Test a

```
</details>

**Comment by July541** [comment] 2021-04-07 09:00
@Ailrun I dump the test response of tactics, it generates the correct result, but not successfully apply this action to the client(fails as this issue described). I can't locate the issue where it occurs.

Here is the code action's response of `KnownDestructedSemigroup.hs`:
![image](https://user-images.githubusercontent.com/16057632/113839457-46ab1980-97c2-11eb-90e9-504871004b75.png)
We can see clearly it generate the correct result.

Does there exist any trick to trace the calling stack? I'd love to fix it.

**Comment by isovector** [comment] 2021-04-07 14:33
This is by design --- for now. Some new features are intentionally guarded from the public release as [incentives for my patreon](https://www.patreon.com/posts/49741761). Signing up for the "Beta" tier gets you access to these things as soon as they're merged.

This is not forever, cool new features will be enabled globally with a one-release latency.

It sorta sucks, but I'm working on Wingman full time, and need to find some way to make ends meet. Corporate sponsorship would be the dream here, where I can build features without worrying about monetization, but unfortunately that's not currently in the cards.

If you want to forge forwards here, the feature protection is intentionally very easy to work around. You have my blessing to go reverse engineer it --- but please don't talk about it.

**Closed by isovector** 2021-04-07 14:33 UTC
Labels: component: wingman, status: needs repro, type: bug
