### ISSUE TITLE
ghcide error (cabal.project related?)

### ISSUE THREAD

**Issue by joehendrix** [haskell/haskell-language-server#794] opened 2020-03-17 22:05 UTC
I get the following error when running ghcide in a project with a `cabal.project` file in it.  Are cabal vs project files supported?

```
Step 4/6, Cradle 1/1: Loading GHC Session
> cabal: Unrecognised target syntax for ''.
> 
ghcide: CradleError (ExitFailure 1) ["Failed to parse result of calling cabal","","cabal: Unrecognised target syntax for ''.\n\n",""]
```

Here is what I am using for ghc and cabal versions:

```
~% ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5
~% cabal --version
cabal-install version 3.0.1.0
compiled using version 3.0.2.0 of the Cabal library 
```
Any help would be appreciated.

**Comment by jneira** [comment] 2021-01-12 08:08
The ghcide executable is being deprecated as external tool and i cant reproduce with hls and cabal> 3.0 (so update it should fix it) so i am gonna close it. Feel free to reopen if you continue experiencing it.

**Closed by jneira** 2021-01-12 08:08 UTC
Labels: build tool: cabal, type: bug, type: setup
