### ISSUE TITLE
Suggested pattern signature doesn't account for provided constraints

### ISSUE THREAD

**Issue by sheaf** [haskell/haskell-language-server#1975] opened 2021-06-24 17:15 UTC
It seems that the suggested pattern signature is not always correct in the presence of provided constraints. For instance:

```haskell
{-# LANGUAGE PatternSynonyms #-}
import GHC.TypeNats

pattern MySomeNat a = SomeNat a
```

HLS suggests the pattern signature
```haskell
pattern MySomeNat :: KnownNat n => Proxy n -> SomeNat
```

which is incorrect, as `KnownNat n` is not a required constraint (that is needed in order to write down the pattern synonym) but a provided one (which becomes available once pattern matching succeeds).

The pattern signature that HLS should suggest is the following:

```haskell
pattern MySomeNat :: () => KnownNat n => Proxy n -> SomeNat
```

which uses the peculiar pattern signature syntax wherein the first set of constraints denotes those that are required, and the second the provided ones.

Another example:

```haskell
class MyClass (n :: Nat)

pattern MySomeNat1 :: MyClass n => KnownNat n => Proxy n -> SomeNat
pattern MySomeNat1 a = SomeNat a

pattern MySomeNat2 a = MySomeNat1 a
```

HLS suggests the pattern signature:

```haskell
pattern MySomeNat2 :: (MyClass n, KnownNat n) => Proxy n -> SomeNat
```

Not understanding that

```haskell
pattern MySomeNat2 :: MyClass n => KnownNat n => Proxy n -> SomeNat
```

means something different.

It seems like there is some logic that rewrites a constraint involving multiple constraint arrows. For instance, if one writes:

```haskell
{-# LANGUAGE NoMonomorphismRestriction #-}

x :: () => Num a => Ord a => Bounded a => a
x = 1

y = x
```

Then HLS suggests the following type for y:

```haskell
y :: (Num a, Ord a, Bounded a) => a
```

This is obviously fine in this case, but the same rewriting is invalid for pattern signatures.

Version: Haskell Language Server 1.2.0 with GHC 9.0.

**Comment by peterwicksstringfield** [comment] 2021-06-25 01:11
Duplicate of #1951; should be fixed by #1952.

Maybe take a look at the tests in that PR? I think this covers the use case you have in mind?

ghcide/test/Main.hs
```haskell
...
           , "data T1 a where"
           , "  MkT1 :: (Show b) => a -> b -> T1 a"
...
    , "pattern MkT1' b = MkT1 42 b" >:: 
        -- should have type
           "pattern MkT1' :: (Eq a, Num a) => Show b => b -> T1 a"
...
```

**Comment by jneira** [comment] 2021-06-25 05:26
@sheaf thanks for report the issue, will close as duplicate if you use case match the test posted above

**Comment by sheaf** [comment] 2021-06-25 09:35
Excellent, thanks for your work @peterwicksstringfield. Your solution does indeed cover the situation in the OP.

To answer your other question, in your second example, the type signature you give for `y` is precisely the one I'd expect GHC to infer. (Technically we don't need the `Eq a` instance to use `MkT1` as a constructor, but we don't have a way of specifying that information when writing a pattern signature).

**Closed** 2021-06-25 12:07 UTC
Labels: status: needs confirmation, type: bug

**Comment by peterwicksstringfield** [comment] 2021-06-27 01:53
@sheaf, thanks! Glad we are on the same page.
