### ISSUE TITLE
Case split does not work

### ISSUE THREAD

**Issue by largeword** [haskell/haskell-language-server#3575] opened 2023-05-03 20:56 UTC
Hi, in [PR](https://github.com/haskell/vscode-haskell/pull/70), there is supposed a case automatically split up feature, but it does not show up in vscode, and I also don't know how to enable it manually.

So can someone guide me in the right direction to make it work?

**Comment by michaelpj** [comment] 2023-05-06 11:30
I'm going to close as a duplicate of https://github.com/haskell/haskell-language-server/issues/2971

**Closed by michaelpj** 2023-05-06 11:30 UTC
