### ISSUE TITLE
[Feature Request] Code action to add unused symbol to module export list

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#348] opened 2020-08-24 10:04 UTC
Upon defining a top level symbol that is unused in the module, it would be nice if instead of just "delete" there was also a code action to add to the export list.

```haskell
module Lib () where

foo = ...
-- ^this triggers a "unused symbol" warning
```

=>

```haskell
module Lib (foo) where

foo = ...
```

**Comment by pepeiborra** [comment] 2020-08-24 11:04
Duplicate of #157

**Closed by pepeiborra** 2020-08-24 11:04 UTC
Labels: type: enhancement
