### ISSUE TITLE
The filepath is not recognized correctly in a multi-cradle project.

### ISSUE THREAD

**Issue by shin-sakata** [haskell/haskell-language-server#265] opened 2020-08-01 04:55 UTC
This is the minimal project that causes the symptoms.
https://github.com/shin-sakata/multi-cradle-example

It's a project that outputs itself to standard output.

`stack run component1`

```
{-# LANGUAGE TemplateHaskell #-}

module Lib
    ( someFunc
    ) where

import Data.FileEmbed (embedStringFile)

someFunc :: IO ()
someFunc = putStrLn file

file :: String
file = $(embedStringFile "./src/Lib.hs")
```

This project works correctly, but I get a warning.

<img width="387" alt="スクリーンショット 2020-08-01 13 50 27" src="https://user-images.githubusercontent.com/56592600/89094354-fb07cb00-d3fd-11ea-9a04-f97e9379a801.png">

<img width="540" alt="スクリーンショット 2020-08-01 13 51 04" src="https://user-images.githubusercontent.com/56592600/89094357-0fe45e80-d3fe-11ea-9c52-131d333e8778.png">

environment:
  OS: Catalina 10.15.5
  Editor: VScode
  haskell-language-server: 0.2.2

**Comment by jneira** [comment] 2020-11-09 08:07
I think this is a duplicate of #481 (that it is blocked upstream and has a workaround).

**Closed by jneira** 2020-11-09 08:07 UTC
Labels: build tool: stack, component: ghcide, type: bug
