### ISSUE TITLE
[Feature Request] Code action: add unused definition to module exports

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#447] opened 2020-10-01 12:15 UTC
When writing explicit exports, unused top level definitions are marked as "unused".
The only code action available is to remove the definition.
However, one might just want to add it to the export list.

```haskell
module Lib () where

import Foo (Foo (Foo))

foo :: Foo
foo = Foo
```

foo is marked as unused

->

```haskell
module Lib
  ( foo,
  )
where

import Foo (Foo (Foo))

foo :: Foo
foo = Foo
```

**Comment by googleson78** [comment] 2020-10-01 12:26
Duplicate of https://github.com/haskell/haskell-language-server/issues/157, and it seems to already be done?

**Comment by jneira** [comment] 2020-10-01 12:55
Yeah, it should be in hls master.

**Closed by jneira** 2020-10-01 12:55 UTC

**Comment by GuillaumeDesforges** [comment] 2020-10-01 13:29
Sorry about that, I'll update my HLS
