### ISSUE TITLE
Is "version" in lsp response used to assure file consistency (e.g. for renames)?

### ISSUE THREAD

**Issue by codygman** [haskell/haskell-language-server#3498] opened 2023-02-17 19:37 UTC
The context is mostly from https://github.com/joaotavora/eglot/issues/1051#issuecomment-1252791891 which says:

> Probably sending the :version isn't even necessary and Eglot will not perform the check if it isn't present. But if you are the server are going to send one, Eglot assumes its purpose is to assure file consistency and will refuse to perform the edit.

In response to an issue where the user tries to execute a rename and nothing seems to change in emacs with eglot.

**Comment by michaelpj** [comment] 2023-03-22 12:54
This is unclear. It's handled in `lsp` mostly, to be honest I'm not 100% sure how it works, so someone would need to take a look.

**Comment by jameschensmith** [comment] 2023-04-19 16:05
I believe the issue is at [`Ide.PluginUtils#L173`](https://github.com/haskell/haskell-language-server/blob/399d1a24fc578f67e47e2277429f64afb7a28f90/hls-plugin-api/src/Ide/PluginUtils.hs#L173). This is my first time going through Haskell code, but by going through `Ide.Plugin.Rename` I was able to arrive at `Ide.PluginUtils`. It looks like version is either always 0, or it defaults to 0 if there is no version passed by the client. Hope this helps!

**Comment by July541** [comment] 2023-04-20 13:36
@jameschensmith Thanks for pointing it out! I agree with you, and there is an ongoing [pr](https://github.com/haskell/haskell-language-server/pull/3566) for both this and #3547.

**Comment by maralorn** [comment] 2023-06-11 20:39
This should be fixed by the just merged #3643, maybe you can test this with master or the next hls release, when that happens.

**Comment by michaelpj** [comment] 2023-06-12 07:47
I'm going to tentatively mark this as fixed, please reopen if it recurs after the next release.

**Closed by michaelpj** 2023-06-12 07:47 UTC
Labels: type: bug, component: lsp
