### ISSUE TITLE
Failing test with whitespace mismatches for hls-splice-plugin

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#1808] opened 2021-05-07 22:34 UTC
### Your environment

Trying to build hls-splice-plugin-1.0.0.1.

Which OS do you use: Nixos

### Steps to reproduce

I ran the tests.

### Expected behaviour

Tests pass.

### Actual behaviour
```
  TSimpleDecl.hs (golden):      FAIL (111.47s)
    test/Main.hs:87:
    expected: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\r\nfoo = 42\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"
     but got: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\nfoo = 42\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"
  TQQDecl.hs (golden):          FAIL (133.83s)
    test/Main.hs:87:
    expected: "{-# LANGUAGE QuasiQuotes #-}\r\nmodule TQQDecl where\r\nimport QQ (str)\r\n\r\nfoo :: String\r\nfoo = \"foo\"\r\n"
     but got: "{-# LANGUAGE QuasiQuotes #-}\r\nmodule TQQDecl where\r\nimport QQ (str)\r\n\r\nfoo :: String\nfoo = \"foo\"\r\n"
  TTypeKindError.hs (golden):   OK (125.31s)
  TDeclKindError.hs (golden):   FAIL (118.40s)
    test/Main.hs:120:
    expected: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\r\nfoo = 42\r\nbar :: Int\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"
     but got: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\nfoo = 42\nbar :: Int\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"

3 out of 31 tests failed (138.46s)
```

This looks like some issue with unix vs. windows line endings?

**Comment by felixonmars** [comment] 2021-05-10 23:08
I am getting the same errors when building for Arch:

```
  TSimpleDecl.hs (golden):      FAIL (88.82s)
    test/Main.hs:87:
    expected: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\r\nfoo = 42\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"
     but got: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\nfoo = 42\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"
  TQQDecl.hs (golden):          FAIL (102.13s)
    test/Main.hs:87:
    expected: "{-# LANGUAGE QuasiQuotes #-}\r\nmodule TQQDecl where\r\nimport QQ (str)\r\n\r\nfoo :: String\r\nfoo = \"foo\"\r\n"
     but got: "{-# LANGUAGE QuasiQuotes #-}\r\nmodule TQQDecl where\r\nimport QQ (str)\r\n\r\nfoo :: String\nfoo = \"foo\"\r\n"
  TTypeKindError.hs (golden):   OK (99.71s)
  TDeclKindError.hs (golden):   FAIL (93.87s)
    test/Main.hs:120:
    expected: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\r\nfoo = 42\r\nbar :: Int\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"
     but got: "{-# LANGUAGE TemplateHaskell #-}\r\n{-# LANGUAGE QuasiQuotes #-}\r\nmodule TSimpleDecl where\r\nimport Language.Haskell.TH ( mkName, clause, normalB, funD, sigD )\r\n\r\n-- Foo\r\n--  Bar\r\nfoo :: Int\nfoo = 42\nbar :: Int\r\n-- Bar\r\n-- ee\r\n-- dddd\r\n"
```

**Comment by jneira** [comment] 2021-05-11 05:32
Usually tests fail in windows cause the same issue :slightly_smiling_face: , editing the source test cases should fix it, i suppose

**Comment by Ailrun** [comment] 2021-05-11 08:59
It's partially because splice plugin does not use any golden test util, and implement its own pseudo-golden test by itself... (If we use git diff, we can ignore `\r` differences)

**Comment by berberman** [comment] 2021-05-11 09:32
Yeah, eval plugin and tactics plugin have the same problem as well.

And it turns out that files in uploaded tarballs are different from those in our git source tree:
```
$ diff ~/Downloads/hls-splice-plugin-1.0.0.1/test/testdata/TErrorExp.hs.expected ~/haskell-language-server/plugins/hls-splice-plugin/test/testdata/TErrorExp.hs.expected   
1,6c1,6
< {-# LANGUAGE TemplateHaskell #-}
< module TErrorExp where
< import Language.Haskell.TH ( tupE, litE, integerL )
< 
< main :: IO ()
< main = return (42, ())
---
> {-# LANGUAGE TemplateHaskell #-}
> module TErrorExp where
> import Language.Haskell.TH ( tupE, litE, integerL )
> 
> main :: IO ()
> main = return (42, ())
```

@jneira Did you create this sdist on Windows?

**Comment by jneira** [comment] 2021-05-11 09:36
yeah, it seems it could be my fault, maybe cause i have `auto.crlf` enabled (not at my laptop rigt now). 
I will take a look asap

**Comment by maralorn** [comment] 2021-05-11 13:31
> It's partially because splice plugin does not use any golden test util, and implement its own pseudo-golden test by itself... (If we use git diff, we can ignore `\r` differences)

btw. git diff also leads to problems on nixos because it shows differences in file permissions caused by the nix-store. But it’s okay. We can of course disable them …

**Comment by Ailrun** [comment] 2021-05-11 17:08
@maralorn It's now fixed on master (and probably after next version)

**Comment by jneira** [comment] 2021-05-12 17:10
I've checked mye env and:
```
PS D:\hls> git config --get auto.crlf
false
```
and i have the `.editorconfig` plugin installed so it should change crlf by lf on save (although i did not open those test data files iirc)

🤔

**Comment by jneira** [comment] 2021-05-12 17:55
Ok i forced a checkout after fixing the damn `core.autocrlf` and all files has LF now. So i will bump up the plugin to `1.0.0.2` in master, backport the change to `hackage-1.1.0` and upload the tarball again
Sorry for the inconveniences caused by that stupid error 😟

**Comment by felixonmars** [comment] 2021-05-16 15:37
> I've uploaded https://hackage.haskell.org/package/hls-splice-plugin-1.0.0.2 after double checking files have LF.
> 
> Akthough i am gonna use unix `LF` cause i want to be kind with my fellow posix comrades stuck_out_tongue_closed_eyes , tests should be resilient to line endings changes, like other plugins, as suggested by @Ailrun
> 
> @maralorn tests should work now (at least they shouldn't fail due to line endings)

Confirmed that the tests are passing now in Arch. Thanks!

https://github.com/archlinux/svntogit-community/commit/ffc8dbecaebaf7cf5738148a8c043210c3e237bd#diff-37538beb61ff63edebbf735dfcf39e5d732f49183d6beb097169d971875ca422L42

**Closed** 2021-05-16 16:13 UTC
Labels: component: hls-splice-plugin, type: bug, type: distribution, type: testing
