### ISSUE TITLE
Build dynamic executables by default on supported platforms

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#2245] opened 2021-09-27 07:10 UTC
We want A)`git clone .. && cd <dir> && cabal install haskell-language-server` to build a `-dynamic` binary by default on Linux, MacOs and any other supported platforms, excluding Windows, for the reasons outlined in https://github.com/haskell/haskell-language-server/blob/1ba88ab9eca1da29cd4fee7d2084eba4074fbe47/docs/troubleshooting.md#problems-with-dynamic-linking

Similarly, we also want B)`cabal unpack haskell-language-server && cd <dir> && cabal install` to build dynamic executables.

What's the best way to do this? Summarising the discussion at https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/245:

1. A `cabal.project` setting is not a good fit since conditionals are not supported and would not help with B)
2. A conditional `ghc-options: -dynamic` in `haskell-language-server.cabal` doesn't play well with `cabal v2-build` 
3. A `cabal-dynamic.project.local` file would require an extra step and would not help with B) either

**Comment by pepeiborra** [comment] 2021-09-27 07:13
Summoning Cabal experts, @emilypi @phadej any suggestions?

**Comment by jneira** [comment] 2021-09-27 07:16
> A conditional ghc-options: -dynamic in haskell-language-server.cabal doesn't play well with cabal v2-build

hmm could you describe briefly what would be the problem?

**Comment by jneira** [comment] 2021-09-27 07:22
Want to link a closed issue which considered build dinamically prebuilt binaries: #2069
We closed it at that moment

**Comment by pepeiborra** [comment] 2021-09-27 07:58
> > A conditional ghc-options: -dynamic in haskell-language-server.cabal doesn't play well with cabal v2-build
> 
> hmm could you describe briefly what would be the problem?
> 
> ```
> if !os(windows) && !flag(static)
>   ghc-options: -dynamic
> ```
> 
> would be a reasonable way to do it

This doesn't work well for the reasons outlined in https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/245#note_378797

**Comment by pepeiborra** [comment] 2021-09-27 08:00
> Want to link a closed issue which considered build dinamically prebuilt binaries: #2069
> And i dont find it right now but i want to remember someone had problems in linux building using stack and dynamic linking enabled.

Thanks but the linked issue is about distribution, this issue is about building from source.

**Comment by hasufell** [comment] 2021-09-27 08:20
> > > A conditional ghc-options: -dynamic in haskell-language-server.cabal doesn't play well with cabal v2-build
> > 
> > hmm could you describe briefly what would be the problem?
> > 
> > ```
> > if !os(windows) && !flag(static)
> >   ghc-options: -dynamic
> > ```
> > 
> > would be a reasonable way to do it
> 
> This doesn't work well for the reasons outlined in https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/245#note_378797

The isssue I described is orthogonal to where this flag is put, be it cabal file, project file or command line. The problem is that we need to install the plugin libs, which requires `v2-install`, which doesn't play nice with compiling from git, because of overly eager cache hits.

**Comment by jneira** [comment] 2021-12-15 07:39
We took the path of building [fully statically linked binaries for linux](https://github.com/haskell/haskell-language-server/pull/2463) and [set a warning for macos](https://github.com/haskell/haskell-language-server/pull/2470), suggesting building dinamically from source, @pepeiborra do you think could we close this?

**Comment by pepeiborra** [comment] 2021-12-15 07:55
No, I still want cabal install HLS to build a dyn linked binary by default

**Closed** 2022-02-01 13:30 UTC
Labels: type: enhancement, status: needs confirmation, type: distribution
