### ISSUE TITLE
Specifying a number of threads to 1 causes haskell-language-server to get stuck

### ISSUE THREAD

**Issue by jakzale** [haskell/haskell-language-server#1762] opened 2021-04-19 18:40 UTC
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.1.0.0 (GHC: 8.10.2.20201118) (PATH: /nix/store/1l6ajln74mljnqsv91mjwvp7s4mfi3pp-haskell-language-server-exe-haskell-language-server-1.1.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1.1
ghc:		8.10.2.20201118


```
Which OS do you use:
```sh
macOS Big Sur 11.3.2 (M1/Aarch64)
```
Which lsp-client do you use:
```sh
N/A
```
Describe your project (alternative: link to the project):
```sh
A new directory with an empty .hs file.
```

Contents of `hie.yaml`:
```yaml
N/A
```

### Steps to reproduce
1. `mkdir foo`
2. `cd foo`
3. `touch Foo.hs`
4. `haskell-language-server  -j 1`

### Expected behaviour
Typecheck the whole directory

### Actual behaviour
Haskell language server get's stuck:

```
$ haskell-language-server -j 1
haskell-language-server version: 1.1.0.0 (GHC: 8.10.2.20201118) (PATH: /nix/store/1l6ajln74mljnqsv91mjwvp7s4mfi3pp-haskell-language-server-exe-haskell-language-server-1.1.0.0/bin/haskell-language-server)
 ghcide setup tester in /Users/jakub/Developer/foo.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /Users/jakub/Developer/foo
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
^C

$
```

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
haskell-language-server --debug
haskell-language-server version: 1.1.0.0 (GHC: 8.10.2.20201118) (PATH: /nix/store/1l6ajln74mljnqsv91mjwvp7s4mfi3pp-haskell-language-server-exe-haskell-language-server-1.1.0.0/bin/haskell-language-server)
 ghcide setup tester in /Users/jakub/Developer/foo.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /Users/jakub/Developer/foo
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
2021-04-19 20:39:54.642118 [ThreadId 4] DEBUG hls:	Set files of interest to: [(NormalizedFilePath "/Users/jakub/Developer/foo/Foo.hs",OnDisk)]
2021-04-19 20:39:54.646906 [ThreadId 46] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/jakub/Developer/foo/Foo.hs"
2021-04-19 20:39:54.64767 [ThreadId 48] INFO hls:	Consulting the cradle for "Foo.hs"
2021-04-19 20:39:54.647806 [ThreadId 48] WARNING hls:	No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for Foo.hs.
 Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
Output from setting up the cradle Cradle {cradleRootDir = "/Users/jakub/Developer/foo", cradleOptsProg = CradleAction: Default}
2021-04-19 20:39:54.658087 [ThreadId 48] DEBUG hls:	Session loading result: Right (ComponentOptions {componentOptions = [], componentRoot = "/Users/jakub/Developer/foo", componentDependencies = []},"/nix/store/x1rpdjyf4ljhi2xis8m0rh12bcg2n0dh-ghc-shell-for-packages-ghc-8.10.2.20201118-env/lib/ghc-8.10.2.20201118")
2021-04-19 20:39:55.011132 [ThreadId 48] INFO hls:	Using interface files cache dir: /Users/jakub/.cache/ghcide/main-da39a3ee5e6b4b0d3255bfef95601890afd80709
2021-04-19 20:39:55.011555 [ThreadId 48] INFO hls:	Making new HscEnv[main]
2021-04-19 20:39:55.033283 [ThreadId 48] DEBUG hls:	New Component Cache HscEnvEq: (([],Just HscEnvEq 5),fromList [])
2021-04-19 20:39:55.033926 [ThreadId 48] DEBUG hls:	Known files updated: fromList [(TargetFile NormalizedFilePath "/Users/jakub/Developer/foo/Foo.hs",fromList ["/Users/jakub/Developer/foo/Foo.hs"])]
2021-04-19 20:39:55.034892 [ThreadId 18] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
2021-04-19 20:39:55.034963 [ThreadId 48] DEBUG hls:	Restarting build session (aborting the previous one took 0.00s)
2021-04-19 20:39:55.036528 [ThreadId 92] DEBUG hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/jakub/Developer/foo/Foo.hs"
2021-04-19 20:39:55.174975 [ThreadId 141] INFO hls:	finish: User TypeCheck (took 0.14s)
2021-04-19 20:39:55.182448 [ThreadId 150] INFO hls:	finish: GetHie (took 0.01s)

2021-04-19 20:39:55.198568 [ThreadId 155] INFO hls:	finish: GenerateCore (took 0.02s)
Completed (1 file worked, 0 files failed)

```
</details>

**Comment by jneira** [comment] 2021-04-19 19:38
@jakzale hi, thanks for your detailed bug report, i think this is somewhat a duplicate of #727, under a different way to reproduce.
I am gonna close it this one if you dont mind, feel free to reopen if you think it worths to keep open.

**Closed by jneira** 2021-04-19 19:38 UTC
Labels: type: bug
