### ISSUE TITLE
[GHC 9.0] No need to parse without Haddocks

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1892] opened 2021-06-05 08:25 UTC
Haddock markup parse errors are flagged as warnings in 9.0 (no longer errors) so there's no longer a need to parse twice

**Comment by yoshitsugu** [comment] 2021-11-09 12:45
@pepeiborra 
I'm now taking a look at this :eyes:  but what is the expected behavior? 
In the current test case, it looks like no output is expected above GHC90
https://github.com/haskell/haskell-language-server/blob/master/ghcide/test/exe/Main.hs#L562-L564

**Comment by jneira** [comment] 2021-11-09 12:49
> I'm now taking a look at this but what is the expected behavior?

I think the expected behaviour is the same but we can remove the double parsing *for ghc >= 9.0.1*, as haddock will not throw error for those ghc versions

here: 

https://github.com/haskell/haskell-language-server/blob/229faac11a517efdd75f7d23afce9daa6345259e/ghcide/src/Development/IDE/Core/Rules.hs#L893-L900

and here

https://github.com/haskell/haskell-language-server/blob/229faac11a517efdd75f7d23afce9daa6345259e/ghcide/src/Development/IDE/Core/Rules.hs#L197-L250

**Comment by jneira** [comment] 2021-11-09 12:50
```haskell
liftIO $ (fmap.fmap.fmap.fmap)
```` 

wonderful :sweat_smile:

**Comment by konn** [comment] 2021-11-09 12:56
> I think the expected behaviour is the same but we can remove the double parsing _for ghc >= 9.0.1_, as haddock will not throw error for those ghc versions

Then, perhaps also adding a regression test with erroneous Haddock comment(s) would make sense to ensure that HLS doesn't suffer from such malformed Haddock comments.

**Comment by jneira** [comment] 2021-11-09 13:02
> Then, perhaps also adding a regression test with erroneous Haddock comment(s) would make sense to ensure that HLS doesn't suffer from such malformed Haddock comments.

Hmm i think the linked test already does it: the haddock error is converted in a warning. So if it is reported incorrectly as an error the test would fail afaiu.

**Comment by yoshitsugu** [comment] 2021-11-09 13:08
@jneira @konn thanks for quick reply 😄 i'll try this.

**Comment by jneira** [comment] 2021-11-09 13:23
Thinking in this twice it is unfortunate that we are losing the haddock diagnostics for ghc >= 9.0as maybe some users find them useful, before they hit the error when building docs.
Maybe we should restore those diagnostics, but not in ghcide, where are not necessary but in the hls-haddock-plugin itslef: https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-haddock-comments-plugin/src/Ide/Plugin/HaddockComments.hs

**Comment by yoshitsugu** [comment] 2021-11-18 04:43
We can close this? @pepeiborra @jneira

**Comment by jneira** [comment] 2021-11-18 06:42
Yeah! many thanks for fixing it

**Closed by jneira** 2021-11-18 06:42 UTC
Labels: type: enhancement, component: ghcide, type: refactor, beginner friendly, ghc-9
