### ISSUE TITLE
Unable to get code completion or other lsp features - stuck type checking the files

### ISSUE THREAD

**Issue by F15Ky** [haskell/haskell-language-server#1624] opened 2021-03-26 07:54 UTC
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:
```
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.10.4
```
Which lsp-client do you use:
Doom Emacs
Describe your project (alternative: link to the project):
Contents of cabal file:
```
cabal-version:       >=1.10
name:                Everything-Manager
version:             0.1.0.0
synopsis:            System used to optimize the efficiency of achieving goals.
bug-reports:         https://github.com/fairy-tale-agi-solutions/Everything-Manager/issues
license:             MIT
license-file:        LICENSE
author:              Răzvan Flavius Panda
maintainer:          razvan.panda@gmail.com
category:            Productivity
build-type:          Simple
extra-source-files:  CHANGELOG.md, README.md

executable Everything-Manager
  main-is:             Main.hs
  -- other-modules:       Lib.EverythingManager
  build-depends:       base,
                       containers,
                       generic-lens,
                       lens,
                       text,
                       hedgehog,
                       postgresql-simple,
                       product-profunctors,
                       opaleye,
                       miso,
                       turtle
  default-language:    Haskell2010
  default-extensions:  DataKinds,
                       DeriveGeneric,
                       DuplicateRecordFields,
                       FlexibleContexts,
                       OverloadedStrings,
                       TypeApplications,
                       Arrows,
                       RecordWildCards

library Everything-Manager-Library
  -- other-modules:       Lib.EverythingManager
  build-depends:       base,
                       containers,
                       generic-lens,
                       lens,
                       text,
                       hedgehog,
                       postgresql-simple,
                       product-profunctors,
                       opaleye,
                       miso,
                       turtle

  default-language:    Haskell2010
  default-extensions:  DataKinds,
                       DeriveGeneric,
                       DuplicateRecordFields,
                       FlexibleContexts,
                                            
```

### Steps to reproduce
After setting up haskell language server and lsp-haskell for emacs, I still get no completion.

### Expected behaviour
I expect code completion as well as other lsp features.

### Actual behaviour
No code completion is given.

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /home/ben/.local/bin/haskell-language-server) (GIT hash: 8dbeae160c526672958096edee48aa97ef9f5359)
ghcide setup tester in /home/ben/Documents/haskell/Everything-Manager.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /home/ben/Documents/haskell/Everything-Manager
Found 6 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
2021-03-26 17:52:59.383441561 [ThreadId 4] DEBUG hls:	Set files of interest to: [(NormalizedFilePath "/home/ben/Documents/haskell/Everything-Manager/Setup.hs",OnDisk),(NormalizedFilePath "/home/ben/Documents/haskell/Everything-Manager/Lib/EverythingManager.hs",OnDisk),(NormalizedFilePath "/home/ben/Documents/haskell/Everything-Manager/install.hs",OnDisk),(NormalizedFilePath "/home/ben/Documents/haskell/Everything-Manager/test/TestEverythingManager.hs",OnDisk),(NormalizedFilePath "/home/ben/Documents/haskell/Everything-Manager/Main.hs",OnDisk),(NormalizedFilePath "/home/ben/Documents/haskell/Everything-Manager/Lib/Connection.hs",OnDisk)]

</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
https://gist.github.com/F15Ky/69e242397f60575147460afe9262c7f8
</summary>

```
<paste your logs here>
```
</details>

**Comment by F15Ky** [comment] 2021-03-29 02:36
This is what I get when running haskell-language-server in the projects top directory:
```
haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /home/ben/.local/bin/haskell-language-server) (GIT hash: 8dbeae160c526672958096edee48aa97ef9f5359)
ghcide setup tester in /home/ben/Documents/haskell/hlstest.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /home/ben/Documents/haskell/hlstest
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
```

When I run it on a different system the output continues past that.

**Comment by jneira** [comment] 2021-03-29 21:30
Hi, thanks for the bug report, the output is strange, the process find one file to process in the test but it does not get typechecked.
The process get stuck in the 4th step or it exits without no further output?
Also, have you tried your editor with other lsp-server or hls with other editor?

**Comment by F15Ky** [comment] 2021-03-30 02:20
The process get stuck on the 4th step with no more output. 

ghcide gives the same output as haskell language server. 

I do not get code completion after installing language-haskell and atom-ide-ui on Atom.

**Comment by michaelpj** [comment] 2021-03-31 17:52
Ah, perhaps https://github.com/haskell/haskell-language-server/issues/727. Can we check the number of capabilities and give an error if it's 1?

**Comment by jneira** [comment] 2021-04-01 12:59
Ok i am gonna close it as duplicate of #727, i've copied the comment with the last suggestion there

**Closed by jneira** 2021-04-01 12:59 UTC
Labels: status: needs attention, type: bug, type: setup
