### ISSUE TITLE
CI for 9.0.1 is broken due to missing upstream commit

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#2016] opened 2021-07-13 20:32 UTC
It appears CI for 9.0.1 is broken. At least four PRs currently in the queue are broken in 9.0.1 with the following error:

```
Cloning into '/home/runner/work/haskell-language-server/haskell-language-server/dist-newstyle/src/operation_-2cf41f8926150174'...
fatal: reference is not a tree: 0e062895678f49fd673ae493371262cfb8c5ab56
```

Digging in, that commit appears to be referenced here:

https://github.com/haskell/haskell-language-server/blob/a0f6f5fe9a610a11aeda9567873da5e970cf42b2/stack-9.0.1.yaml#L98-L100

and comes with a helpful PR reference:

https://github.com/HeinrichApfelmus/operational/pull/26

which is now merged. Looking at the commit in question:

https://github.com/berberman/operational/commit/0e062895678f49fd673ae493371262cfb8c5ab56

github responds with 

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

which sounds scary and I'd bet is why CI is failing.

@berberman your name is attached to the commit in question, mind investigating?

**Comment by jneira** [comment] 2021-07-13 21:01
The problem is `the branch in berberman's repo was deleted after merge so the commit does not exist anymore. We have to change the commit to point to master, as the pr was merged into

**Comment by berberman** [comment] 2021-07-14 01:07
Sorry, my bad, I should've kept my branch even if the PR was merged.

**Comment by isovector** [comment] 2021-07-14 01:08
This is the sort of thing nobody would ever think about :) No worries at all!

**Closed** 2021-07-14 04:22 UTC
Labels: build, status: needs attention, type: bug
