### ISSUE TITLE
new code action: add binding

### ISSUE THREAD

**Issue by alok** [haskell/haskell-language-server#1917] opened 2021-06-13 06:07 UTC
i often write type sigs first. a code action to autogenerate a body would be nice. something like

``` f :: a -> b
-- for the body, code actions adds something like 'f a = _' 
```

**Comment by berberman** [comment] 2021-06-13 06:13
Duplicate of #458

**Comment by jneira** [comment] 2021-06-14 05:33
@alok thanks for your feature request, that would be a nice addition for sure. You can follow its progress in the linked previous feature request: #458. Feel free to reopen if you think the feature described there doesnt match yours.

**Closed by jneira** 2021-06-14 05:33 UTC
