### ISSUE TITLE
& operator omitted on lint name end

### ISSUE THREAD

**Issue by schuelermine** [haskell/haskell-language-server#2909] opened 2022-05-16 17:20 UTC
### Your environment

Which OS do you use:

NixOS 22.05.20220514.43ff6cb (Quokka)

### Steps to reproduce

Write `(& foo)`

### Expected behaviour

Clicking “quick fix” shows “Apply hint "Redundant &"” or so

### Actual behaviour

It shows “Apply hint "Redundant "”

### Screenshot

![Screenshot from 2022-05-16 19-17-47](https://user-images.githubusercontent.com/48802534/168648219-3c567ba0-e1df-479c-b821-eec321e4e9ce.png)

**Comment by fendor** [comment] 2022-05-16 17:58
Thank you for the bug report! Moving to the main repo, as it is likely to be either a render error in LSP in general or we need to escape the hints in HLS correctly.

**Comment by July541** [comment] 2022-05-17 13:44
I can't reproduce it, can you please supply what haskell-language-server are you using and what lsp-client are you using?

https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#troubleshooting

<img width="438" alt="image" src="https://user-images.githubusercontent.com/16057632/168824383-12051e74-048a-4573-8285-4a61c32d09a0.png">

**Comment by schuelermine** [comment] 2022-05-17 14:46
haskell-language-server version: 1.7.0.0 (GHC: 9.0.2) (PATH: /nix/store/xn5jznvfp0i4mapvppzszdlskrb174yl-haskell-language-server-1.7.0.0/bin/haskell-language-server)

**Comment by July541** [comment] 2022-05-18 15:17
I tried hls-1.7.0.0 on ghc-9.0.2, still can't repro this. Maybe someone can repro this.

Or can you try other fonts? I doubt it is something about fonts...

**Comment by drsooch** [comment] 2022-05-22 02:56
I was unable to reproduce this either

**Comment by michaelpj** [comment] 2024-01-16 17:55
Nobody seems to be able to reproduce, so closing

**Closed by michaelpj** 2024-01-16 17:55 UTC
Labels: type: bug, status: needs info, component: hls-hlint-plugin
