### ISSUE TITLE
Feature Request: Show "defined in" for packages as well as modules 

### ISSUE THREAD

**Issue by DavidEichmann** [haskell/haskell-language-server#1615] opened 2021-03-24 11:42 UTC
At the moment, hovering over a binding shows a "Defined in <module>". This is great! It would also be great to see the package e.g. "Defined in <package> <module>". It would also be great if we could see the package when hovering over an import e.g. over `import A.B.C` so that I can easily know what package `A.B.C` is defined in.

**Comment by berberman** [comment] 2021-03-24 11:49
Duplicate of #686

**Comment by jneira** [comment] 2021-03-24 19:42
I've added a comment in the original issue mentioning the idea of see the package on imports hover too.
So i think we can close it in favour of #686

**Closed by jneira** 2021-03-24 19:42 UTC
Labels: component: ghcide, type: enhancement
