### ISSUE TITLE
Cannot get automatic case splitting to work

### ISSUE THREAD

**Issue by NiekPas** [haskell/haskell-language-server#3496] opened 2023-02-17 13:26 UTC
I'm a happy user of HLS, but for some reason cannot get [automatic case splitting](https://haskellwingman.dev/case-split.gif) to work in any file or project. 

## Your environment 

**Which OS do you use?** 
MacOS Ventura 13.1

**Which version of GHC do you use and how did you install it?** 
9.4.4 from GHCUP

**Which LSP client (editor/plugin) do you use?**
VS Code with the Haskell extension

**Which version of HLS do you use and how did you install it?** 
Version 1.9.1.0 aarch64 ghc-9.4.4 from GHCUP

**Have you configured HLS in any way (especially: a `hie.yaml` file)?** 
No

## What's wrong?

Take the following code example:

```
data FuzzyBool = True | HalfTrue | False

convertFuzzyBool :: FuzzyBool -> Int
convertFuzzyBool fb = _
```

The only quick fixes suggested at `_` are hole fits. Case splitting is not provided.

**Comment by fendor** [comment] 2023-02-18 09:29
Iirc, the plugin wingman is incompatible with GHC 9.4.4, see https://github.com/haskell/haskell-language-server/blob/master/docs/support/plugin-support.md (it is called hls-tactics-plugin)

**Comment by NiekPas** [comment] 2023-02-19 22:09
Thanks! I think the docs are slightly confusing here: [hls-tactics-plugin on Hackage](https://hackage.haskell.org/package/hls-tactics-plugin) prompts you to go to the HLS readme on github, which, when you follow [Supported GHC Versions](https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html) lists "full support" for GHC 9.4.4.

**Comment by fendor** [comment] 2023-02-20 10:59
Indeed, the issue is just what "full support" means. A bit higher, it specifies that it means "most tier 2 plugins work", and then you'd have to check the plugin support.
It is a bit difficult to provide more accurate information, while not over-bearing readers with info.

**Comment by fendor** [comment] 2023-02-20 10:59
Closing, for now, but feel free to reopen if this resolve isnt to your satisfaction.

**Closed by fendor** 2023-02-20 10:59 UTC
Labels: type: support, status: needs triage

**Comment by NiekPas** [comment] 2023-02-22 11:05
Yeah, I'd argue that that is not what 'full support' would mean to most (lay) readers, and that the terminology should be rethought, but that is a seperate issue.
