### ISSUE TITLE
Import Regression: Wrong Import Placement on first Import

### ISSUE THREAD

**Issue by emilypi** [haskell/haskell-language-server#2100] opened 2021-08-16 17:48 UTC
Here's a weird one: first imports are inserted in wrong place. Unsure why. 

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:
```sh
askell-language-server version: 1.3.0.0 (GHC: 8.10.4) (PATH: /Users/emilypi/.ghcup/bin/haskell-language-server-wrapper-1.3.0) (GIT hash: e7c5e90b6df5dff2760d76169eddaea3bdd6a831)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.10.4
```
Which OS do you use:
MacOS Big Sure

Which lsp-client do you use:

Emacs

Describe your project (alternative: link to the project):
*.cabal files, cabal.project

Contents of `hie.yaml`:
```yaml
cradle:
  cabal:
    - path: "src"
      component: "lib:order"

    - path: "test"
      component: "order:test:doctests"
```

### Steps to reproduce

1. Make a first import with functions defined (along with comments)
<img width="1219" alt="Screen Shot 2021-08-16 at 11 44 07 AM" src="https://user-images.githubusercontent.com/10459342/129606779-e6fe60dd-216b-4ffb-80cd-b51bc381cf75.png">

2. Import goes in wrong place.
<img width="1102" alt="Screen Shot 2021-08-16 at 11 44 15 AM" src="https://user-images.githubusercontent.com/10459342/129606797-db4a0c5e-c720-4498-a597-d5dc41abf703.png">

3. If importing another thing, imports are added below first import 

<img width="1205" alt="Screen Shot 2021-08-16 at 11 46 12 AM" src="https://user-images.githubusercontent.com/10459342/129606894-8aef89db-b051-46f3-95c3-9193ec77d104.png">

4. However, when physically moved, to the right spot, imports work as expected. 
<img width="1207" alt="Screen Shot 2021-08-16 at 11 44 40 AM" src="https://user-images.githubusercontent.com/10459342/129606815-7766e60f-d31b-4053-b900-5482f5022669.png">
<img width="1073" alt="Screen Shot 2021-08-16 at 11 44 46 AM" src="https://user-images.githubusercontent.com/10459342/129606823-2e57b6ab-e7aa-4a2b-88fb-7e1bdf158ad1.png">

### Expected behaviour

Imports should be inserted in correct area of the module. 

### Actual behaviour
The first import is inserted above the first signicant decl, regardless of comments.

**Comment by jneira** [comment] 2021-08-16 19:10
OMG this is the neverending history. A regression test is absolutely needed as first step.

**Comment by nini-faroux** [comment] 2021-08-16 20:08
sure! I can have a look tomorrow

**Comment by nini-faroux** [comment] 2021-08-17 21:02
hi, so I played around a little with this just now and it seems the issue is whenever the first (non-empty) line after the 'module ... where' is a comment, if you put anything above the comment the 'import' seems to be added above that correctly, as an example, with a data declaration above the comment the import gets added above that: 

module Test 
( SomeData(..)
) where

import Data.Monoid -- newly added
data Something = Something

-- | some comment
class Semigroup a => SomeData a
instance SomeData All

The problem seems to be with this function:

https://github.com/haskell/haskell-language-server/blob/a5d70ee2cd98f0e8396d2ddb94123d6d6759eae8/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L1291

Where there are two cases, when the import list is empty, it finds the position from 'hsmodDecls', and if it matches this case and the first line is a comment, we have the problem with the import being added under the comment.

The second case is when there are imports, so the import list isn't empty, in which case it finds the position from 'hsmodImports', and will add the suggested import under the current last import in the file, which works fine once the existing imports are in the correct position, as mentioned already.

So I'd be happy to try to make a fix for this some evening later in the week if that suits, but it would be good to add a number of tests as well, so I was wondering where's the best place to add them? There's a 'test' folder in '/ghcide/...', but I didn't see any tests for this functionality there, and there's two import plugins (refine and explicit) but I don't think either are particularly related to this issue. Just to make sure I add them in a sensible place. 

Thanks!

**Comment by jneira** [comment] 2021-08-17 21:35
@nini-faroux many thanks for the head up, i think the place for such tests could be 

https://github.com/haskell/haskell-language-server/blob/a5d70ee2cd98f0e8396d2ddb94123d6d6759eae8/ghcide/test/exe/Main.hs#L1579

**Comment by nini-faroux** [comment] 2021-08-17 21:52
that's great, thanks @jneira

**Closed** 2021-09-04 22:36 UTC
Labels: type: bug, component: imports plugin, status: regression test needed
