### ISSUE TITLE
Weird Haddock sends HLS crashing

### ISSUE THREAD

**Issue by Ptival** [haskell/haskell-language-server#1318] opened 2021-02-06 21:03 UTC
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.9.0.0 (GHC: 8.10.3) (PATH: /nix/store/hgbinji81xvnjqibncbj0fi04l1hy570-haskell-language-server-exe-haskell-language-server-0.9.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		Not found
ghc:		8.10.3
```

Which lsp-client do you use: VSCode

Describe your project (alternative: link to the project):
https://github.com/GaloisInc/crucible/

Contents of `hie.yaml`:
https://github.com/Ptival/config/blob/master/projects/crucible/hie.yaml

### Steps to reproduce
Introduce the following snippet in some otherwise working code:
```haskell
f ::
  a
    {- ^ test
    -} ->
  a
f x = x
```

### Expected behaviour
Things work.

### Actual behaviour
HLS crashes at some point, then gives up after 5 crashes.
Note that the command-line tool does not crash when pointed to that specific file or project, which made this very hard to debug.

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
Let me know if you actually need it... it did not seem useful, and it does not crash in the terminal.
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
2021-02-06 13:00:46.819327 [ThreadId 25] - Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-5991089978266373575) "file:///Users/val/galois/crucible"], clientSettings = hashed Nothing}
2021-02-06 13:00:46.821188 [ThreadId 25] - Configuration changed: Object (fromList [("haskell",Object (fromList [("logFile",String "/tmp/hls.log"),("updateBehavior",String "prompt"),("hlintOn",Bool True),("formatOnImportOn",Bool True),("indentationRules",Object (fromList [("enabled",Bool True)])),("liquidOn",Bool False),("languageServerVariant",String "haskell-language-server"),("serverExecutablePath",String "/nix/store/hgbinji81xvnjqibncbj0fi04l1hy570-haskell-language-server-exe-haskell-language-server-0.9.0.0/bin/haskell-language-server"),("diagnosticsOnChange",Bool True),("completionSnippetsOn",Bool True),("maxNumberOfProblems",Number 100.0),("formattingProvider",String "ormolu"),("trace",Object (fromList [("server",String "off")]))]))])
2021-02-06 13:00:46.824546 [ThreadId 25] - Opened text document: file:///Users/val/galois/crucible/crux/src/Crux.hs
2021-02-06 13:00:46.825696 [ThreadId 109] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:00:46.826161 [ThreadId 113] - Consulting the cradle for "crux/src/Crux.hs"
2021-02-06 13:01:04.007451 [ThreadId 113] - Using interface files cache dir: ghcide
2021-02-06 13:01:04.007545 [ThreadId 113] - Making new HscEnv[crux-0.4-inplace]
2021-02-06 13:01:04.059237 [ThreadId 281] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:01:04.062012 [ThreadId 286] - finish: getSession (took 0.00s)
2021-02-06 13:01:04.062059 [ThreadId 283] - finish: ModuleName.ghcSession (took 0.00s)
2021-02-06 13:01:04.093812 [ThreadId 283] - finish: importLens (took 0.04s)
2021-02-06 13:01:04.093796 [ThreadId 560] - finish: Outline (took 0.04s)
2021-02-06 13:01:04.093825 [ThreadId 559] - finish: ModuleName.GetParsedModule (took 0.03s)
2021-02-06 13:01:04.093772 [ThreadId 562] - finish: addPragma (took 0.04s)
2021-02-06 13:01:04.09385 [ThreadId 565] - finish: CodeAction (took 0.04s)
2021-02-06 13:01:04.093886 [ThreadId 569] - finish: splice.codeAction.GitHieAst (took 0.04s)
2021-02-06 13:01:04.093907 [ThreadId 567] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.04s)
2021-02-06 13:01:04.757393 [ThreadId 824] - finish: retrie (took 0.70s)
2021-02-06 13:01:04.757383 [ThreadId 823] - finish: codeLens (took 0.70s)
2021-02-06 13:01:04.75815 [ThreadId 830] - finish:  (took 0.70s)
2021-02-06 13:01:04.771374 [ThreadId 833] - finish: tactic (took 0.71s)
2021-02-06 13:01:04.77162 [ThreadId 838] - finish: tactic (took 0.00s)
2021-02-06 13:01:04.771997 [ThreadId 839] - finish: tactic (took 0.00s)
2021-02-06 13:01:04.839507 [ThreadId 842] - finish: CodeAction:PackageExports (took 0.75s)
2021-02-06 13:01:05.203388 [ThreadId 868] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.00s)
2021-02-06 13:01:05.203379 [ThreadId 866] - finish: CodeAction (took 0.00s)
2021-02-06 13:01:05.203448 [ThreadId 870] - finish: addPragma (took 0.00s)
2021-02-06 13:01:05.203458 [ThreadId 872] - finish: retrie (took 0.00s)
2021-02-06 13:01:05.203525 [ThreadId 874] - finish: importLens (took 0.00s)
2021-02-06 13:01:05.203522 [ThreadId 878] - finish: splice.codeAction.GitHieAst (took 0.00s)
2021-02-06 13:01:05.203549 [ThreadId 876] - finish: tactic (took 0.00s)
2021-02-06 13:01:05.203615 [ThreadId 880] - finish: CodeAction:PackageExports (took 0.00s)
2021-02-06 13:01:05.203639 [ThreadId 882] - finish: tactic (took 0.00s)
2021-02-06 13:01:05.203757 [ThreadId 884] - finish: tactic (took 0.00s)
2021-02-06 13:01:05.942526 [ThreadId 25] - Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-5991089978266373575) "file:///Users/val/galois/crucible"], clientSettings = hashed Nothing}
2021-02-06 13:01:05.945183 [ThreadId 25] - Configuration changed: Object (fromList [("haskell",Object (fromList [("logFile",String "/tmp/hls.log"),("updateBehavior",String "prompt"),("hlintOn",Bool True),("formatOnImportOn",Bool True),("indentationRules",Object (fromList [("enabled",Bool True)])),("liquidOn",Bool False),("languageServerVariant",String "haskell-language-server"),("serverExecutablePath",String "/nix/store/hgbinji81xvnjqibncbj0fi04l1hy570-haskell-language-server-exe-haskell-language-server-0.9.0.0/bin/haskell-language-server"),("diagnosticsOnChange",Bool True),("completionSnippetsOn",Bool True),("maxNumberOfProblems",Number 100.0),("formattingProvider",String "ormolu"),("trace",Object (fromList [("server",String "off")]))]))])
2021-02-06 13:01:05.946621 [ThreadId 25] - Opened text document: file:///Users/val/galois/crucible/crux/src/Crux.hs
2021-02-06 13:01:05.947301 [ThreadId 109] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:01:05.948073 [ThreadId 113] - Consulting the cradle for "crux/src/Crux.hs"
2021-02-06 13:01:22.512506 [ThreadId 113] - Using interface files cache dir: ghcide
2021-02-06 13:01:22.513481 [ThreadId 113] - Making new HscEnv[crux-0.4-inplace]
2021-02-06 13:01:22.597151 [ThreadId 253] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:01:22.598488 [ThreadId 250] - finish: ModuleName.ghcSession (took 0.01s)
2021-02-06 13:01:22.598524 [ThreadId 247] - finish: getSession (took 0.01s)
2021-02-06 13:01:22.660624 [ThreadId 242] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.07s)
2021-02-06 13:01:22.66399 [ThreadId 246] - finish: CodeAction (took 0.07s)
2021-02-06 13:01:22.664086 [ThreadId 252] - finish: splice.codeAction.GitHieAst (took 0.07s)
2021-02-06 13:01:22.664196 [ThreadId 246] - finish: ModuleName.GetParsedModule (took 0.06s)
2021-02-06 13:01:22.664542 [ThreadId 246] - finish: addPragma (took 0.07s)
2021-02-06 13:01:22.664728 [ThreadId 249] - finish: importLens (took 0.07s)
2021-02-06 13:01:22.66483 [ThreadId 246] - finish: Outline (took 0.07s)
2021-02-06 13:01:23.797904 [ThreadId 751] - finish: codeLens (took 1.21s)
2021-02-06 13:01:23.798044 [ThreadId 750] - finish: retrie (took 1.21s)
2021-02-06 13:01:23.798834 [ThreadId 756] - finish:  (took 1.21s)
2021-02-06 13:01:23.81893 [ThreadId 760] - finish: tactic (took 1.23s)
2021-02-06 13:01:23.819228 [ThreadId 765] - finish: tactic (took 0.00s)
2021-02-06 13:01:23.81934 [ThreadId 766] - finish: tactic (took 0.00s)
2021-02-06 13:01:23.872576 [ThreadId 769] - finish: CodeAction:PackageExports (took 1.21s)
2021-02-06 13:01:24.058192 [ThreadId 792] - finish: CodeAction (took 0.00s)
2021-02-06 13:01:24.058202 [ThreadId 794] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.00s)
2021-02-06 13:01:24.058279 [ThreadId 796] - finish: addPragma (took 0.00s)
2021-02-06 13:01:24.058347 [ThreadId 800] - finish: importLens (took 0.00s)
2021-02-06 13:01:24.058305 [ThreadId 798] - finish: splice.codeAction.GitHieAst (took 0.00s)
2021-02-06 13:01:24.058402 [ThreadId 802] - finish: retrie (took 0.00s)
2021-02-06 13:01:24.058444 [ThreadId 804] - finish: tactic (took 0.00s)
2021-02-06 13:01:24.058476 [ThreadId 806] - finish: CodeAction:PackageExports (took 0.00s)
2021-02-06 13:01:24.058513 [ThreadId 808] - finish: tactic (took 0.00s)
2021-02-06 13:01:24.058559 [ThreadId 810] - finish: tactic (took 0.00s)
2021-02-06 13:01:25.863189 [ThreadId 25] - Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-5991089978266373575) "file:///Users/val/galois/crucible"], clientSettings = hashed Nothing}
2021-02-06 13:01:25.866701 [ThreadId 25] - Configuration changed: Object (fromList [("haskell",Object (fromList [("logFile",String "/tmp/hls.log"),("updateBehavior",String "prompt"),("hlintOn",Bool True),("formatOnImportOn",Bool True),("indentationRules",Object (fromList [("enabled",Bool True)])),("liquidOn",Bool False),("languageServerVariant",String "haskell-language-server"),("serverExecutablePath",String "/nix/store/hgbinji81xvnjqibncbj0fi04l1hy570-haskell-language-server-exe-haskell-language-server-0.9.0.0/bin/haskell-language-server"),("diagnosticsOnChange",Bool True),("completionSnippetsOn",Bool True),("maxNumberOfProblems",Number 100.0),("formattingProvider",String "ormolu"),("trace",Object (fromList [("server",String "off")]))]))])
2021-02-06 13:01:25.870948 [ThreadId 25] - Opened text document: file:///Users/val/galois/crucible/crux/src/Crux.hs
2021-02-06 13:01:25.871915 [ThreadId 109] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:01:25.872685 [ThreadId 114] - Consulting the cradle for "crux/src/Crux.hs"
2021-02-06 13:01:42.305709 [ThreadId 114] - Using interface files cache dir: ghcide
2021-02-06 13:01:42.3061 [ThreadId 114] - Making new HscEnv[crux-0.4-inplace]
2021-02-06 13:01:42.396459 [ThreadId 235] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:01:42.407722 [ThreadId 270] - finish: ModuleName.ghcSession (took 0.01s)
2021-02-06 13:01:42.407917 [ThreadId 270] - finish: getSession (took 0.01s)
2021-02-06 13:01:42.490538 [ThreadId 324] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.10s)
2021-02-06 13:01:42.493665 [ThreadId 280] - finish: Outline (took 0.10s)
2021-02-06 13:01:42.493747 [ThreadId 278] - finish: CodeAction (took 0.10s)
2021-02-06 13:01:42.493969 [ThreadId 274] - finish: addPragma (took 0.10s)
2021-02-06 13:01:42.494082 [ThreadId 278] - finish: splice.codeAction.GitHieAst (took 0.10s)
2021-02-06 13:01:42.49418 [ThreadId 280] - finish: importLens (took 0.10s)
2021-02-06 13:01:42.49421 [ThreadId 274] - finish: ModuleName.GetParsedModule (took 0.09s)
2021-02-06 13:01:43.241171 [ThreadId 778] - finish: codeLens (took 0.85s)
2021-02-06 13:01:43.241242 [ThreadId 777] - finish: retrie (took 0.85s)
2021-02-06 13:01:43.241824 [ThreadId 784] - finish:  (took 0.85s)
2021-02-06 13:01:43.254171 [ThreadId 787] - finish: tactic (took 0.86s)
2021-02-06 13:01:43.254426 [ThreadId 792] - finish: tactic (took 0.00s)
2021-02-06 13:01:43.254559 [ThreadId 793] - finish: tactic (took 0.00s)
2021-02-06 13:01:43.312358 [ThreadId 796] - finish: CodeAction:PackageExports (took 0.82s)
2021-02-06 13:01:43.712515 [ThreadId 820] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.00s)
2021-02-06 13:01:43.712563 [ThreadId 822] - finish: CodeAction (took 0.00s)
2021-02-06 13:01:43.7126 [ThreadId 824] - finish: addPragma (took 0.00s)
2021-02-06 13:01:43.7127 [ThreadId 830] - finish: tactic (took 0.00s)
2021-02-06 13:01:43.712746 [ThreadId 826] - finish: retrie (took 0.00s)
2021-02-06 13:01:43.712853 [ThreadId 832] - finish: importLens (took 0.00s)
2021-02-06 13:01:43.712966 [ThreadId 828] - finish: splice.codeAction.GitHieAst (took 0.00s)
2021-02-06 13:01:43.712986 [ThreadId 834] - finish: CodeAction:PackageExports (took 0.00s)
2021-02-06 13:01:43.713125 [ThreadId 838] - finish: tactic (took 0.00s)
2021-02-06 13:01:43.713062 [ThreadId 836] - finish: tactic (took 0.00s)
2021-02-06 13:01:44.843705 [ThreadId 25] - Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-5991089978266373575) "file:///Users/val/galois/crucible"], clientSettings = hashed Nothing}
2021-02-06 13:01:44.846847 [ThreadId 25] - Configuration changed: Object (fromList [("haskell",Object (fromList [("logFile",String "/tmp/hls.log"),("updateBehavior",String "prompt"),("hlintOn",Bool True),("formatOnImportOn",Bool True),("indentationRules",Object (fromList [("enabled",Bool True)])),("liquidOn",Bool False),("languageServerVariant",String "haskell-language-server"),("serverExecutablePath",String "/nix/store/hgbinji81xvnjqibncbj0fi04l1hy570-haskell-language-server-exe-haskell-language-server-0.9.0.0/bin/haskell-language-server"),("diagnosticsOnChange",Bool True),("completionSnippetsOn",Bool True),("maxNumberOfProblems",Number 100.0),("formattingProvider",String "ormolu"),("trace",Object (fromList [("server",String "off")]))]))])
2021-02-06 13:01:44.851295 [ThreadId 25] - Opened text document: file:///Users/val/galois/crucible/crux/src/Crux.hs
2021-02-06 13:01:44.852802 [ThreadId 108] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:01:44.854512 [ThreadId 113] - Consulting the cradle for "crux/src/Crux.hs"
2021-02-06 13:02:02.020966 [ThreadId 113] - Using interface files cache dir: ghcide
2021-02-06 13:02:02.021809 [ThreadId 113] - Making new HscEnv[crux-0.4-inplace]
2021-02-06 13:02:02.111436 [ThreadId 247] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:02:02.114251 [ThreadId 246] - finish: ModuleName.ghcSession (took 0.01s)
2021-02-06 13:02:02.114258 [ThreadId 250] - finish: getSession (took 0.01s)
2021-02-06 13:02:02.229967 [ThreadId 254] - finish: importLens (took 0.12s)
2021-02-06 13:02:02.230178 [ThreadId 254] - finish: splice.codeAction.GitHieAst (took 0.12s)
2021-02-06 13:02:02.230484 [ThreadId 254] - finish: Outline (took 0.12s)
2021-02-06 13:02:02.23109 [ThreadId 255] - finish: CodeAction (took 0.12s)
2021-02-06 13:02:02.231017 [ThreadId 253] - finish: ModuleName.GetParsedModule (took 0.12s)
2021-02-06 13:02:02.231104 [ThreadId 254] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.12s)
2021-02-06 13:02:02.231316 [ThreadId 255] - finish: addPragma (took 0.12s)
2021-02-06 13:02:03.369126 [ThreadId 781] - finish: codeLens (took 1.26s)
2021-02-06 13:02:03.369164 [ThreadId 780] - finish: retrie (took 1.26s)
2021-02-06 13:02:03.370062 [ThreadId 787] - finish:  (took 1.26s)
2021-02-06 13:02:03.386333 [ThreadId 790] - finish: tactic (took 1.28s)
2021-02-06 13:02:03.386608 [ThreadId 795] - finish: tactic (took 0.00s)
2021-02-06 13:02:03.386703 [ThreadId 796] - finish: tactic (took 0.00s)
2021-02-06 13:02:03.412566 [ThreadId 799] - finish: CodeAction:PackageExports (took 1.18s)
2021-02-06 13:02:03.632239 [ThreadId 820] - finish: CodeAction (took 0.00s)
2021-02-06 13:02:03.632266 [ThreadId 824] - finish: addPragma (took 0.00s)
2021-02-06 13:02:03.63231 [ThreadId 830] - finish: importLens (took 0.00s)
2021-02-06 13:02:03.632361 [ThreadId 828] - finish: retrie (took 0.00s)
2021-02-06 13:02:03.632401 [ThreadId 826] - finish: HaddockComments.GetAnnotatedParsedSource (took 0.00s)
2021-02-06 13:02:03.632469 [ThreadId 832] - finish: tactic (took 0.00s)
2021-02-06 13:02:03.632545 [ThreadId 834] - finish: splice.codeAction.GitHieAst (took 0.00s)
2021-02-06 13:02:03.632694 [ThreadId 836] - finish: CodeAction:PackageExports (took 0.00s)
2021-02-06 13:02:03.632743 [ThreadId 838] - finish: tactic (took 0.00s)
2021-02-06 13:02:03.632832 [ThreadId 840] - finish: tactic (took 0.00s)
2021-02-06 13:02:05.193208 [ThreadId 25] - Registering ide configuration: IdeConfiguration {workspaceFolders = fromList [NormalizedUri (-5991089978266373575) "file:///Users/val/galois/crucible"], clientSettings = hashed Nothing}
2021-02-06 13:02:05.196487 [ThreadId 25] - Configuration changed: Object (fromList [("haskell",Object (fromList [("logFile",String "/tmp/hls.log"),("updateBehavior",String "prompt"),("hlintOn",Bool True),("formatOnImportOn",Bool True),("indentationRules",Object (fromList [("enabled",Bool True)])),("liquidOn",Bool False),("languageServerVariant",String "haskell-language-server"),("serverExecutablePath",String "/nix/store/hgbinji81xvnjqibncbj0fi04l1hy570-haskell-language-server-exe-haskell-language-server-0.9.0.0/bin/haskell-language-server"),("diagnosticsOnChange",Bool True),("completionSnippetsOn",Bool True),("maxNumberOfProblems",Number 100.0),("formattingProvider",String "ormolu"),("trace",Object (fromList [("server",String "off")]))]))])
2021-02-06 13:02:05.199414 [ThreadId 25] - Opened text document: file:///Users/val/galois/crucible/crux/src/Crux.hs
2021-02-06 13:02:05.200849 [ThreadId 109] - hlint:getIdeas:file:NormalizedFilePath "/Users/val/galois/crucible/crux/src/Crux.hs"
2021-02-06 13:02:05.201473 [ThreadId 113] - Consulting the cradle for "crux/src/Crux.hs"
[...]
```
</details>

**Comment by jneira** [comment] 2022-01-31 10:43
hi, cant reproduce with hls-1.5.0, ghc-8.6.5 and windows:

![imagen](https://user-images.githubusercontent.com/54035/151779680-6a02db78-db8a-49d3-8a1d-aa23e3d91ed7.png)

so i am gonna close this optimistically, feel free to reopen if you continue hitting this bug

**Closed by jneira** 2022-01-31 10:43 UTC
Labels: type: bug, status: needs repro
