### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#104] opened 2020-05-10 19:14 UTC
The README does not include any information on how to install haskell-language-server and hook it into an LSP client. Am I missing something?

**Comment by Sir4ur0n** [comment] 2020-05-11 07:10
Hi,

Seems to be a duplicate of https://github.com/haskell/haskell-language-server/issues/85

**Comment by alanz** [comment] 2020-05-13 21:00
@pepeiborra the TLDR is it installs the same way as haskell-ide-engine.  I use

```bash
./cabal-hls-install hls-8.8.3
```

Then both emacs lsp-mode and vscode-hie-server now have a simple selector between hie, hls and ghcide.

**Comment by pepeiborra** [comment] 2020-05-14 14:28
Thanks everyone. Should I close this in favor of #85?

**Comment by jneira** [comment] 2020-05-15 21:43
I am porting the hie readme here. @pepeiborra yeah, if you dont mind i'll close it in favor of #85

**Closed by jneira** 2020-05-15 21:43 UTC
Labels: type: documentation
