### ISSUE TITLE
ghcide tests fail for our GHC 8.6.4 stack deps

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#22] opened 2020-01-29 23:58 UTC
See https://circleci.com/gh/alanz/ide/9

This is part of https://circleci.com/workflow-run/9631ba2c-6905-49ca-b1cd-59ca6e0bdc68

And it is prior to making ghcide a dependency, rather than a submodule.

Perhaps we should revisit that, for now?

**Comment by alanz** [comment] 2020-01-29 23:58
cc @jneira

**Comment by jneira** [comment] 2020-01-30 09:37
Mmm, afaiu ghcide itself dont run ci on 8.6.4, only it is for the last minor version so maybe we should fix it upstream or remove 8.6.4 ourselves

**Comment by alanz** [comment] 2020-01-30 09:50
Ok. I have lost track of things, which 8.6 version is broken for window? 8.6.4?

**Comment by ndmitchell** [comment] 2020-01-30 09:52
The problem is that all the known broken tests are failing. It might be not a GHC 8.X thing, but the test library having a hiccup in that LTS. We only test on the last minor, but it's not unreasonable to have IDE test on them all, and use that to fix upstream (the number of such issues should be low, one would hope...)

**Comment by jneira** [comment] 2020-01-30 10:31
@alanz
* afaik the initial circleci report is a fail test suite in linux+stack+ghc-8.6.4
* the fail is in ghcide tests, we moved it to `extra-deps` so ghcide test suite should not be even run with the actual config
* so the errors could be arise again only in haskell-ide specific test suite, hitting them through the use of ghcide as a library

**Comment by ndmitchell** [comment] 2020-01-30 12:57
I would recommend running the ghcide test suite. It's big, and most of the errors you will get are going to arise in ghcide.

**Comment by alanz** [comment] 2020-01-30 18:42
> I would recommend running the ghcide test suite. It's big, and most of the errors you will get are going to arise in ghcide.

That was my thought too.   Especially as we don't have a test suite here yet, and it would be pointless to duplicate it.

**Comment by jneira** [comment] 2020-01-30 21:02
Ok so i will move it as local package again to run the test suite by default (now you have to run `stack test ghcide` or `cabal test ghcide`)

**Comment by alanz** [comment] 2020-01-30 21:05
Yes. And we will have to deal with the installation fallout too. Except I think that is already managed?

**Comment by jneira** [comment] 2020-01-30 21:14
Yeah, with c67e9fa

**Comment by ndmitchell** [comment] 2020-02-02 17:29
I think this is probably fixed in https://github.com/digital-asset/ghcide/pull/398.

**Comment by ndmitchell** [comment] 2020-02-03 17:35
Now fixed on master, so you should be able to reenable them.

**Comment by alanz** [comment] 2020-02-03 21:36
It worries me slightly that the ghcide fix is to punt, by disabling the test for GHC 8,6,4.

Which makes me think we may end up building an more comprehensive test suite here, because we explicitly want to test functionality for the versions we claim to support.

**Comment by ndmitchell** [comment] 2020-02-04 07:26
We're testing what the docs are in the base library, that get modified with each point release. I think that's why they only work with 8.6.5 - not the underlying code.

**Comment by jneira** [comment] 2020-05-25 05:40
It seems the ghcide tests for ghc-8.6.4 are failing with the same errors than the other versions and there is an issue about testing (#5) so i think we could close this one

**Closed** 2020-06-02 06:47 UTC
Labels: type: testing
