### ISSUE TITLE
hls does not detect new dependencies added to packages.yml

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#775] opened 2020-06-12 14:29 UTC
##### Bug description
I'm using VS Code, with the ghcide extension.

When adding a package dependency to the package.yaml, I have to reload to entire VS Code window to restart ghcide to detect and load this new dependency in ghcide.

##### Desired behaviour
ghcide should reload the dependencies when packages.yaml is updated, so that I don't have to restart it manually.

##### Version
```
$ ghcide --version
ghcide version: 0.2.0 (GHC: 8.8.3) (PATH: /nix/store/sdn0dabqvc1g25s8grq7sa9g13ax8fk7-ghcide-exe-ghcide-0.2.0/bin/ghcide)
```

using Remote SSH extension for VS Code

vscode client on Windows 10
vscode server on NixOS 20.03

I use the ghcide-nix derivation to get GHCIDE (version was recently bumped there)

**Comment by jneira** [comment] 2021-01-12 08:29
Recently this issue was noted in the irc channel by an user so i guess this is still an issue.
@fendor the plan could be still this?

>Change the API of cradle dependencies in hie-bios to give absolute paths since this is the only location where we can know this.

**Comment by GuillaumeDesforges** [comment] 2021-01-12 11:08
I can confirm the issue still happens, I often restart the HLS manually.

**Comment by jneira** [comment] 2021-08-31 14:59
i think we can close it as duplicate of #1068

**Closed by jneira** 2021-08-31 14:59 UTC
Labels: type: bug, component: hie-bios, build tool: stack, type: setup
