### ISSUE TITLE
Hlint panics on CPP when applying hint on 9.2.7

### ISSUE THREAD

**Issue by joyfulmantis** [haskell/haskell-language-server#3669] opened 2023-06-23 21:54 UTC
I am running ghc 9.2.7 with hls 2 and I am getting an error while applying a hlint hint on ironically hlint.hs in the hls project. The relevant logs are 

```
[Trace - 17:46:25] Sending request 'workspace/executeCommand - (14)'.
Params: {
    "command": "31284:hlint:applyOne",
    "arguments": [
        {
            "file": "file:///home/zhangtianci/MySourceCode/haskell-language-server/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs",
            "hintTitle": "Unused LANGUAGE pragma",
            "start_pos": {
                "character": 0,
                "line": 18
            }
        }
    ]
}


[Trace - 17:46:25] Received request 'window/workDoneProgress/create - (13)'.
Params: {
    "token": 3
}


[Trace - 17:46:25] Sending response 'window/workDoneProgress/create - (13)'. Processing request took 0ms
No result returned.


[Trace - 17:46:25] Received notification '$/progress'.
Params: {
    "token": 3,
    "value": {
        "cancellable": true,
        "kind": "begin",
        "title": "Applying hint: Unused LANGUAGE pragma"
    }
}



/tmp/Hlint31284-3.hs:105:0: error:
     錯誤：missing binary operator before token "("
      105 | #if MIN_GHC_API_VERSION(9,2,0)
          | 
    |
105 | #if MIN_GHC_API_VERSION(9,2,0)
    | ^

/tmp/Hlint31284-3.hs:143:0: error:
     錯誤：missing binary operator before token "("
      143 | #if MIN_VERSION_apply_refact(0,12,0)
          | 
    |
143 | #if MIN_VERSION_apply_refact(0,12,0)
    | ^

/tmp/Hlint31284-3.hs:183:0: error:
     錯誤：missing binary operator before token "("
      183 | #if MIN_GHC_API_VERSION(9,4,0)
          | 
    |
183 | #if MIN_GHC_API_VERSION(9,4,0)
    | ^

/tmp/Hlint31284-3.hs:686:0: error:
     錯誤：missing binary operator before token "("
      686 | #if MIN_VERSION_apply_refact(0,12,0)
          | 
    |
686 | #if MIN_VERSION_apply_refact(0,12,0)
    | ^
haskell-language-server-9.2.7: panic! (the 'impossible' happened)
  (GHC version 9.2.7:
	`gcc' failed in phase `C pre-processor'. (Exit code: 1)
CallStack (from HasCallStack):
  error, called at src/Language/Haskell/GHC/ExactPrint/Preprocess.hs:222:17 in ghc-exactprint-1.5.0-c9ae01b987437b6e946b3b447b2150e3db4a0cbdded29587a2e9ab4b1d171e06:Language.Haskell.GHC.ExactPrint.Preprocess

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

**Comment by michaelpj** [comment] 2023-06-24 12:31
Can you reproduce with `hlint --refactor` on the command line?

**Comment by michaelpj** [comment] 2023-06-24 13:04
I reproduced with `hlint --refactor`, so this is an upstream issue, and it seem ultimately an exactprint issue. cc @alanz

**Comment by joyfulmantis** [comment] 2023-06-26 11:10
I submitted a bug [here](https://github.com/mpickering/apply-refact/issues/141) too

**Comment by alanz** [comment] 2023-06-26 11:28
I still want to tackle a project to remove the need for CPP in most cases, by doing it in the parser.

Because support in ghc-exactprint is almost impossible to get right

**Comment by michaelpj** [comment] 2024-01-17 10:39
Closing as it's an upstream issue

**Closed by michaelpj** 2024-01-17 10:39 UTC
Labels: type: bug, status: blocked
