### ISSUE TITLE
Support unsaved buffers

### ISSUE THREAD

**Issue by aherrmann-da** [haskell/haskell-language-server#801] opened 2020-02-14 14:14 UTC
`ghcide` does not provide diagnostics in VSCode (version 1.42.1) buffers that don't have a corresponding existing file. 

One way to reproduce this is with the [vscode vim plugin](https://github.com/VSCodeVim/Vim/blob/master/CHANGELOG.md) (version 1.12.4):
Create a new buffer `:e Foo.hs` but do not write it to disk. Then enter content that should produce some diagnostics, e.g.
```
module Foo where
x = y
```
No diagnostics are displayed and the `ghcide` output contains the message
```
[INFO] Modified text document: untitled:/home/.../Foo.hs
```

This is not an issue in neovim (version 0.3.8) and coc (version 0.0.74-6700e7468d), where diagnostics are displayed and the output contains the message (even though the file is not written to disk)
```
[INFO] Modified text document: file:///home/.../Foo.hs
```

This was discovered in the context of import suggestions: https://github.com/digital-asset/ghcide/pull/428#discussion_r379434635. `ghcide` tracks whether a file exists, which is probably relevant to this issue. 
https://github.com/digital-asset/ghcide/blob/fd01d20cc92dce83e3e807e2db4c9532a6108cd1/src/Development/IDE/Core/FileExists.hs#L78-L85

**Comment by jneira** [comment] 2021-11-26 21:20
Same in vscode if you create a new file (you cant choose the name) without saving and then choose haskell as its language:

![imagen](https://user-images.githubusercontent.com/54035/143655723-fc4f83bf-35ad-4ba9-8ae7-a8abd460c115.png)

**Comment by jneira** [comment] 2021-12-03 09:38
I guess it will be the behaviour for any editor which allows creating buffers without writing to disk

**Comment by hasufell** [comment] 2022-07-13 17:08
Do any of the people working on the shake core know whether this is even fixable? @wz1000 @pepeiborra

**Comment by pepeiborra** [comment] 2022-07-13 22:16
The original issue is quite old. Does the problem still reproduce with a current HLS?

**Comment by hasufell** [comment] 2022-07-13 22:45
I can't really reproduce it this way. But what I tried is:

1. add a new exposed module `Foo` to my `.cabal` file
2. use a dummy cradle `cradle:\n  cabal:`
3. open a new buffer without writing the file
4. hie-bios will fail with "unrecognised target"

I'm not sure if HLS is even supposed to check empty buffers that are not part of the cradle. If you add it to the cradle, you'll get errors, because it's based on files.

Isn't that expected behavior?

----

If I open a new vim window with an empty buffer, start the LSP server... I get something like `haskell-language-server-wrapper: /home/hasufell/.cabal: openFile: inappropriate type (is a directory)`.

I'm starting to think that this case at least should work... but I'm not sure that's an issue of the client or HLS. The LSP protocol doesn't really demand existence of files, does it?

**Comment by michaelpj** [comment] 2022-07-14 08:58
In principle we don't need a file to exist: we have a VFS. In practice, the file not existing probably means that e.g. `cabal` won't know about it so we may get in trouble trying to work out the compilation flags for it.

My expectation would be that if you open an unsaved buffer for a file path that is in the project, then it *might* work, but probably we'll actually trip up when we try and work out how to compile it since cabal won't know about it. But it would be helpful if we gave a good diagnostic in this case.

For a file path outside the project... I wouldn't expect it to work at all, but actually it might just fail in the same way (don't know how to compile), so a better diagnostic might serve in both cases.

**Comment by hasufell** [comment] 2022-07-14 09:21
@michaelpj what I'd be interested in is the use case of:

1. no cabal project
2. no cradle
3. just an ad-hoc buffer

I think if a cradle or project exists, the current behavior is somewhat justifiable. 

But typechecking ad-hoc code should be supported.

**Comment by hasufell** [comment] 2022-07-14 09:48
@michaelpj I'm not sure... my point is:

1. supporting unsaved buffers for a proper project is an odd use case
2. supporting unsaved buffers for a non-project is a reasonable use case

So I'd only focus on 2.

**Comment by michaelpj** [comment] 2022-07-14 10:03
Right, my _guess_ is that the unsaved-ness is not especially problematic, but getting the cradle flags is. But I'd actually have to look into it more.

**Comment by michaelpj** [comment] 2024-01-10 12:38
I'm going to close this because I think _unsaved_ buffers work perfectly fine.

**Closed by michaelpj** 2024-01-10 12:38 UTC
Labels: type: bug, component: ghcide, status: needs info
