### ISSUE TITLE
Error when applying HLint Hint

### ISSUE THREAD

**Issue by JonathanLorimer** [haskell/haskell-language-server#1713] opened 2021-04-11 21:18 UTC
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /nix/store/z718v6a3zvrwigmdixhb8yqhn15hcrw0-haskell-language-server-0.8.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.5.1.1
ghc:		8.10.3
```
Which OS do you use: `NixOS`
Which lsp-client do you use: `nvim-lspconfig (native neovim client)`
Describe your project (alternative: link to the project): `*.cabal files`
Contents of `hie.yaml`:
```yaml
cradle:
  multi:
    - path: "./docs"
      config:
        cradle:
          none:
    - path: "./benchmark"
      config:
        cradle:
          none:
    - path: "./"
      config:
        cradle:
          cabal:
            - path: "./src"
              component: "lib:mwb"
            - path: "./test"
              component: "test:test"
            - path: "./app"
              component: "exe:mwb"
            - path: "./one-off-task"
              component: "exe:one-off-tasks"

```

### Steps to reproduce
- Create simple hlint error
- Select code action `Apply hint`

### Expected behaviour
Refactors hint

### Actual behaviour
fails

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output: Error code -32603, seems like some sort of TH error
</summary>
>NOTE: I pretty printed the json with the relevant error message, and took the liberty of pseudo formatting the error message as a multi line string for readability. I can past the ugly error message too if that is helpful. 

```
2021-04-11 16:54:33.947833813 [ThreadId 5] - ---> {"id": 4, "jsonrpc": "2.0", "method": "workspace/executeCommand", "params": {"arguments": [{"file": "file:///home/jonathanl/Mercury/mercury-web-backend/src/Mercury/Sweep/Internal.hs", "hintTitle": "Redundant id", "start_pos": {"character": 27, "line": 291}}], "title": "Apply hint: Redundant id", "command": "9940:hlint:applyOne"}}
2021-04-11 16:54:33.94870723 [ThreadId 7] - <--2--{"jsonrpc":"2.0","params":{"token":1},"method":"window/workDoneProgress/create","id":2}
2021-04-11 16:54:33.948540964 [ThreadId 50357] - hlint:applyOneCmd:file=NormalizedFilePath "/home/jonathanl/Mercury/mercury-web-backend/src/Mercury/Sweep/Internal.hs"
2021-04-11 16:54:33.949029746 [ThreadId 7] - <--2--{"jsonrpc":"2.0","params":{"value":{"kind":"begin","cancellable":true,"title":"Applying hint: Redundant id"},"token":1},"method":"$/progress"}
2021-04-11 16:54:33.949268488 [ThreadId 50358] - hlint:getIdeas:file:NormalizedFilePath "/home/jonathanl/Mercury/mercury-web-backend/src/Mercury/Sweep/Internal.hs"
2021-04-11 16:54:33.949419533 [ThreadId 50358] - finish: applyHint (took 0.00s)
2021-04-11 16:54:33.950753789 [ThreadId 5] - ---> {"id": 2, "jsonrpc": "2.0", "result": null}
2021-04-11 16:54:33.950843822 [ThreadId 5] - haskell-lsp:Got reply message:"{\"id\": 2, \"jsonrpc\": \"2.0\", \"result\": null}"
2021-04-11 16:54:33.949496467 [ThreadId 50357] - applyHint:apply=[("/home/jonathanl/Mercury/mercury-web-backend/src/Mercury/Sweep/Internal.hs:292:28-40: Warning: Redundant id\nFound:\n  id $ ruleKind\nPerhaps:\n  ruleKind\n",[Replace {rtype = Expr, pos = SrcSpan {startLine = 292, startCol = 28, endLine = 292, endCol = 41}, subts = [("x",SrcSpan {startLine = 292, startCol = 33, endLine = 292, endCol = 41})], orig = "x"}])]
2021-04-11 16:54:34.388674854 [ThreadId 50360] - finish: hlint (took 0.00s)
2021-04-11 16:54:34.422077495 [ThreadId 7] - <--2--{
  "error": {
    "code": -32603,
    "message": "
        haskell-language-server-8.10.3: panic! (the 'impossible' happened)
          (GHC version 8.10.3:
            apply
            
            /run/user/1000/Internal9940-1614.hs:221:1: error:
                parse error on input ‘$’
                Perhaps you intended to use TemplateHaskell
                Call stack:
                    CallStack (from HasCallStack):
                      callStackDoc, called at compiler/utils/Outputable.hs:1179:37 in ghc:Outputable
                            pprPanic, called at src/Refact/Internal.hs:80:13 in apply-refact-0.8.2.1-1vP0BGnmeMBJp35WjYb78z:Refact.Internal
                            
                            Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug\
                "
  },
  "jsonrpc": "2.0",
  "id": 4
}
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs: Seems to be the same error
</summary>

```
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  id = 5,  jsonrpc = "2.0",  method = "window/workDoneProgress/create",  params = {    token = 4  }}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  jsonrpc = "2.0",  method = "$/progress",  params = {    token = 4,    value = {      cancellable = true,      kind = "begin",      title = "Applying hint: Redundant id"    }  }}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...neovim-nightly-master/share/nvim/runtime/lua/vim/lsp.lua:514 ]	"server_request"	"window/workDoneProgress/create"	{  token = 4}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...neovim-nightly-master/share/nvim/runtime/lua/vim/lsp.lua:517 ]	"server_request: found handler for"	"window/workDoneProgress/create"
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...ghtly-master/share/nvim/runtime/lua/vim/lsp/handlers.lua:407 ]	"default_handler"	"window/workDoneProgress/create"	{  client_id = 1,  params = {    token = 4  }}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:500 ]	"server_request: callback result"	{  result = vim.NIL,  status = true}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:388 ]	"rpc.send.payload"	{  id = 5,  jsonrpc = "2.0",  result = vim.NIL}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...neovim-nightly-master/share/nvim/runtime/lua/vim/lsp.lua:500 ]	"notification"	"$/progress"{  token = 4,  value = {    cancellable = true,    kind = "begin",    title = "Applying hint: Redundant id"  }}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...ghtly-master/share/nvim/runtime/lua/vim/lsp/handlers.lua:407 ]	"default_handler"	"$/progress"	{  client_id = 1,  params = {    token = 4,    value = {      cancellable = true,      kind = "begin",      title = "Applying hint: Redundant id"    }  }}
[ DEBUG ] 2021-04-11T17:17:42-0400 ] ...im-nightly-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:489 ]	"decoded"	{  error = {    code = -32603,    message = "haskell-language-server-8.10.3: panic! (the 'impossible' happened)\n  (GHC version 8.10.3:\n\tapply\n\n/run/user/1000/Internal23727-1617.hs:221:1: error:\n    parse error on input ‘$’\n    Perhaps you intended to use TemplateHaskell\nCall stack:\n    CallStack (from HasCallStack):\n      callStackDoc, called at compiler/utils/Outputable.hs:1179:37 in ghc:Outputable\n      pprPanic, called at src/Refact/Internal.hs:80:13 in apply-refact-0.8.2.1-1vP0BGnmeMBJp35WjYb78z:Refact.Internal\n\nPlease report this as a GHC bug:  https://www.haskell.org/ghc/reportabug\n"  },  id = 11,  jsonrpc = "2.0"}
```
</details>

**Comment by jneira** [comment] 2021-04-12 05:26
Hi, thanks for the bug report, very likely this is a duplicate of #1589. As you can check it there it is fixed in master and in the incoming hls release. Meanwhile you can try the workaround described there.

**Closed by jneira** 2021-04-12 05:26 UTC
Labels: can-workaround, component: hlint plugin, status: fixed in master, type: bug
