### ISSUE TITLE
"Change All Occurrences (CTRL+F2)" matches too much

### ISSUE THREAD

**Issue by brikken** [haskell/haskell-language-server#1574] opened 2021-03-14 19:22 UTC
When using "Change All Occurrences (CTRL+F2)" it appears to match too much. It looks like it's doing a basic "search/replace" rather than matching on the selected symbol.

Code to reproduce
```
module Main where

import qualified Data.Time as Time ( Day, fromGregorian )

data Day = Day Int Int Int

myDay :: Day
myDay = Day 2021 3 14

myRealDay :: Time.Day 
myRealDay = Time.fromGregorian 2021 3 14

main :: IO ()
main = putStrLn "Hello, Haskell!"
```

Place the caret on the `data` definition of `Day`. Notice that only the relevant symbols are now highlighted by the editor (ie. the `data` definition and the type declaration of `myDay`).

![image](https://user-images.githubusercontent.com/17687681/111081180-5c4e5b80-8502-11eb-95a9-4f8da436584c.png)

Now hit CTRL+F2. Notice that now all simple text matches of `Day` are selected and updated when changing the text.

![image](https://user-images.githubusercontent.com/17687681/111081190-66705a00-8502-11eb-84cb-3477f54b7a57.png)

```
Version: 1.54.2 (user setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

Extension v1.2.0

[output.txt](https://github.com/haskell/vscode-haskell/files/6137408/output.txt)

**Comment by jneira** [comment] 2021-03-15 06:24
I've moved the issue to haskell-language-server as the bad behaviour is caused by the server as @fendor mentioned.
The main issue about add renaming (via retrie plugin) would be: https://github.com/haskell/haskell-language-server/issues/282

**Comment by jneira** [comment] 2021-03-22 12:27
Ok, i am gonna close this one, @brikken you could track the progress of the feature in the mentioned issue #282

**Closed by jneira** 2021-03-22 12:27 UTC
Labels: component: retrie plugin, type: enhancement
