### ISSUE TITLE
Unboxed Tuples Sums and bytecode...

### ISSUE THREAD

**Issue by awgn** [haskell/haskell-language-server#1393] opened 2021-02-18 07:42 UTC
Hi there,

Not sure if this is a bug of ghcide or my fault, but I can't find a workaround for the annoying "Program error: bytecode compiler can't handle unboxed tuples and sums" when the module is indeed using unboxed tuples or sums (I got this with ghc 8.6.x 8.8.x or 8.10.x).

Where should I have to put the "-fobject-code" option? I added it to the ghc-options in cabal, but it didn't fix the problem.
Best, 

N.

**Comment by jneira** [comment] 2021-02-18 08:11
There is an ongoing pull request about that issue (or it seems to me that could be related): https://github.com/haskell/haskell-language-server/pull/1382

**Comment by jneira** [comment] 2021-06-20 21:04
It seems this is a Duplicate of #771 (or is closely related). I am gonna close it, feel free to reopen if you think they are different ones.

**Closed by jneira** 2021-06-20 21:04 UTC
Labels: component: ghcide, type: bug, type: question
