### ISSUE TITLE
stuck initializing in atom on mac osx

### ISSUE THREAD

**Issue by eflister** [haskell/haskell-language-server#416] opened 2020-09-20 07:51 UTC
### Subject of the issue
a little blinking orange light along the bottom of atom says "hie initializing" indefinitely.  i don't see any ide features.

### Your environment

`atom 1.51.0` 
`stack 2.3.3` 
`osx 10.15.6`

- `stack` is on my path, set for `lts-16.13` (`ghc-8.8.4`)

- i manually installed a system `ghc 8.8.4` from https://www.haskell.org/ghcup/ to hide an older one on the path.  can you use the local one in the stack project instead of the system one?  i'm worried that the path to this correct `ghc` is only added by `.bashrc`, which atom may not see, if only bash shells load that...  how do i check/fix?

[1] https://github.com/haskell/haskell-language-server/releases/download/0.4.0/haskell-language-server-macOS-8.8.4.gz
[2] https://github.com/haskell/haskell-language-server/releases/download/0.4.0/haskell-language-server-wrapper-macOS.gz
- unzipped [1] + [2] to `~/.local/bin` (which is on my path) and `chmod` to `755`.  in the finder, the wrapper icon changed to an exe, but the other one remained a generic document, if that is a clue?
- had to remove `macOS` from the exe cuz manually running the wrapper shows it wasn't expecting the `macOS` part
- osx security tries to block both exe's, have to go either to Security & Privacy preferences or Control-click the app icon, then choose Open from the shortcut menu. then the app is saved as an exception to your security settings

- install instructions should include the chmod and renaming and security instructions (or wrapper should try including the `macOS` part)

[3] https://atom.io/packages/atom-ide-ui
[4] https://atom.io/packages/ide-haskell-hie
[5] https://atom.io/packages/language-haskell
- added [3] [4] [5] to atom, set absolute path to exe `~/.local/bin/haskell-language-server-wrapper-macOS`, hie wrapper and debugging output are checked

[6] https://github.com/Avi-D-coder/implicit-hie
- in a project dir i had previously set up with `stack new`, `stack setup`, used [6]: `gen-hie > hie.yaml`

* Output of `haskell-language-server --probe-tools`
```
$ haskell-language-server-8.8.4 --probe-tools
haskell-language-server version: 0.4.0.0 (GHC: 8.8.4) (PATH: /Users/eflister/.local/bin/haskell-language-server-8.8.4) (GIT hash: 0a18edde24923251a148cbbc0ae993a6aac83b9c)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.8.4
```

or `haskell-language-server-wrapper --probe-tools`
```
$ haskell-language-server-wrapper-macOS --probe-tools
haskell-language-server version: 0.4.0.0 (GHC: 8.10.1) (PATH: /Users/eflister/.local/bin/haskell-language-server-wrapper-macOS) (GIT hash: 0a18edde24923251a148cbbc0ae993a6aac83b9c)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.8.4
```
-why does this one mention ghc 8.10.1?  i don't have it...

* Which lsp-client do you use
atom

* Describe your project (alternative: link to the project)
  * Include `stack.yaml`
```
resolver: lts-16.13
packages:
- .
```

  * Include `package.yaml`
standard from `stack new`, `stack setup`, added some dependencies

  * Include `*.cabal` files
standard from `stack new`, `stack setup`

  * Include `cabal.project`
none

* Contents of `hie.yaml`
used `gen-hie > hie.yaml`
```
cradle:
  stack:
    - path: "./src"
      component: "covid:lib"

    - path: "./app/Main.hs"
      component: "covid:exe:covid-exe"

    - path: "./app/Paths_covid.hs"
      component: "covid:exe:covid-exe"

    - path: "./test"
      component: "covid:test:covid-test"
```

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

is it supposed to be called that?  the download unzips to `haskell-language-server-macOS-8.8.4`, which i renamed to `haskell-language-server-8.8.4` because `haskell-language-server-wrapper-macOS` doesn't expect the `macOS` part.

<details>
<summary>
Debug output:
</summary>

```
$ haskell-language-server-wrapper-macOS 
Found "/Users/eflister/covid/covid/hie.yaml" for "/Users/eflister/covid/covid/a"
Module "/Users/eflister/covid/covid/a" is loaded by Cradle: Cradle {cradleRootDir = "/Users/eflister/covid/covid", cradleOptsProg = CradleAction: Stack}
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-macOS) Version 0.4.0.0, Git revision 0a18edde24923251a148cbbc0ae993a6aac83b9c (dirty) x86_64 ghc-8.10.1
Current directory: /Users/eflister/covid/covid
Operating system: darwin
Arguments: []
Cradle directory: /Users/eflister/covid/covid
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.8.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.8.4
haskell-language-server exe candidates: ["haskell-language-server-8.8.4","haskell-language-server-8.8","haskell-language-server"]
Launching haskell-language-server exe at:/Users/eflister/.local/bin/haskell-language-server-8.8.4
haskell-language-server version: 0.4.0.0 (GHC: 8.8.4) (PATH: /Users/eflister/.local/bin/haskell-language-server-8.8.4) (GIT hash: 0a18edde24923251a148cbbc0ae993a6aac83b9c)
(haskell-language-server)Ghcide setup tester in /Users/eflister/covid/covid.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.8.4


Step 1/4: Finding files to test in /Users/eflister/covid/covid
Found 69 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "/Users/eflister/covid/covid/pdf-toolbox-content/test/Test/FontDescriptor.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/Users/eflister/covid/covid", cradleOptsProg = CradleAction: Stack}
File:     /Users/eflister/covid/covid/pdf-toolbox-content/test/Test/FontDescriptor.hs
Hidden:   no
Range:    1:0-2:0
Source:   cradle
Severity: DsError
Message: 
  Multi Cradle: No prefixes matched
  pwd: /Users/eflister/covid/covid
  filepath: /Users/eflister/covid/covid/pdf-toolbox-content/test/Test/FontDescriptor.hs
  prefixes:
  ("./src",Stack {component = Just "covid:lib"})
  ("./app/Main.hs",Stack {component = Just "covid:exe:covid-exe"})
  ("./app/Paths_covid.hs",Stack {component = Just "covid:exe:covid-exe"})
  ("./test",Stack {component = Just "covid:test:covid-test"})

...same error repeats many times

Completed (3 files worked, 66 files failed)
haskell-language-server-wrapper-macOS: callProcess: /Users/eflister/.local/bin/haskell-language-server-8.8.4 (exit 66): failed
```
the failing files are all from this project's local copy of https://github.com/Yuras/pdf-toolbox.  the project works fine with stack.

</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

is this supposed to be `/tmp/hie.log`?  cuz i only have `/tmp/hie-wrapper.log`.  no idea why it is mentioning `ghc 8.4`...
i don't see anything when filtering for `hie` in atom's console except one warning:
```
Haskell (hie) rpc.onClose The RPC connection closed unexpectedly
/Users/eflister/.atom/packages/ide-haskell-hie/node_modules/atom-languageclient/build/lib/logger.js @9
```

<details>
<summary>
LSP logs:
</summary>

```
$ cat /tmp/hie-wrapper.log 
Launching HIE for project located at /Users/eflister/covid/covid
  Using stack GHC and HIE
  The Glorious Glasgow Haskell Compilation System, version 8.8.4
  Project is using GHC 8.4.*
... same block repeated several times
```
</details>

**Comment by jneira** [comment] 2020-09-20 21:04
Hi, thanks for the detailed bug report:
* About the installation process
  * The executables inside those .gz files has not the `-macOs` extension, afaics opening them in my windows system
  * You are right about `chmod` and the security steps, they should be added to the installation instructions (pull requests welcome! 😄 ) 

* About executing it: 
  * It seems to me from the log that the generated `hie.yaml` is not well adjusted with the structure of the project. It does not list `pdf-toolbox-content/test` as a known path for example. Could you add a link to the project if it is open source or a description of the directory structure?

**Comment by eflister** [comment] 2020-09-21 00:30
>   * The executables inside those .gz files has not the `-macOs` extension, afaics opening them in my windows system

on osx, i download in chrome, double click in finder (invokes apple's built in `Archive Utiliy.app` from `/System/Library/CoreServices/Applications/`), and get filename: `haskell-language-server-macOS-8.8.4`

>   * It seems to me from the log that the generated `hie.yaml` is not well adjusted with the structure of the project. It does not list `pdf-toolbox-content/test` as a known path for example. Could you add a link to the project if it is open source or a description of the directory structure?

ok, i didn't think that could matter.  so now i made the simplest stack project that doesn't include `pdf-toolbox`.  when i open the main `src/ Lib.hs` file in atom, i get a green light and IDE!

in the original project that did include `pdf-toolbox`, the only differences are that i copied `pdf-toolbox`'s three directories into the project directory, and added them to `stack.yaml` -- sorry i had left them out of the original report thinking they weren't relevant.
```
extra-deps:
- pdf-toolbox-document
- pdf-toolbox-core
- pdf-toolbox-content
```

so in that case the directory structure is just:
```
.stack-work/
ChangeLog.md
LICENSE
README.md
Setup.hs
app/
cache/
hie.yaml
package.yaml
src/
stack.yaml
stack.yaml.lock
test/
test.cabal
pdf-toolbox-content/
pdf-toolbox-core/
pdf-toolbox-document/
```
so how do i tell `hie.yaml` about `pdf-toolbox`?

back in my simple project that doesn't include `pdf-toolbox`, after fixing a compile error related to excising `pdf-toolbox`, saving, and trying to rebuild, i got a red box indicating an HIE error with a button `Create issue on the atom-ide-ui-package`, but the button doesn't seem to do anything.  there's a copy button that i've pasted the results from below.  the status says HIE exited code 1, and stuff didn't work anymore.  reopening atom gives me the flashing orange light/initializing forever.  opening just my src file in atom gives me a green light + IDE, then adding the directory to the project, also gives flashing orange if i choose "recover state."  but it stays green if i discard state.  from there i was able to successfully build.  but i don't see how to run or launch ghci/repl.  `menu > Haskell IDE > Open REPL` does nothing.

it might be that i've added some incompatible packages to atom in hunting for something that works.  should i remove those other than HIE?

copy button clipboard:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.13.0


### Stack Trace

Uncaught TypeError: diagnostic.text.includes is not a function

```
At /Users/eflister/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71

TypeError: diagnostic.text.includes is not a function
    at /packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/DiagnosticsView.js:239:60
    at Array.find (<anonymous>)
    at DiagnosticsView.render (/packages/atom-ide-ui/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/DiagnosticsView.js:238:51)
    at Kg (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:167:226)
    at Rg (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:180:75)
    at xh (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:202:22)
    at yh (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:203:234)
    at Vh (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:212:353)
    at Yh (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:211:278)
    at Wh (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:211:113)
    at Ah (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:209:281)
    at og (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:207:333)
    at Object.enqueueSetState (/packages/atom-ide-ui/node_modules/react-dom/cjs/react-dom.production.min.js:148:225)
    at Object.F.setState (/packages/atom-ide-ui/node_modules/react/cjs/react.production.min.js:12:357)
    at a._next (/packages/atom-ide-ui/modules/nuclide-commons-ui/bindObservableAsProps.js:46:14)
    at a.__tryOrUnsub (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:184:285)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._tryProject (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:92:235)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:92:51)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._tryProject (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:92:235)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:92:51)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:105:241)
    at a._next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/atom-ide-ui/modules/nuclide-commons/observable.js:412:66)
    at later (/packages/atom-ide-ui/modules/nuclide-commons/debounce.js:40:23)
```

### Commands

```
     -5:43.2.0 core:move-up (input.hidden-input)
     -5:41.2.0 core:move-right (input.hidden-input)
     -5:40.8.0 core:backspace (input.hidden-input)
     -5:38 core:move-right (input.hidden-input)
     -5:38 core:move-down (input.hidden-input)
     -5:37.4.0 core:move-up (input.hidden-input)
     -4:47 editor:newline (input.hidden-input)
     -4:45.8.0 core:move-right (input.hidden-input)
     -4:45.5.0 core:backspace (input.hidden-input)
  6x -4:45 core:move-down (input.hidden-input)
     -4:42.2.0 editor:newline (input.hidden-input)
     -4:41.2.0 core:save (input.hidden-input)
 16x -1:57.4.0 diagnostics:toggle-table (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.ide-haskell)
     -0:39.7.0 core:move-left (input.hidden-input)
  2x -0:39.3.0 core:backspace (input.hidden-input)
     -0:22.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-haskell 0.4.0 
atom-ide-ui 0.13.0 
autocomplete-haskell 1.0.1 
busy-signal 2.0.1 
haskell-ghc-mod 2.2.6 
haskell-hoogle 0.1.3 
haskell-pointfree 0.2.0 
haskell-scry 1.0.9 
hasklig 0.4.0 
ide-haskell 2.4.1 
ide-haskell-cabal 2.5.0 
ide-haskell-ghcide 0.5.0 
ide-haskell-hasktags 0.0.17 
ide-haskell-hie 0.12.0 
ide-haskell-hlint 0.1.2 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.10.0 
intentions 1.1.5 
language-haskell 1.20.0 
language-haskell-scoped 0.1.2 
linter 2.3.1 
linter-pylint 2.1.1 
linter-ui-default 1.8.1 
```

**Comment by eflister** [comment] 2020-09-21 01:19
> > * The executables inside those .gz files has not the `-macOs` extension, afaics opening them in my windows system
> 
> on osx, i download in chrome, double click in finder (invokes apple's built in `Archive Utiliy.app` from `/System/Library/CoreServices/Applications/`), and get filename: `haskell-language-server-macOS-8.8.4`

same results from `gunzip` in terminal.

**Comment by unhammer** [comment] 2020-09-21 11:55
The files at https://github.com/haskell/haskell-language-server/releases/tag/0.4.0 are just gzipped files, not tarballs, so they need to be renamed before they can be used (I ran into the same problem with the linux files). A papercut for new users; installation would be friendlier if they were tar.gz files with the right name inside.

**Comment by eflister** [comment] 2020-09-25 01:08
ok, just removing `hie.yaml` allowed it to work with `pdf-toolbox`.  but i am not seeing many ide features.  i get a "Haskell IDE" menu, but i don't get any kind of type info when i hover, completion prompts, jumps to docs/definitions/usages, etc.  i can get a REPL from the menu item, but it is awful to use -- it doesn't even use a fixed-width font (i don't see a way to configure the font), i have to copy/paste lines of code into it (no context menu item to send a selection of code) and use a mouse click to evaluate it (no menu items or button tooltips indicate any keyboard shortcuts, so they are not readily discoverable).  no items in the context menu for code selection `ghc-mod >` do anything.  `beautify` `prettify` and `Format Code` don't do anything (except i think one formatted my imports).  `Debugger > Launch` says no debuggers installed.

this isn't what `haskell-language-server` is supposed to be is it?  do you recommend using something other than atom, or is there some fix to my configuration?

i often get a tooltip that says "haskell-ghc-mod Error: spawn ghc-mod ENOENT" even though it sometimes shows `haskell-ghc-mod` with a checkmark.

i tried adding some features that use [`hvega`](https://hackage.haskell.org/package/hvega) with `import Graphics.Vega.VegaLite` (of course adding it to `package.yaml`).  in atom, i got appropriate compiler warnings to fix some things, but once they were correct, atom stopped being able to find `hvega`?  in a terminal, `stack` builds just fine, but `IDE-Haskell` build fails with `Could not find module ‘Graphics.Vega.VegaLite’`.

a similar thing happened when i tried using `aeson` - `Could not load module ‘Data.Aeson’
It is a member of the hidden package ‘aeson-1.4.7.1’.`  again, `stack` builds it fine in a terminal.

**Comment by fendor** [comment] 2020-09-25 07:56
I think you have way too many haskell related extensions. The errors could be from *anywhere*. `ghc-mod` is really old and not used at all by HLS, HLS also has no REPL support, commands such as `beautify` and `prettify` are also not provided by HLS. But it is true, we are not providing a debugger.

My suggestion is to remove everything except the core HLS extension, but I am not even sure we have that on the Atom marketplace? @bubba can you confirm?
If you are not that emotionally connected to Atom, you can give VSCode or [VSCodium](https://vscodium.com/)(which is telemetry free) a try with the [Haskell](https://marketplace.visualstudio.com/items?itemName=haskell.haskell) extension, which should take care of almost everything.

**Comment by eflister** [comment] 2020-09-25 16:07
ok, i guess most of those came from [atom haskell](https://atom-haskell.github.io/), which i think was providing most of what i thought was from HLS.

i disabled all except `language-haskell`, `atom-ide-ui`, `ide-haskell-hie`.

the [installation instructions](https://github.com/haskell/haskell-language-server#using-haskell-language-server-with-atom) are self-conflicting on whether to install `language-haskell` but i wasn't even getting syntax coloring without it.

i restarted, and don't see any ide features, the `Haskell IDE` menu is gone, i get no hover type info, and i don't even see how to build.  i do sometimes get a blue light in the status bar that is again stuck forever on "hie initializing," but usually it is gone completely.  how do i check that HLS is running at all?  the `-- >>>` codelens doesn't do anything, i'm not seeing any of the features [described](https://github.com/moodmosaic/ide-haskell-ghcide#features) for `ghcide` or [those](https://github.com/haskell/haskell-ide-engine#features) for `haskell-ide`...

i am amenable to trying VSCode, but would like to try to get atom working first if possible.

**Comment by fendor** [comment] 2020-09-25 16:33
I don't know about these plugins and how they work. 

BTW, I think you should rename the wrapper to `haskell-language-server-wrapper`.
Regarding `hie.yaml`, you can generate one via https://github.com/Avi-D-coder/implicit-hie, install that executable and invoke "gen-hie > hie.yaml".

Can you also try to invoke `haskell-language-server-wrapper --debug ./src/`and paste the logs here? If that roughly works, then the problem is the atom plugin.

**Comment by eflister** [comment] 2020-09-25 17:56
> BTW, I think you should rename the wrapper to `haskell-language-server-wrapper`.

can you explain why, since i set up the absolute path in the plugin settings?

> Regarding `hie.yaml`, you can generate one via https://github.com/Avi-D-coder/implicit-hie, install that executable and invoke "gen-hie > hie.yaml".

do you see in the OP that i originally tried that?  or is there a reason to do it again?

> Can you also try to invoke `haskell-language-server-wrapper --debug ./src/`and paste the logs here? 

```
$ haskell-language-server-wrapper-macOS --debug ./src/
Module "/Users/eflister/covid/covid/a" is loaded by Cradle: Cradle {cradleRootDir = "/Users/eflister/covid/covid", cradleOptsProg = CradleAction: Stack}
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-macOS) Version 0.4.0.0, Git revision 0a18edde24923251a148cbbc0ae993a6aac83b9c (dirty) x86_64 ghc-8.10.1
Current directory: /Users/eflister/covid/covid
Operating system: darwin
Arguments: ["--debug","./src/"]
Cradle directory: /Users/eflister/covid/covid
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.8.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.8.4
haskell-language-server exe candidates: ["haskell-language-server-8.8.4","haskell-language-server-8.8","haskell-language-server"]
Launching haskell-language-server exe at:/Users/eflister/.local/bin/haskell-language-server-8.8.4
haskell-language-server version: 0.4.0.0 (GHC: 8.8.4) (PATH: /Users/eflister/.local/bin/haskell-language-server-8.8.4) (GIT hash: 0a18edde24923251a148cbbc0ae993a6aac83b9c)
(haskell-language-server)Ghcide setup tester in /Users/eflister/covid/covid.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.8.4


Step 1/4: Finding files to test in /Users/eflister/covid/covid
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "/Users/eflister/covid/covid/src/Lib.hs"
Output from setting up the cradle Cradle {cradleRootDir = "/Users/eflister/covid/covid", cradleOptsProg = CradleAction: Stack}
> Using main module: 1. Package `covid' component covid:exe:covid-exe with main-is file: /Users/eflister/covid/covid/app/Main.hs
> covid> configure (lib + exe)
> Configuring covid-0.1.0.0...
> covid> initial-build-steps (lib + exe)
> The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
> Configuring GHCi with the following packages: covid
> /Users/eflister/covid/covid/.stack-work/install/x86_64-osx/960ac9c98f0b578dfff7dc5960bb24b46d9b1e4d8d2d5299b34ee8ab3cf0153d/8.8.4/pkgdb:/Users/eflister/.stack/snapshots/x86_64-osx/960ac9c98f0b578dfff7dc5960bb24b46d9b1e4d8d2d5299b34ee8ab3cf0153d/8.8.4/pkgdb:/Users/eflister/.stack/programs/x86_64-osx/ghc-8.8.4/lib/ghc-8.8.4/package.conf.d
[INFO] Using interface files cache dir: /Users/eflister/.cache/ghcide/main-42933ff99e3775832ea7f0c8db53758b82047965
[INFO] Making new HscEnv[main]
File:     /Users/eflister/covid/covid/src/Lib.hs
Hidden:   no
Range:    166:15-166:46
Source:   parser
Severity: DsWarning
Message:  Haddock parse error on input ‘-- $ M2.filterRow (`elem` zs) t’

Completed (1 file worked, 0 files failed)
```

> If that roughly works, then the problem is the atom plugin.

is there a separate issue tracker for that?

**Comment by fendor** [comment] 2020-09-25 19:26
> can you explain why, since i set up the absolute path in the plugin settings?

Did not see that, sorry, then just forget what I said.

> do you see in the OP that i originally tried that? or is there a reason to do it again?

Right, I didn't see it, my apologies.

---

good news, your hls seems to be working, the logs seem good to me.

> is there a separate issue tracker for that?

I don't know how the Atom plugin works or even which of the plugin is the right one :/


I am really not helpful here.

**Comment by jneira** [comment] 2021-03-21 22:23
could we confirm the origin of the issue in the atom plugin?
some other hls atom user out there to help to reproduce the issue?

**Comment by michaelpj** [comment] 2024-01-11 09:36
Old support issue, closing

**Closed by michaelpj** 2024-01-11 09:36 UTC
Labels: type: bug, status: blocked, os: macos, build tool: stack
