### ISSUE TITLE
Bug when applying hlint hint

### ISSUE THREAD

**Issue by santiweight** [haskell/haskell-language-server#1625] opened 2021-03-26 09:32 UTC
MacOS using HLS HEAD as of March 26

Which lsp-client do you use:
VS Code

Describe your project (alternative: link to the project):
stack lib with test component

Contents of `hie.yaml`:

```yaml
cradle:
  stack:
    - path: "./src"
      component: "config-parser:lib"
    - path: "./test"
      component: "config-parser:config-parser-test
```

### Steps to reproduce
I think this is not a step-by-step bug but some kind of functional error. It seems related to the json format and I imagine the LSP api.
### Expected behaviour
<img width="393" alt="Screenshot 2021-03-26 at 2 29 32 AM" src="https://user-images.githubusercontent.com/16826028/112611499-226f3600-8ddb-11eb-8657-5bc603b98149.png">

For the above code situation, apply the `Move brackets to avoid $` hint
I would expect that when applying the `Move brackets to avoid $` hint that the parentheses would be moved and $ removed. Instead nothing happens and this error is output in the log.

### Actual behaviour

Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:
```
2021-03-26 02:25:14.869943 [ThreadId 38021] INFO hls:	hlint:applyOneCmd:file=NormalizedFilePath "/Users/santiweight/config-parser/test/Spec.hs"
2021-03-26 02:25:14.870124 [ThreadId 38022] INFO hls:	hlint:getIdeas:file:NormalizedFilePath "/Users/santiweight/config-parser/test/Spec.hs"
2021-03-26 02:25:14.870243 [ThreadId 38022] INFO hls:	finish: applyHint (took 0.00s)
[Error - 2:25:14 AM] haskell-lsp:incoming message parse error. {"jsonrpc":"2.0","id":44,"result":null} Error in $.result: parsing () failed, expected Array, but encountered Null

2021-03-26 02:25:14.870259 [ThreadId 38021] INFO hls:	applyHint:apply=[[Replace {rtype = Expr, pos = SrcSpan {startLine = 50, startCol = 18, endLine = 50, endCol = 37}, subts = [("a",SrcSpan {startLine = 50, startCol = 19, endLine = 50, endCol = 23}),("b",SrcSpan {startLine = 50, startCol = 26, endLine = 50, endCol = 36})], orig = "a (b)"}]]
2021-03-26 02:25:14.948832 [ThreadId 38024] INFO hls:	finish: applyHint (took 0.00s)
2021-03-26 02:25:14.948898 [ThreadId 38026] INFO hls:	finish: applyHint (took 0.00s)
2021-03-26 02:25:14.948963 [ThreadId 38028] INFO hls:	finish: applyHint (took 0.00s)
Missing file: /Users/runner/.ghcup/ghc/8.10.3/lib/ghc-8.10.3/settings
2021-03-26 02:25:14.949104 [ThreadId 38018] ERROR hls:	Unexpected exception on request, please report!
Exception: ExitFailure 1
[Error - 2:25:14 AM] Request workspace/executeCommand failed.
  Message: ExitFailure 1
  Code: -32603 
2021-03-26 02:25:14.950355 [ThreadId 38043] INFO hls:	fini
```
<details>
<summary>
Debug output:
</summary>

**Comment by jneira** [comment] 2021-03-26 15:53
hi, thank for the detailed report, I think this might be the same issue as https://github.com/haskell/haskell-language-server/issues/1589
it could be confirmed if you can apply some of the workarounds described therr

**Comment by jneira** [comment] 2021-04-06 09:05
@santiweight i am gonna close this one optimistically as duplicate of #1589, feel free to reopen if you think it is a different issue

**Closed by jneira** 2021-04-06 09:05 UTC
Labels: component: hlint plugin, status: needs confirmation, type: bug
